# Meridian Partner Commerce Health and Settlement Reconciliation

**Notebook:** 01_syndata

This project uses entirely synthetic data for a fictional company. It is unaffiliated with NEXT plc and does not use NEXT or any partner's confidential data.

## Notebook objective

In this notebook we will set up the project, create a reproducible configuration, and prepare folders for raw synthetic source files. We will generate the data in a later cell once the setup is working.

In [13]:
from pathlib import Path
from datetime import datetime
import json
import random

import numpy as np
import pandas as pd

print("Python setup loaded successfully")

Python setup loaded successfully

In [14]:
# Reproducibility settings
RANDOM_SEED = 20260925

random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)

PROJECT_NAME = "meridian_partner_commerce_health"
PROJECT_START = "2025-01-01"
PROJECT_END = "2026-06-30"
REPORTING_CURRENCY = "GBP"

print(f"Project: {PROJECT_NAME}")
print(f"Period: {PROJECT_START} to {PROJECT_END}")
print(f"Random seed: {RANDOM_SEED}")

Project: meridian_partner_commerce_health
Period: 2025-01-01 to 2026-06-30
Random seed: 20260925

In [15]:
# Create a simple project folder structure
BASE_DIR = Path.cwd()

DATA_DIR = BASE_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
REFERENCE_DIR = DATA_DIR / "reference"
PROCESSED_DIR = DATA_DIR / "processed"
OUTPUT_DIR = BASE_DIR / "outputs"

for folder in [
    RAW_DIR,
    REFERENCE_DIR,
    PROCESSED_DIR,
    OUTPUT_DIR
]:
    folder.mkdir(parents=True, exist_ok=True)

print("Project folders are ready:")

for folder in [
    RAW_DIR,
    REFERENCE_DIR,
    PROCESSED_DIR,
    OUTPUT_DIR
]:
    print(f" - {folder}")

Project folders are ready:
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/raw
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/reference
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/outputs

In [16]:
# Store the project configuration so later notebooks use the same settings

from datetime import datetime, timezone

config = {
    "project_name": PROJECT_NAME,
    "project_start": PROJECT_START,
    "project_end": PROJECT_END,
    "reporting_currency": REPORTING_CURRENCY,
    "random_seed": RANDOM_SEED,
    "created_at_utc": datetime.now(timezone.utc).isoformat(timespec="seconds")
}

CONFIG_PATH = BASE_DIR / "project_config.json"

CONFIG_PATH.write_text(
    json.dumps(config, indent=2)
)

print(f"Configuration saved to: {CONFIG_PATH}")
print(json.dumps(config, indent=2))

Configuration saved to: /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/project_config.json
{
  "project_name": "meridian_partner_commerce_health",
  "project_start": "2025-01-01",
  "project_end": "2026-06-30",
  "reporting_currency": "GBP",
  "random_seed": 20260925,
  "created_at_utc": "2026-10-04T19:17:12+00:00"
}

## Create fictional reference data

These reference tables represent Meridian Market Group's internal catalogue and partner configuration.

They are fully synthetic and are not based on NEXT plc, its partners, its products, or its internal systems.

In [18]:
# Create fictional partner and country reference data

rng = np.random.default_rng(RANDOM_SEED)

partner_ref = pd.DataFrame([
    {
        "partner_id": "CH_A",
        "partner_name": "Channel A",
        "channel_type": "marketplace",
        "base_currency": "GBP",
        "reporting_frequency": "daily",
        "active_from": "2025-01-01",
        "active_to": "2026-12-31"
    },
    {
        "partner_id": "CH_B",
        "partner_name": "Channel B",
        "channel_type": "department_store",
        "base_currency": "EUR",
        "reporting_frequency": "daily",
        "active_from": "2025-01-01",
        "active_to": "2026-12-31"
    },
    {
        "partner_id": "CH_C",
        "partner_name": "Channel C",
        "channel_type": "regional_platform",
        "base_currency": "EUR",
        "reporting_frequency": "weekly",
        "active_from": "2025-03-01",
        "active_to": "2026-12-31"
    },
    {
        "partner_id": "CH_D",
        "partner_name": "Channel D",
        "channel_type": "social_commerce",
        "base_currency": "SEK",
        "reporting_frequency": "daily",
        "active_from": "2025-06-01",
        "active_to": "2026-12-31"
    }
])

partner_ref["active_from"] = pd.to_datetime(partner_ref["active_from"])
partner_ref["active_to"] = pd.to_datetime(partner_ref["active_to"])

country_ref = pd.DataFrame([
    {"country_code": "GB", "country_name": "United Kingdom", "currency_code": "GBP", "region": "UK", "synthetic_tax_rate": 0.20},
    {"country_code": "IE", "country_name": "Ireland", "currency_code": "EUR", "region": "Western Europe", "synthetic_tax_rate": 0.23},
    {"country_code": "DE", "country_name": "Germany", "currency_code": "EUR", "region": "Western Europe", "synthetic_tax_rate": 0.19},
    {"country_code": "FR", "country_name": "France", "currency_code": "EUR", "region": "Western Europe", "synthetic_tax_rate": 0.20},
    {"country_code": "NL", "country_name": "Netherlands", "currency_code": "EUR", "region": "Western Europe", "synthetic_tax_rate": 0.21},
    {"country_code": "BE", "country_name": "Belgium", "currency_code": "EUR", "region": "Western Europe", "synthetic_tax_rate": 0.21},
    {"country_code": "ES", "country_name": "Spain", "currency_code": "EUR", "region": "Southern Europe", "synthetic_tax_rate": 0.21},
    {"country_code": "IT", "country_name": "Italy", "currency_code": "EUR", "region": "Southern Europe", "synthetic_tax_rate": 0.22},
    {"country_code": "SE", "country_name": "Sweden", "currency_code": "SEK", "region": "Northern Europe", "synthetic_tax_rate": 0.25},
    {"country_code": "DK", "country_name": "Denmark", "currency_code": "DKK", "region": "Northern Europe", "synthetic_tax_rate": 0.25}
])

print("Partners created:", len(partner_ref))
print("Countries created:", len(country_ref))

display(partner_ref)
display(country_ref)

Partners created: 4
Countries created: 10

,partner_id,partner_name,channel_type,base_currency,reporting_frequency,active_from,active_to
0,CH_A,Channel A,marketplace,GBP,daily,2025-01-01,2026-12-31
1,CH_B,Channel B,department_store,EUR,daily,2025-01-01,2026-12-31
2,CH_C,Channel C,regional_platform,EUR,weekly,2025-03-01,2026-12-31
3,CH_D,Channel D,social_commerce,SEK,daily,2025-06-01,2026-12-31

,country_code,country_name,currency_code,region,synthetic_tax_rate
0,GB,United Kingdom,GBP,UK,0.20
1,IE,Ireland,EUR,Western Europe,0.23
2,DE,Germany,EUR,Western Europe,0.19
3,FR,France,EUR,Western Europe,0.20
4,NL,Netherlands,EUR,Western Europe,0.21
5,BE,Belgium,EUR,Western Europe,0.21
6,ES,Spain,EUR,Southern Europe,0.21
7,IT,Italy,EUR,Southern Europe,0.22
8,SE,Sweden,SEK,Northern Europe,0.25
9,DK,Denmark,DKK,Northern Europe,0.25

In [19]:
# Create a fictional internal product catalogue

N_PRODUCTS = 3000

categories = [
    "Womenswear",
    "Menswear",
    "Kidswear",
    "Footwear",
    "Accessories",
    "Home"
]

category_weights = [0.28, 0.20, 0.15, 0.14, 0.10, 0.13]

brand_names = [
    "Northline",
    "Harbour & Pine",
    "Mosaic House",
    "Everwell",
    "Juniper Lane",
    "Cedar & Coast",
    "Aster Row",
    "Fieldstone",
    "Lumen Studio",
    "Kindred Goods",
    "Oak & Vale",
    "Solace"
]

sizes_by_category = {
    "Womenswear": ["XS", "S", "M", "L", "XL"],
    "Menswear": ["S", "M", "L", "XL", "XXL"],
    "Kidswear": ["2Y", "4Y", "6Y", "8Y", "10Y", "12Y"],
    "Footwear": ["36", "37", "38", "39", "40", "41", "42", "43", "44"],
    "Accessories": ["One Size"],
    "Home": ["Small", "Medium", "Large"]
}

weight_ranges = {
    "Womenswear": (0.15, 1.50),
    "Menswear": (0.20, 1.80),
    "Kidswear": (0.10, 1.20),
    "Footwear": (0.40, 2.00),
    "Accessories": (0.05, 0.80),
    "Home": (0.30, 8.00)
}

product_rows = []

project_start_date = pd.Timestamp(PROJECT_START)
project_end_date = pd.Timestamp(PROJECT_END)

for product_number in range(1, N_PRODUCTS + 1):
    category = rng.choice(categories, p=category_weights)
    brand_name = rng.choice(brand_names)
    size = rng.choice(sizes_by_category[category])
    
    min_weight, max_weight = weight_ranges[category]
    weight_kg = rng.uniform(min_weight, max_weight)
    
    # Product costs are synthetic and expressed in GBP
    unit_cost_gbp = np.clip(
        rng.lognormal(mean=2.5, sigma=0.65),
        3.50,
        180.00
    )
    
    # Most products remain active for the full project period
    active_from = project_start_date + pd.Timedelta(
        days=int(rng.integers(0, 240))
    )
    
    if rng.random() < 0.08:
        active_to = project_end_date - pd.Timedelta(
            days=int(rng.integers(15, 120))
        )
    else:
        active_to = project_end_date
    
    product_rows.append({
        "internal_sku": f"SKU_{product_number:06d}",
        "parent_product_id": f"PARENT_{int(rng.integers(1, 850)):05d}",
        "category": category,
        "brand_name": brand_name,
        "brand_type": rng.choice(
            ["owned", "licensed", "third_party"],
            p=[0.45, 0.15, 0.40]
        ),
        "size": size,
        "colour": rng.choice([
            "Black",
            "White",
            "Navy",
            "Stone",
            "Green",
            "Blue",
            "Red",
            "Natural"
        ]),
        "unit_cost_gbp": round(float(unit_cost_gbp), 2),
        "weight_kg": round(float(weight_kg), 3),
        "active_from": active_from,
        "active_to": active_to
    })

product_ref = pd.DataFrame(product_rows)

print("Products created:", len(product_ref))
print("Columns:")
print(list(product_ref.columns))

display(product_ref.head())

Products created: 3000
Columns:
['internal_sku', 'parent_product_id', 'category', 'brand_name', 'brand_type', 'size', 'colour', 'unit_cost_gbp', 'weight_kg', 'active_from', 'active_to']

,internal_sku,parent_product_id,category,brand_name,brand_type,size,colour,unit_cost_gbp,weight_kg,active_from,active_to
0,SKU_000001,PARENT_00434,Womenswear,Fieldstone,owned,XS,Black,16.07,0.788,2025-03-11,2026-06-30
1,SKU_000002,PARENT_00144,Menswear,Solace,owned,XXL,White,13.76,0.929,2025-01-03,2026-06-30
2,SKU_000003,PARENT_00596,Womenswear,Fieldstone,third_party,XL,Green,4.63,1.013,2025-03-07,2026-06-30
3,SKU_000004,PARENT_00502,Footwear,Kindred Goods,third_party,41,Navy,18.97,1.152,2025-03-25,2026-03-15
4,SKU_000005,PARENT_00818,Menswear,Cedar & Coast,licensed,XL,Red,6.04,1.347,2025-07-16,2026-06-30

In [20]:
# Create fictional mappings between internal products and partner SKUs

mapping_rows = []

partner_listing_probabilities = {
    "CH_A": 0.75,
    "CH_B": 0.65,
    "CH_C": 0.50,
    "CH_D": 0.40
}

for _, product in product_ref.iterrows():
    for partner_id, listing_probability in partner_listing_probabilities.items():
        if rng.random() < listing_probability:
            mapping_rows.append({
                "partner_id": partner_id,
                "internal_sku": product["internal_sku"],
                "partner_sku": f"{partner_id}_{product['internal_sku']}",
                "mapping_method": rng.choice(
                    ["automated", "manual", "partner_confirmed"],
                    p=[0.70, 0.15, 0.15]
                ),
                "mapping_status": "mapped",
                "effective_from": product["active_from"],
                "effective_to": product["active_to"]
            })

partner_product_map = pd.DataFrame(mapping_rows)

print("Partner-product mappings created:", len(partner_product_map))
print("\nMappings by partner:")
display(
    partner_product_map
    .groupby("partner_id")
    .size()
    .reset_index(name="mapping_count")
)

Partner-product mappings created: 6858

Mappings by partner:

  partner_id  mapping_count
0       CH_A           2234
1       CH_B           1947
2       CH_C           1489
3       CH_D           1188

In [21]:
# Save the clean reference tables

partner_ref_path = REFERENCE_DIR / "partner_ref.csv"
country_ref_path = REFERENCE_DIR / "country_ref.csv"
product_ref_path = REFERENCE_DIR / "product_ref.csv"
mapping_path = REFERENCE_DIR / "partner_product_map.csv"

partner_ref.to_csv(partner_ref_path, index=False)
country_ref.to_csv(country_ref_path, index=False)
product_ref.to_csv(product_ref_path, index=False)
partner_product_map.to_csv(mapping_path, index=False)

print("Reference files saved:")

for path in [
    partner_ref_path,
    country_ref_path,
    product_ref_path,
    mapping_path
]:
    print(f" - {path}")

Reference files saved:
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/reference/partner_ref.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/reference/country_ref.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/reference/product_ref.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/reference/partner_product_map.csv

In [22]:
# Basic quality checks for the reference tables

print("Reference-table quality checks")
print("=" * 40)

print("\nPartner IDs unique:")
print(partner_ref["partner_id"].is_unique)

print("\nCountry codes unique:")
print(country_ref["country_code"].is_unique)

print("\nInternal SKUs unique:")
print(product_ref["internal_sku"].is_unique)

print("\nPartner SKU mappings unique:")
print(
    partner_product_map[
        ["partner_id", "partner_sku"]
    ].duplicated().sum()
    == 0
)

print("\nMissing values in product reference:")
display(
    product_ref.isna()
    .sum()
    .to_frame("missing_count")
    .query("missing_count > 0")
)

print("\nReference table shapes:")
print("partner_ref:", partner_ref.shape)
print("country_ref:", country_ref.shape)
print("product_ref:", product_ref.shape)
print("partner_product_map:", partner_product_map.shape)

Reference-table quality checks
========================================

Partner IDs unique:
True

Country codes unique:
True

Internal SKUs unique:
True

Partner SKU mappings unique:
True

Missing values in product reference:

Empty DataFrame
Columns: [missing_count]
Index: []

Reference table shapes:
partner_ref: (4, 7)
country_ref: (10, 5)
product_ref: (3000, 11)
partner_product_map: (6858, 7)

## Generate an unfamiliar partner listing export

This file represents weekly product-listing snapshots received from fictional external selling channels.

The raw file intentionally uses source-style column names and mixed formats. We will not clean it during generation. Cleaning and investigation will happen in later steps.

In [24]:
# Prepare weekly listing snapshots from the fictional partner-product mappings

snapshot_dates = pd.date_range(
    start=PROJECT_START,
    end=PROJECT_END,
    freq="7D"
)

listing_base = (
    partner_product_map
    .merge(
        product_ref[
            [
                "internal_sku",
                "parent_product_id",
                "category",
                "brand_name",
                "unit_cost_gbp",
                "active_from",
                "active_to"
            ]
        ],
        on="internal_sku",
        how="left"
    )
    .merge(
        partner_ref[
            [
                "partner_id",
                "active_from"
            ]
        ].rename(
            columns={"active_from": "partner_active_from"}
        ),
        on="partner_id",
        how="left"
    )
)

listing_snapshots = []

for snapshot_date in snapshot_dates:
    snapshot = listing_base[
        (listing_base["active_from"] <= snapshot_date)
        & (listing_base["active_to"] >= snapshot_date)
        & (listing_base["partner_active_from"] <= snapshot_date)
    ].copy()

    snapshot["snapshot_date"] = snapshot_date
    listing_snapshots.append(snapshot)

listing_snapshots = pd.concat(
    listing_snapshots,
    ignore_index=True
)

print("Weekly snapshot dates:", len(snapshot_dates))
print("Base listing snapshot rows:", len(listing_snapshots))

Weekly snapshot dates: 78
Base listing snapshot rows: 399575

In [25]:
# Create source-style fields for the external listing export

n_rows = len(listing_snapshots)

# Assign a marketplace country to each listing snapshot
country_codes = country_ref["country_code"].to_numpy()

listing_snapshots["marketplace_country_clean"] = rng.choice(
    country_codes,
    size=n_rows,
    p=[0.24, 0.08, 0.16, 0.13, 0.09, 0.05, 0.08, 0.07, 0.06, 0.04]
)

# Synthetic price in GBP before conversion to the displayed source currency
markup_factor = rng.uniform(1.8, 3.4, size=n_rows)

listing_snapshots["synthetic_price_gbp"] = (
    listing_snapshots["unit_cost_gbp"] * markup_factor
).round(2)

# Add seasonality and modest price movement
month_number = listing_snapshots["snapshot_date"].dt.month

seasonal_multiplier = np.where(
    month_number.isin([11, 12]),
    1.08,
    np.where(
        month_number.isin([1, 7]),
        0.94,
        1.00
    )
)

listing_snapshots["synthetic_price_gbp"] = (
    listing_snapshots["synthetic_price_gbp"]
    * seasonal_multiplier
    * rng.uniform(0.97, 1.03, size=n_rows)
).round(2)

# Synthetic stock position
base_stock = rng.gamma(
    shape=2.2,
    scale=5.5,
    size=n_rows
)

listing_snapshots["reported_stock_clean"] = np.maximum(
    np.round(base_stock).astype(int),
    0
)

# Create natural zero-stock situations
zero_stock_mask = rng.random(n_rows) < 0.08
listing_snapshots.loc[
    zero_stock_mask,
    "reported_stock_clean"
] = 0

# Create listing states using stock, lifecycle, and source behaviour
listing_states = np.full(n_rows, "LIVE", dtype=object)

paused_mask = (
    (rng.random(n_rows) < 0.035)
    & (listing_snapshots["reported_stock_clean"] > 0)
)

preorder_mask = (
    (rng.random(n_rows) < 0.018)
    & (listing_snapshots["reported_stock_clean"] == 0)
)

offline_mask = (
    (listing_snapshots["reported_stock_clean"] == 0)
    | (rng.random(n_rows) < 0.025)
)

listing_states[paused_mask] = "PAUSED"
listing_states[preorder_mask] = "PREORDER"
listing_states[offline_mask] = "OFFLINE"

listing_snapshots["listing_state_clean"] = listing_states

print(
    listing_snapshots["listing_state_clean"]
    .value_counts()
)

listing_state_clean
LIVE       345339
OFFLINE     41598
PAUSED      12638
Name: count, dtype: int64

In [26]:
# Repair cell: create all source-style fields in one step

n_rows = len(listing_snapshots)

# Use a separate random generator for this stage
listing_rng = np.random.default_rng(RANDOM_SEED + 16)

def format_mixed_date(value, format_number):
    if format_number == 0:
        return value.strftime("%Y-%m-%d")
    elif format_number == 1:
        return value.strftime("%d/%m/%Y")
    else:
        return value.strftime("%Y-%m-%d %H:%M:%S")


def format_currency(currency_code, format_number):
    aliases = {
        "GBP": ["GBP", "£", "Pound Sterling"],
        "EUR": ["EUR", "€", "Euro"],
        "SEK": ["SEK", "kr", "Swedish Krona"],
        "DKK": ["DKK", "kr", "Danish Krone"]
    }

    return aliases[currency_code][format_number]


country_currency_lookup = (
    country_ref
    .set_index("country_code")["currency_code"]
    .to_dict()
)

# External partner identifier
listing_snapshots["source_partner_code"] = np.where(
    listing_rng.random(n_rows) < 0.035,
    " " + listing_snapshots["partner_id"].astype(str) + " ",
    listing_snapshots["partner_id"].astype(str)
)

# External country labels
listing_snapshots["source_market"] = (
    listing_snapshots["marketplace_country_clean"]
    .map({
        "GB": "UK",
        "IE": "IE",
        "DE": "DE",
        "FR": "FR",
        "NL": "NL",
        "BE": "BE",
        "ES": "ES",
        "IT": "IT",
        "SE": "SWE",
        "DK": "DK"
    })
)

# External product identifier
listing_snapshots["source_item_code"] = (
    listing_snapshots["partner_sku"].astype(str)
)

identifier_whitespace_mask = listing_rng.random(n_rows) < 0.025

listing_snapshots.loc[
    identifier_whitespace_mask,
    "source_item_code"
] = (
    " "
    + listing_snapshots.loc[
        identifier_whitespace_mask,
        "source_item_code"
    ]
    + " "
)

# External currency
listing_snapshots["source_currency_clean"] = (
    listing_snapshots["marketplace_country_clean"]
    .map(country_currency_lookup)
)

# Synthetic exchange rates
synthetic_fx_rates = {
    "GBP": 1.00,
    "EUR": 1.17,
    "SEK": 0.087,
    "DKK": 0.134
}

listing_snapshots["offer_price_clean"] = (
    listing_snapshots["synthetic_price_gbp"]
    / listing_snapshots["source_currency_clean"]
    .map(synthetic_fx_rates)
).round(2)

currency_format_number = listing_rng.integers(
    0,
    3,
    size=n_rows
)

listing_snapshots["source_currency"] = [
    format_currency(
        currency,
        int(format_number)
    )
    for currency, format_number in zip(
        listing_snapshots["source_currency_clean"],
        currency_format_number
    )
]

# Mixed date formats
date_format_number = listing_rng.integers(
    0,
    3,
    size=n_rows
)

listing_snapshots["source_snapshot_date"] = [
    format_mixed_date(
        date_value,
        int(format_number)
    )
    for date_value, format_number in zip(
        listing_snapshots["snapshot_date"],
        date_format_number
    )
]

# Inventory update timestamp
inventory_update_offset_hours = listing_rng.integers(
    0,
    96,
    size=n_rows
)

listing_snapshots["inventory_update_timestamp"] = (
    listing_snapshots["snapshot_date"]
    + pd.to_timedelta(
        inventory_update_offset_hours,
        unit="h"
    )
)

inventory_date_format_number = listing_rng.integers(
    0,
    3,
    size=n_rows
)

listing_snapshots["source_inventory_update"] = [
    format_mixed_date(
        timestamp_value,
        int(format_number)
    )
    for timestamp_value, format_number in zip(
        listing_snapshots["inventory_update_timestamp"],
        inventory_date_format_number
    )
]

# Source listing fields
listing_snapshots["source_listing_state"] = (
    listing_snapshots["listing_state_clean"]
)

listing_snapshots["source_stock"] = (
    listing_snapshots["reported_stock_clean"]
)

listing_snapshots["source_price"] = (
    listing_snapshots["offer_price_clean"]
)

listing_snapshots["source_category"] = (
    listing_snapshots["category"]
)

listing_snapshots["source_title"] = (
    listing_snapshots["brand_name"]
    + " "
    + listing_snapshots["category"]
    + " "
    + listing_snapshots["internal_sku"]
)

listing_snapshots["source_image_url"] = (
    "https://fictional.example/images/"
    + listing_snapshots["source_item_code"].astype(str).str.strip()
    + ".jpg"
)

# Incomplete source attributes
title_missing_mask = listing_rng.random(n_rows) < 0.012
image_missing_mask = listing_rng.random(n_rows) < 0.018
category_missing_mask = listing_rng.random(n_rows) < 0.010

listing_snapshots.loc[
    title_missing_mask,
    "source_title"
] = None

listing_snapshots.loc[
    image_missing_mask,
    "source_image_url"
] = None

listing_snapshots.loc[
    category_missing_mask,
    "source_category"
] = None

# Category formatting variation
category_format_mask = listing_rng.random(n_rows) < 0.035

listing_snapshots.loc[
    category_format_mask,
    "source_category"
] = (
    listing_snapshots.loc[
        category_format_mask,
        "source_category"
    ]
    .astype("string")
    .str.lower()
    .str.strip()
)

# File lineage and ingestion timestamp
listing_snapshots["source_file"] = (
    "partner_listing_"
    + listing_snapshots["partner_id"].astype(str)
    + "_"
    + listing_snapshots["snapshot_date"]
    .dt.strftime("%Y%m%d")
    + ".csv"
)

listing_snapshots["ingested_at"] = (
    listing_snapshots["snapshot_date"]
    + pd.to_timedelta(
        listing_rng.integers(
            1,
            72,
            size=n_rows
        ),
        unit="h"
    )
)

print("Source-style fields created successfully.")
print(f"Current row count: {len(listing_snapshots):,}")

Source-style fields created successfully.
Current row count: 399,575

In [27]:
expected_source_columns = [
    "source_partner_code",
    "source_market",
    "source_item_code",
    "source_snapshot_date",
    "source_listing_state",
    "source_price",
    "source_currency",
    "source_stock",
    "source_title",
    "source_category",
    "source_image_url",
    "source_inventory_update",
    "source_file",
    "ingested_at"
]

missing_source_columns = [
    column
    for column in expected_source_columns
    if column not in listing_snapshots.columns
]

if missing_source_columns:
    print("Still missing:")
    print(missing_source_columns)
else:
    print("All source columns are present.")

All source columns are present.

In [28]:
# Keep only the columns that an analyst would receive from the external source

raw_listing_export = listing_snapshots[
    [
        "source_partner_code",
        "source_market",
        "source_item_code",
        "source_snapshot_date",
        "source_listing_state",
        "source_price",
        "source_currency",
        "source_stock",
        "source_title",
        "source_category",
        "source_image_url",
        "source_inventory_update",
        "source_file",
        "ingested_at"
    ]
].copy()

print("Raw export shape:", raw_listing_export.shape)
display(raw_listing_export.head())

Raw export shape: (399575, 14)

,source_partner_code,source_market,source_item_code,source_snapshot_date,source_listing_state,source_price,source_currency,source_stock,source_title,source_category,source_image_url,source_inventory_update,source_file,ingested_at
0,CH_A,DE,CH_A_SKU_000312,2025-01-01 00:00:00,LIVE,42.60,€,3,Oak & Vale Menswear SKU_000312,Menswear,https://fictional.example/images/CH_A_SKU_0003...,2025-01-02,partner_listing_CH_A_20250101.csv,2025-01-03 17:00:00
1,CH_B,SWE,CH_B_SKU_000312,2025-01-01 00:00:00,LIVE,630.34,kr,15,Oak & Vale Menswear SKU_000312,Menswear,https://fictional.example/images/CH_B_SKU_0003...,04/01/2025,partner_listing_CH_B_20250101.csv,2025-01-03 05:00:00
2,CH_A,SWE,CH_A_SKU_000531,2025-01-01 00:00:00,LIVE,215.06,SEK,2,Oak & Vale Home SKU_000531,Home,https://fictional.example/images/CH_A_SKU_0005...,2025-01-02 23:00:00,partner_listing_CH_A_20250101.csv,2025-01-03 10:00:00
3,CH_B,FR,CH_B_SKU_000531,01/01/2025,LIVE,13.43,€,7,Oak & Vale Home SKU_000531,Home,https://fictional.example/images/CH_B_SKU_0005...,2025-01-02,partner_listing_CH_B_20250101.csv,2025-01-01 19:00:00
4,CH_B,DE,CH_B_SKU_000937,01/01/2025,LIVE,16.31,€,11,Juniper Lane Home SKU_000937,Home,https://fictional.example/images/CH_B_SKU_0009...,04/01/2025,partner_listing_CH_B_20250101.csv,2025-01-03 22:00:00

In [29]:
# Add a small number of repeated export records with new ingestion metadata

retry_sample_size = max(
    1,
    int(len(raw_listing_export) * 0.004)
)

retry_sample = raw_listing_export.sample(
    n=retry_sample_size,
    random_state=RANDOM_SEED
).copy()

retry_sample["source_file"] = (
    retry_sample["source_file"]
    .str.replace(".csv", "_retry.csv", regex=False)
)

retry_sample["ingested_at"] = (
    pd.to_datetime(retry_sample["ingested_at"])
    + pd.to_timedelta(
        rng.integers(1, 18, size=retry_sample_size),
        unit="h"
    )
)

raw_listing_export = pd.concat(
    [
        raw_listing_export,
        retry_sample
    ],
    ignore_index=True
)

raw_listing_export_path = RAW_DIR / "partner_listing_export.csv"

raw_listing_export.to_csv(
    raw_listing_export_path,
    index=False
)

print(f"Raw listing export saved to: {raw_listing_export_path}")
print(f"Final row count: {len(raw_listing_export):,}")
print(f"File size in MB: {raw_listing_export_path.stat().st_size / 1024**2:.2f}")

Raw listing export saved to: /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/raw/partner_listing_export.csv
Final row count: 401,173
File size in MB: 83.61

In [30]:
# Inspect the raw export without cleaning it

print("Raw listing export columns:")
for column in raw_listing_export.columns:
    print(f" - {column}")

print("\nData types:")
display(raw_listing_export.dtypes.to_frame("dtype"))

print("\nMissing values:")
display(
    raw_listing_export.isna()
    .sum()
    .to_frame("missing_count")
    .sort_values("missing_count", ascending=False)
)

print("\nFirst five rows:")
display(raw_listing_export.head())

Raw listing export columns:
 - source_partner_code
 - source_market
 - source_item_code
 - source_snapshot_date
 - source_listing_state
 - source_price
 - source_currency
 - source_stock
 - source_title
 - source_category
 - source_image_url
 - source_inventory_update
 - source_file
 - ingested_at

Data types:

                                  dtype
source_partner_code              object
source_market                    object
source_item_code                 object
source_snapshot_date             object
source_listing_state             object
source_price                    float64
source_currency                  object
source_stock                      int64
source_title                     object
source_category                  object
source_image_url                 object
source_inventory_update          object
source_file                      object
ingested_at              datetime64[ns]

Missing values:

                         missing_count
source_image_url                  7165
source_title                      4726
source_category                   3973
source_partner_code                  0
source_market                        0
source_item_code                     0
source_snapshot_date                 0
source_listing_state                 0
source_price                         0
source_currency                      0
source_stock                         0
source_inventory_update              0
source_file                          0
ingested_at                          0

First five rows:

,source_partner_code,source_market,source_item_code,source_snapshot_date,source_listing_state,source_price,source_currency,source_stock,source_title,source_category,source_image_url,source_inventory_update,source_file,ingested_at
0,CH_A,DE,CH_A_SKU_000312,2025-01-01 00:00:00,LIVE,42.60,€,3,Oak & Vale Menswear SKU_000312,Menswear,https://fictional.example/images/CH_A_SKU_0003...,2025-01-02,partner_listing_CH_A_20250101.csv,2025-01-03 17:00:00
1,CH_B,SWE,CH_B_SKU_000312,2025-01-01 00:00:00,LIVE,630.34,kr,15,Oak & Vale Menswear SKU_000312,Menswear,https://fictional.example/images/CH_B_SKU_0003...,04/01/2025,partner_listing_CH_B_20250101.csv,2025-01-03 05:00:00
2,CH_A,SWE,CH_A_SKU_000531,2025-01-01 00:00:00,LIVE,215.06,SEK,2,Oak & Vale Home SKU_000531,Home,https://fictional.example/images/CH_A_SKU_0005...,2025-01-02 23:00:00,partner_listing_CH_A_20250101.csv,2025-01-03 10:00:00
3,CH_B,FR,CH_B_SKU_000531,01/01/2025,LIVE,13.43,€,7,Oak & Vale Home SKU_000531,Home,https://fictional.example/images/CH_B_SKU_0005...,2025-01-02,partner_listing_CH_B_20250101.csv,2025-01-01 19:00:00
4,CH_B,DE,CH_B_SKU_000937,01/01/2025,LIVE,16.31,€,11,Juniper Lane Home SKU_000937,Home,https://fictional.example/images/CH_B_SKU_0009...,04/01/2025,partner_listing_CH_B_20250101.csv,2025-01-03 22:00:00

## Generate an unfamiliar inventory export

This file represents inventory snapshots received from fictional external partners or fulfilment sources.

The inventory export is intentionally separate from the listing export. Later, we will compare the two sources to investigate stale stock, availability disagreements, and possible mapping issues.

In [32]:
# Create a clean base for the fictional inventory source

inventory_rng = np.random.default_rng(RANDOM_SEED + 40)

inventory_base = (
    listing_snapshots[
        [
            "partner_id",
            "partner_sku",
            "marketplace_country_clean",
            "snapshot_date",
            "reported_stock_clean"
        ]
    ]
    .drop_duplicates(
        subset=[
            "partner_id",
            "partner_sku",
            "marketplace_country_clean",
            "snapshot_date"
        ]
    )
    .copy()
)

inventory_base = inventory_base.reset_index(drop=True)

n_inventory_rows = len(inventory_base)

print("Inventory base rows:", f"{n_inventory_rows:,}")
display(inventory_base.head())

Inventory base rows: 399,575

,partner_id,partner_sku,marketplace_country_clean,snapshot_date,reported_stock_clean
0,CH_A,CH_A_SKU_000312,DE,2025-01-01,3
1,CH_B,CH_B_SKU_000312,SE,2025-01-01,15
2,CH_A,CH_A_SKU_000531,SE,2025-01-01,2
3,CH_B,CH_B_SKU_000531,FR,2025-01-01,7
4,CH_B,CH_B_SKU_000937,DE,2025-01-01,11

In [33]:
# Create synthetic inventory quantities

# Add small source-specific differences to the listing stock values
stock_adjustment = inventory_rng.choice(
    [-3, -2, -1, 0, 0, 0, 1, 2, 3],
    size=n_inventory_rows
)

inventory_base["available_units_clean"] = np.maximum(
    inventory_base["reported_stock_clean"] + stock_adjustment,
    0
)

# Reserved stock is usually a fraction of available stock
reservation_fraction = inventory_rng.uniform(
    0.00,
    0.35,
    size=n_inventory_rows
)

inventory_base["reserved_units_clean"] = np.minimum(
    np.floor(
        inventory_base["available_units_clean"]
        * reservation_fraction
    ).astype(int),
    inventory_base["available_units_clean"]
)

inventory_base["inbound_units_clean"] = inventory_rng.poisson(
    lam=2.5,
    size=n_inventory_rows
)

# Create fulfilment locations
inventory_base["warehouse_clean"] = inventory_rng.choice(
    [
        "WH_NORTH",
        "WH_CENTRAL",
        "WH_SOUTH",
        "WH_EUROPE"
    ],
    size=n_inventory_rows,
    p=[0.25, 0.40, 0.20, 0.15]
)

print("Inventory quantities created.")
display(
    inventory_base[
        [
            "available_units_clean",
            "reserved_units_clean",
            "inbound_units_clean",
            "warehouse_clean"
        ]
    ].describe()
)

Inventory quantities created.

       available_units_clean  reserved_units_clean  inbound_units_clean
count          399575.000000         399575.000000        399575.000000
mean               11.204580              1.530959             2.500602
std                 8.579027              2.023857             1.581372
min                 0.000000              0.000000             0.000000
25%                 5.000000              0.000000             1.000000
50%                10.000000              1.000000             2.000000
75%                16.000000              2.000000             3.000000
max                84.000000             21.000000            12.000000

In [34]:
# Convert clean inventory values into external source formats

def format_inventory_date(value, format_number):
    if format_number == 0:
        return value.strftime("%Y-%m-%d")
    elif format_number == 1:
        return value.strftime("%d/%m/%Y")
    else:
        return value.strftime("%Y-%m-%d %H:%M:%S")


inventory_export = pd.DataFrame()

# Partner identifier with occasional whitespace
inventory_export["partner_code"] = np.where(
    inventory_rng.random(n_inventory_rows) < 0.025,
    " " + inventory_base["partner_id"].astype(str) + " ",
    inventory_base["partner_id"].astype(str)
)

# Partner SKU with occasional whitespace
inventory_export["item_code"] = inventory_base[
    "partner_sku"
].astype(str)

item_whitespace_mask = inventory_rng.random(
    n_inventory_rows
) < 0.022

inventory_export.loc[
    item_whitespace_mask,
    "item_code"
] = (
    " "
    + inventory_export.loc[
        item_whitespace_mask,
        "item_code"
    ]
    + " "
)

# Country labels differ from the country reference table
inventory_export["market"] = (
    inventory_base["marketplace_country_clean"]
    .map({
        "GB": "UK",
        "IE": "IE",
        "DE": "DE",
        "FR": "FR",
        "NL": "NLD",
        "BE": "BE",
        "ES": "ESP",
        "IT": "IT",
        "SE": "SWE",
        "DK": "DK"
    })
)

inventory_export["warehouse"] = inventory_base[
    "warehouse_clean"
]

# Numeric source fields
inventory_export["available_qty"] = inventory_base[
    "available_units_clean"
]

inventory_export["reserved_qty"] = inventory_base[
    "reserved_units_clean"
]

inventory_export["inbound_qty"] = inventory_base[
    "inbound_units_clean"
]

# Inventory update timestamps
inventory_update_hours = inventory_rng.integers(
    2,
    120,
    size=n_inventory_rows
)

inventory_export["inventory_timestamp_clean"] = (
    inventory_base["snapshot_date"]
    + pd.to_timedelta(
        inventory_update_hours,
        unit="h"
    )
)

inventory_date_formats = inventory_rng.integers(
    0,
    3,
    size=n_inventory_rows
)

inventory_export["inventory_timestamp"] = [
    format_inventory_date(
        timestamp_value,
        int(format_number)
    )
    for timestamp_value, format_number in zip(
        inventory_export["inventory_timestamp_clean"],
        inventory_date_formats
    )
]

# File lineage
inventory_export["source_file"] = (
    "inventory_"
    + inventory_export["partner_code"].astype(str).str.strip()
    + "_"
    + inventory_base["snapshot_date"].dt.strftime("%Y%m%d")
    + ".csv"
)

inventory_export["ingested_at"] = (
    inventory_export["inventory_timestamp_clean"]
    + pd.to_timedelta(
        inventory_rng.integers(
            1,
            48,
            size=n_inventory_rows
        ),
        unit="h"
    )
)

print("Source-specific inventory fields created.")
display(inventory_export.head())

Source-specific inventory fields created.

,partner_code,item_code,market,warehouse,available_qty,reserved_qty,inbound_qty,inventory_timestamp_clean,inventory_timestamp,source_file,ingested_at
0,CH_A,CH_A_SKU_000312,DE,WH_CENTRAL,2,0,2,2025-01-04 03:00:00,2025-01-04 03:00:00,inventory_CH_A_20250101.csv,2025-01-06 01:00:00
1,CH_B,CH_B_SKU_000312,SWE,WH_EUROPE,15,0,1,2025-01-04 20:00:00,2025-01-04 20:00:00,inventory_CH_B_20250101.csv,2025-01-05 13:00:00
2,CH_A,CH_A_SKU_000531,SWE,WH_CENTRAL,5,0,4,2025-01-04 05:00:00,2025-01-04 05:00:00,inventory_CH_A_20250101.csv,2025-01-05 09:00:00
3,CH_B,CH_B_SKU_000531,FR,WH_SOUTH,7,1,2,2025-01-03 05:00:00,2025-01-03 05:00:00,inventory_CH_B_20250101.csv,2025-01-04 17:00:00
4,CH_B,CH_B_SKU_000937,DE,WH_CENTRAL,14,1,1,2025-01-03 16:00:00,2025-01-03,inventory_CH_B_20250101.csv,2025-01-04 20:00:00

In [35]:
# Add plausible missingness to the inventory export

available_missing_mask = inventory_rng.random(
    n_inventory_rows
) < 0.006

reserved_missing_mask = inventory_rng.random(
    n_inventory_rows
) < 0.009

warehouse_missing_mask = inventory_rng.random(
    n_inventory_rows
) < 0.004

timestamp_missing_mask = inventory_rng.random(
    n_inventory_rows
) < 0.007

inventory_export.loc[
    available_missing_mask,
    "available_qty"
] = np.nan

inventory_export.loc[
    reserved_missing_mask,
    "reserved_qty"
] = np.nan

inventory_export.loc[
    warehouse_missing_mask,
    "warehouse"
] = None

inventory_export.loc[
    timestamp_missing_mask,
    "inventory_timestamp"
] = None

print("Missing values added to source-style inventory fields.")
display(
    inventory_export.isna()
    .sum()
    .to_frame("missing_count")
    .sort_values("missing_count", ascending=False)
)

Missing values added to source-style inventory fields.

                           missing_count
reserved_qty                        3618
inventory_timestamp                 2778
available_qty                       2397
warehouse                           1505
partner_code                           0
item_code                              0
market                                 0
inbound_qty                            0
inventory_timestamp_clean              0
source_file                            0
ingested_at                            0

In [36]:
# Save the raw inventory export

inventory_export_path = RAW_DIR / "inventory_snapshot_export.csv"

inventory_export.to_csv(
    inventory_export_path,
    index=False
)

print(f"Inventory export saved to: {inventory_export_path}")
print(f"Row count: {len(inventory_export):,}")
print(
    f"File size in MB: "
    f"{inventory_export_path.stat().st_size / 1024**2:.2f}"
)

Inventory export saved to: /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/raw/inventory_snapshot_export.csv
Row count: 399,575
File size in MB: 48.25

In [37]:
# Inspect the raw inventory export without cleaning it

print("Inventory export columns:")
for column in inventory_export.columns:
    print(f" - {column}")

print("\nData types:")
display(inventory_export.dtypes.to_frame("dtype"))

print("\nFirst five rows:")
display(inventory_export.head())

print("\nMissing values:")
display(
    inventory_export.isna()
    .sum()
    .to_frame("missing_count")
    .sort_values("missing_count", ascending=False)
)

Inventory export columns:
 - partner_code
 - item_code
 - market
 - warehouse
 - available_qty
 - reserved_qty
 - inbound_qty
 - inventory_timestamp_clean
 - inventory_timestamp
 - source_file
 - ingested_at

Data types:

                                    dtype
partner_code                       object
item_code                          object
market                             object
warehouse                          object
available_qty                     float64
reserved_qty                      float64
inbound_qty                         int64
inventory_timestamp_clean  datetime64[ns]
inventory_timestamp                object
source_file                        object
ingested_at                datetime64[ns]

First five rows:

,partner_code,item_code,market,warehouse,available_qty,reserved_qty,inbound_qty,inventory_timestamp_clean,inventory_timestamp,source_file,ingested_at
0,CH_A,CH_A_SKU_000312,DE,WH_CENTRAL,2.0,0.0,2,2025-01-04 03:00:00,2025-01-04 03:00:00,inventory_CH_A_20250101.csv,2025-01-06 01:00:00
1,CH_B,CH_B_SKU_000312,SWE,WH_EUROPE,15.0,0.0,1,2025-01-04 20:00:00,2025-01-04 20:00:00,inventory_CH_B_20250101.csv,2025-01-05 13:00:00
2,CH_A,CH_A_SKU_000531,SWE,WH_CENTRAL,5.0,0.0,4,2025-01-04 05:00:00,2025-01-04 05:00:00,inventory_CH_A_20250101.csv,2025-01-05 09:00:00
3,CH_B,CH_B_SKU_000531,FR,WH_SOUTH,7.0,1.0,2,2025-01-03 05:00:00,2025-01-03 05:00:00,inventory_CH_B_20250101.csv,2025-01-04 17:00:00
4,CH_B,CH_B_SKU_000937,DE,WH_CENTRAL,14.0,1.0,1,2025-01-03 16:00:00,2025-01-03,inventory_CH_B_20250101.csv,2025-01-04 20:00:00

Missing values:

                           missing_count
reserved_qty                        3618
inventory_timestamp                 2778
available_qty                       2397
warehouse                           1505
partner_code                           0
item_code                              0
market                                 0
inbound_qty                            0
inventory_timestamp_clean              0
source_file                            0
ingested_at                            0

## Generate an unfamiliar order-header export

This file represents one row per order received from fictional third-party selling channels.

Order-line data will be generated separately so that we can later test whether order headers and lines reconcile correctly.

In [39]:
# Create synthetic order dates with realistic seasonal behaviour

order_rng = np.random.default_rng(RANDOM_SEED + 50)

N_ORDERS = 75000

order_dates = pd.date_range(
    start=PROJECT_START,
    end=PROJECT_END,
    freq="D"
)

# Start with a baseline probability for each date
daily_weights = np.ones(len(order_dates), dtype=float)

# Weekends receive slightly higher online order volume
weekend_mask = order_dates.dayofweek >= 5
daily_weights[weekend_mask] *= 1.15

# November and December receive higher volume
holiday_mask = order_dates.month.isin([11, 12])
daily_weights[holiday_mask] *= 1.35

# January is quieter after the holiday period
january_mask = order_dates.month == 1
daily_weights[january_mask] *= 0.82

daily_probabilities = daily_weights / daily_weights.sum()

sampled_order_dates = order_rng.choice(
    order_dates.to_numpy(),
    size=N_ORDERS,
    p=daily_probabilities
)

sampled_order_dates = pd.to_datetime(
    sampled_order_dates
)

order_header = pd.DataFrame({
    "order_date_clean": sampled_order_dates
})

# Add a random order time during the day
order_header["order_timestamp_clean"] = (
    order_header["order_date_clean"]
    + pd.to_timedelta(
        order_rng.integers(
            0,
            24 * 60 * 60,
            size=N_ORDERS
        ),
        unit="s"
    )
)

print("Orders generated:", len(order_header))
print(
    "Date range:",
    order_header["order_timestamp_clean"].min(),
    "to",
    order_header["order_timestamp_clean"].max()
)

Orders generated: 75000
Date range: 2025-01-01 00:14:23 to 2026-06-30 23:44:24

In [40]:
# Assign fictional partners and countries to each order

partner_choices = []
country_choices = []

partner_country_options = {
    "CH_A": {
        "countries": ["GB", "IE", "DE"],
        "weights": [0.60, 0.20, 0.20]
    },
    "CH_B": {
        "countries": ["DE", "FR", "NL", "BE"],
        "weights": [0.35, 0.30, 0.20, 0.15]
    },
    "CH_C": {
        "countries": ["FR", "ES", "IT", "DE"],
        "weights": [0.25, 0.30, 0.25, 0.20]
    },
    "CH_D": {
        "countries": ["SE", "DK", "DE"],
        "weights": [0.45, 0.30, 0.25]
    }
}

for order_date in order_header["order_timestamp_clean"]:
    if order_date < pd.Timestamp("2025-03-01"):
        eligible_partners = ["CH_A", "CH_B"]
        eligible_weights = [0.62, 0.38]
    elif order_date < pd.Timestamp("2025-06-01"):
        eligible_partners = ["CH_A", "CH_B", "CH_C"]
        eligible_weights = [0.48, 0.32, 0.20]
    else:
        eligible_partners = ["CH_A", "CH_B", "CH_C", "CH_D"]
        eligible_weights = [0.40, 0.28, 0.20, 0.12]

    selected_partner = order_rng.choice(
        eligible_partners,
        p=eligible_weights
    )

    partner_choices.append(selected_partner)

    country_config = partner_country_options[selected_partner]

    selected_country = order_rng.choice(
        country_config["countries"],
        p=country_config["weights"]
    )

    country_choices.append(selected_country)

order_header["partner_id_clean"] = partner_choices
order_header["country_code_clean"] = country_choices

print("Orders by partner:")
display(
    order_header["partner_id_clean"]
    .value_counts()
    .sort_index()
    .to_frame("order_count")
)

print("Orders by country:")
display(
    order_header["country_code_clean"]
    .value_counts()
    .sort_index()
    .to_frame("order_count")
)

Orders by partner:

                  order_count
partner_id_clean
CH_A                    32716
CH_B                    22100
CH_C                    13580
CH_D                     6604

Orders by country:

                    order_count
country_code_clean
BE                         3418
DE                        18597
DK                         1952
ES                         4123
FR                         9951
GB                        19694
IE                         6547
IT                         3337
NL                         4426
SE                         2955

In [41]:
# Create synthetic order amounts and statuses

# Basket values are positively skewed
order_header["item_amount_clean"] = np.clip(
    order_rng.lognormal(
        mean=3.65,
        sigma=0.75,
        size=N_ORDERS
    ),
    8.00,
    950.00
).round(2)

order_header["shipping_amount_clean"] = np.select(
    [
        order_header["item_amount_clean"] >= 100,
        order_header["item_amount_clean"] >= 50
    ],
    [
        0.00,
        3.99
    ],
    default=5.99
).round(2)

order_header["discount_amount_clean"] = np.where(
    order_rng.random(N_ORDERS) < 0.28,
    (
        order_header["item_amount_clean"]
        * order_rng.uniform(0.05, 0.25, size=N_ORDERS)
    ).round(2),
    0.00
)

country_tax_lookup = (
    country_ref
    .set_index("country_code")["synthetic_tax_rate"]
    .to_dict()
)

order_header["synthetic_tax_rate"] = (
    order_header["country_code_clean"]
    .map(country_tax_lookup)
)

order_header["tax_amount_clean"] = (
    (
        order_header["item_amount_clean"]
        - order_header["discount_amount_clean"]
    )
    * order_header["synthetic_tax_rate"]
).round(2)

# More recent orders are more likely to remain pending
age_in_days = (
    pd.Timestamp(PROJECT_END)
    - order_header["order_timestamp_clean"].dt.normalize()
).dt.days

pending_probability = np.where(
    age_in_days < 10,
    0.10,
    0.015
)

random_status_value = order_rng.random(N_ORDERS)

order_status = np.select(
    [
        random_status_value < 0.055,
        random_status_value < 0.095,
        random_status_value < 0.16,
        random_status_value < 0.22,
        random_status_value < 0.22 + pending_probability
    ],
    [
        "cancelled",
        "returned",
        "refunded",
        "shipped",
        "pending"
    ],
    default="delivered"
)

order_header["order_status_clean"] = order_status

print("Order statuses:")
display(
    order_header["order_status_clean"]
    .value_counts()
    .to_frame("order_count")
)

Order statuses:

                    order_count
order_status_clean
delivered                 57311
refunded                   4861
shipped                    4429
cancelled                  4101
returned                   3058
pending                    1240

In [42]:
# Convert order-header values into external source formats

def format_order_timestamp(value, format_number):
    if format_number == 0:
        return value.strftime("%Y-%m-%d %H:%M:%S")
    elif format_number == 1:
        return value.strftime("%d/%m/%Y %H:%M")
    else:
        return value.strftime("%Y-%m-%dT%H:%M:%S")


def order_currency_alias(currency_code, format_number):
    aliases = {
        "GBP": ["GBP", "£", "Pound Sterling"],
        "EUR": ["EUR", "€", "Euro"],
        "SEK": ["SEK", "kr", "Swedish Krona"],
        "DKK": ["DKK", "kr", "Danish Krone"]
    }

    return aliases[currency_code][format_number]


country_currency_lookup = (
    country_ref
    .set_index("country_code")["currency_code"]
    .to_dict()
)

order_header["source_order_id"] = [
    f"ORD-{number:09d}"
    for number in range(1, N_ORDERS + 1)
]

order_header["source_partner_code"] = np.where(
    order_rng.random(N_ORDERS) < 0.025,
    " " + order_header["partner_id_clean"] + " ",
    order_header["partner_id_clean"]
)

order_header["source_market"] = (
    order_header["country_code_clean"]
    .map({
        "GB": "UK",
        "IE": "IE",
        "DE": "DE",
        "FR": "FR",
        "NL": "NLD",
        "BE": "BE",
        "ES": "ESP",
        "IT": "IT",
        "SE": "SWE",
        "DK": "DK"
    })
)

order_header["currency_clean"] = (
    order_header["country_code_clean"]
    .map(country_currency_lookup)
)

currency_format_number = order_rng.integers(
    0,
    3,
    size=N_ORDERS
)

order_header["source_currency"] = [
    order_currency_alias(
        currency,
        int(format_number)
    )
    for currency, format_number in zip(
        order_header["currency_clean"],
        currency_format_number
    )
]

timestamp_format_number = order_rng.integers(
    0,
    3,
    size=N_ORDERS
)

order_header["source_created_at"] = [
    format_order_timestamp(
        timestamp,
        int(format_number)
    )
    for timestamp, format_number in zip(
        order_header["order_timestamp_clean"],
        timestamp_format_number
    )
]

order_header["source_status"] = (
    order_header["order_status_clean"]
    .map({
        "delivered": "COMPLETED",
        "shipped": "DISPATCHED",
        "pending": "OPEN",
        "cancelled": "CANCELLED",
        "returned": "RETURNED",
        "refunded": "REFUNDED"
    })
)

order_header["source_item_amount"] = (
    order_header["item_amount_clean"]
)

order_header["source_shipping_amount"] = (
    order_header["shipping_amount_clean"]
)

order_header["source_discount_amount"] = (
    order_header["discount_amount_clean"]
)

order_header["source_tax_amount"] = (
    order_header["tax_amount_clean"]
)

In [43]:
# Add source metadata and plausible missing values

order_header["source_file"] = (
    "orders_"
    + order_header["partner_id_clean"]
    + "_"
    + order_header["order_timestamp_clean"]
    .dt.strftime("%Y%m%d")
    + ".csv"
)

order_header["ingested_at"] = (
    order_header["order_timestamp_clean"]
    + pd.to_timedelta(
        order_rng.integers(
            1,
            48,
            size=N_ORDERS
        ),
        unit="h"
    )
)

# Some orders have no explicit shipping charge because the partner
# bundles shipping into the item amount.
shipping_missing_mask = order_rng.random(N_ORDERS) < 0.012

order_header.loc[
    shipping_missing_mask,
    "source_shipping_amount"
] = np.nan

# Some source files do not provide tax separately.
tax_missing_mask = order_rng.random(N_ORDERS) < 0.018

order_header.loc[
    tax_missing_mask,
    "source_tax_amount"
] = np.nan

# A small number of source statuses are blank and require investigation.
status_missing_mask = order_rng.random(N_ORDERS) < 0.006

order_header.loc[
    status_missing_mask,
    "source_status"
] = None

print("Source-style order-header fields created.")
display(order_header.head())

Source-style order-header fields created.

,order_date_clean,order_timestamp_clean,partner_id_clean,country_code_clean,item_amount_clean,shipping_amount_clean,discount_amount_clean,synthetic_tax_rate,tax_amount_clean,order_status_clean,...,currency_clean,source_currency,source_created_at,source_status,source_item_amount,source_shipping_amount,source_discount_amount,source_tax_amount,source_file,ingested_at
0,2025-10-06,2025-10-06 19:19:09,CH_A,DE,26.75,5.99,0.00,0.19,5.08,delivered,...,EUR,€,2025-10-06 19:19:09,COMPLETED,26.75,5.99,0.00,5.08,orders_CH_A_20251006.csv,2025-10-07 03:19:09
1,2026-03-02,2026-03-02 09:37:57,CH_A,GB,45.17,5.99,0.00,0.20,9.03,cancelled,...,GBP,£,2026-03-02 09:37:57,CANCELLED,45.17,5.99,0.00,9.03,orders_CH_A_20260302.csv,2026-03-02 23:37:57
2,2025-08-29,2025-08-29 05:46:06,CH_C,IT,64.79,3.99,0.00,0.22,14.25,delivered,...,EUR,€,2025-08-29T05:46:06,COMPLETED,64.79,3.99,0.00,14.25,orders_CH_C_20250829.csv,2025-08-29 23:46:06
3,2025-03-21,2025-03-21 07:05:28,CH_C,ES,85.95,3.99,6.77,0.21,16.63,delivered,...,EUR,€,2025-03-21 07:05:28,COMPLETED,85.95,3.99,6.77,16.63,orders_CH_C_20250321.csv,2025-03-22 15:05:28
4,2025-09-29,2025-09-29 15:38:34,CH_A,DE,40.79,5.99,0.00,0.19,7.75,delivered,...,EUR,Euro,29/09/2025 15:38,COMPLETED,40.79,5.99,0.00,7.75,orders_CH_A_20250929.csv,2025-09-30 09:38:34

In [44]:
# Keep only the external order-header fields

raw_order_header_export = order_header[
    [
        "source_order_id",
        "source_partner_code",
        "source_market",
        "source_created_at",
        "source_currency",
        "source_status",
        "source_item_amount",
        "source_shipping_amount",
        "source_discount_amount",
        "source_tax_amount",
        "source_file",
        "ingested_at"
    ]
].copy()

order_header_path = RAW_DIR / "order_header_export.csv"

raw_order_header_export.to_csv(
    order_header_path,
    index=False
)

print(f"Order-header export saved to: {order_header_path}")
print(f"Row count: {len(raw_order_header_export):,}")
print(
    f"File size in MB: "
    f"{order_header_path.stat().st_size / 1024**2:.2f}"
)

Order-header export saved to: /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/raw/order_header_export.csv
Row count: 75,000
File size in MB: 8.70

In [45]:
# Inspect the raw order-header export without cleaning it

print("Order-header columns:")
for column in raw_order_header_export.columns:
    print(f" - {column}")

print("\nData types:")
display(
    raw_order_header_export.dtypes.to_frame("dtype")
)

print("\nMissing values:")
display(
    raw_order_header_export.isna()
    .sum()
    .to_frame("missing_count")
    .sort_values(
        "missing_count",
        ascending=False
    )
)

print("\nSample rows:")
display(raw_order_header_export.head())

Order-header columns:
 - source_order_id
 - source_partner_code
 - source_market
 - source_created_at
 - source_currency
 - source_status
 - source_item_amount
 - source_shipping_amount
 - source_discount_amount
 - source_tax_amount
 - source_file
 - ingested_at

Data types:

                                 dtype
source_order_id                 object
source_partner_code             object
source_market                   object
source_created_at               object
source_currency                 object
source_status                   object
source_item_amount             float64
source_shipping_amount         float64
source_discount_amount         float64
source_tax_amount              float64
source_file                     object
ingested_at             datetime64[ns]

Missing values:

                        missing_count
source_tax_amount                1328
source_shipping_amount            908
source_status                     443
source_order_id                     0
source_partner_code                 0
source_market                       0
source_created_at                   0
source_currency                     0
source_item_amount                  0
source_discount_amount              0
source_file                         0
ingested_at                         0

Sample rows:

,source_order_id,source_partner_code,source_market,source_created_at,source_currency,source_status,source_item_amount,source_shipping_amount,source_discount_amount,source_tax_amount,source_file,ingested_at
0,ORD-000000001,CH_A,DE,2025-10-06 19:19:09,€,COMPLETED,26.75,5.99,0.00,5.08,orders_CH_A_20251006.csv,2025-10-07 03:19:09
1,ORD-000000002,CH_A,UK,2026-03-02 09:37:57,£,CANCELLED,45.17,5.99,0.00,9.03,orders_CH_A_20260302.csv,2026-03-02 23:37:57
2,ORD-000000003,CH_C,IT,2025-08-29T05:46:06,€,COMPLETED,64.79,3.99,0.00,14.25,orders_CH_C_20250829.csv,2025-08-29 23:46:06
3,ORD-000000004,CH_C,ESP,2025-03-21 07:05:28,€,COMPLETED,85.95,3.99,6.77,16.63,orders_CH_C_20250321.csv,2025-03-22 15:05:28
4,ORD-000000005,CH_A,DE,29/09/2025 15:38,Euro,COMPLETED,40.79,5.99,0.00,7.75,orders_CH_A_20250929.csv,2025-09-30 09:38:34

## Generate an unfamiliar order-line export

This file contains one row per product line within an order.

The source uses partner product codes rather than internal SKUs. We will map these codes back to the internal product catalogue during the cleaning and validation stage.

In [47]:
# Prepare partner product choices for order-line generation

line_rng = np.random.default_rng(RANDOM_SEED + 60)

partner_mapping_for_lines = (
    partner_product_map
    .merge(
        product_ref[
            [
                "internal_sku",
                "unit_cost_gbp",
                "category"
            ]
        ],
        on="internal_sku",
        how="left"
    )
)

partner_sku_lookup = (
    partner_mapping_for_lines
    .groupby("partner_id")["partner_sku"]
    .apply(list)
    .to_dict()
)

partner_sku_to_internal = dict(
    zip(
        partner_mapping_for_lines["partner_sku"],
        partner_mapping_for_lines["internal_sku"]
    )
)

partner_sku_to_cost = dict(
    zip(
        partner_mapping_for_lines["partner_sku"],
        partner_mapping_for_lines["unit_cost_gbp"]
    )
)

print("Partner SKU lists prepared.")

for partner_id, sku_list in partner_sku_lookup.items():
    print(f"{partner_id}: {len(sku_list):,} available partner SKUs")

Partner SKU lists prepared.
CH_A: 2,234 available partner SKUs
CH_B: 1,947 available partner SKUs
CH_C: 1,489 available partner SKUs
CH_D: 1,188 available partner SKUs

In [48]:
# Assign one to four product lines to each order

line_count_per_order = line_rng.choice(
    [1, 2, 3, 4],
    size=len(order_header),
    p=[0.48, 0.34, 0.14, 0.04]
)

order_lines = (
    order_header
    .loc[
        order_header.index.repeat(line_count_per_order)
    ]
    .reset_index(drop=True)
)

order_lines["line_number"] = (
    order_lines
    .groupby("source_order_id")
    .cumcount()
    + 1
)

n_order_lines = len(order_lines)

print("Order headers:", f"{len(order_header):,}")
print("Order lines:", f"{n_order_lines:,}")
print(
    "Average lines per order:",
    round(n_order_lines / len(order_header), 2)
)

Order headers: 75,000
Order lines: 130,522
Average lines per order: 1.74

In [49]:
# Select a partner SKU that is available for each order's partner

selected_partner_skus = [
    line_rng.choice(
        partner_sku_lookup[partner_id]
    )
    for partner_id in order_lines["partner_id_clean"]
]

order_lines["partner_sku_clean"] = selected_partner_skus

order_lines["internal_sku_clean"] = (
    order_lines["partner_sku_clean"]
    .map(partner_sku_to_internal)
)

order_lines["unit_cost_gbp"] = (
    order_lines["partner_sku_clean"]
    .map(partner_sku_to_cost)
)

# Most lines have a quantity of one, with a smaller number of multi-unit lines
order_lines["quantity_clean"] = line_rng.choice(
    [1, 2, 3, 4],
    size=n_order_lines,
    p=[0.70, 0.20, 0.08, 0.02]
)

# Create an initial commercial value for each line
line_markup = line_rng.uniform(
    1.8,
    3.3,
    size=n_order_lines
)

order_lines["initial_line_value"] = (
    order_lines["unit_cost_gbp"]
    * line_markup
    * order_lines["quantity_clean"]
)

In [50]:
# Scale line values so their total approximately matches each order's item amount

order_lines["initial_order_value"] = (
    order_lines
    .groupby("source_order_id")["initial_line_value"]
    .transform("sum")
)

order_lines["line_value_clean"] = (
    order_lines["initial_line_value"]
    / order_lines["initial_order_value"]
    * order_lines["item_amount_clean"]
).round(2)

order_lines["unit_price_clean"] = (
    order_lines["line_value_clean"]
    / order_lines["quantity_clean"]
).round(2)

# Allocate the header discount across the order lines
order_lines["line_discount_clean"] = (
    order_lines["discount_amount_clean"]
    * order_lines["line_value_clean"]
    / order_lines
        .groupby("source_order_id")["line_value_clean"]
        .transform("sum")
).round(2)

print("Line-level commercial values created.")

display(
    order_lines[
        [
            "source_order_id",
            "line_number",
            "partner_sku_clean",
            "internal_sku_clean",
            "quantity_clean",
            "unit_price_clean",
            "line_discount_clean"
        ]
    ].head(10)
)

Line-level commercial values created.

,source_order_id,line_number,partner_sku_clean,internal_sku_clean,quantity_clean,unit_price_clean,line_discount_clean
0,ORD-000000001,1,CH_A_SKU_000409,SKU_000409,1,11.08,0.00
1,ORD-000000001,2,CH_A_SKU_002677,SKU_002677,1,6.99,0.00
2,ORD-000000001,3,CH_A_SKU_001513,SKU_001513,1,8.68,0.00
3,ORD-000000002,1,CH_A_SKU_000682,SKU_000682,1,7.14,0.00
4,ORD-000000002,2,CH_A_SKU_001248,SKU_001248,3,7.27,0.00
5,ORD-000000002,3,CH_A_SKU_000752,SKU_000752,1,16.24,0.00
6,ORD-000000003,1,CH_C_SKU_002166,SKU_002166,2,32.40,0.00
7,ORD-000000004,1,CH_C_SKU_002520,SKU_002520,2,8.10,1.28
8,ORD-000000004,2,CH_C_SKU_002202,SKU_002202,4,17.44,5.49
9,ORD-000000005,1,CH_A_SKU_001887,SKU_001887,2,20.40,0.00

In [51]:
# Convert clean order-line values into source-style fields

raw_order_lines = pd.DataFrame()

raw_order_lines["source_order_id"] = (
    order_lines["source_order_id"]
)

raw_order_lines["source_line_id"] = (
    order_lines["source_order_id"]
    + "-L"
    + order_lines["line_number"]
    .astype(str)
    .str.zfill(2)
)

raw_order_lines["source_partner_code"] = np.where(
    line_rng.random(n_order_lines) < 0.022,
    " " + order_lines["partner_id_clean"] + " ",
    order_lines["partner_id_clean"]
)

raw_order_lines["source_item_code"] = (
    order_lines["partner_sku_clean"]
)

item_code_whitespace_mask = line_rng.random(
    n_order_lines
) < 0.028

raw_order_lines.loc[
    item_code_whitespace_mask,
    "source_item_code"
] = (
    " "
    + raw_order_lines.loc[
        item_code_whitespace_mask,
        "source_item_code"
    ]
    + " "
)

raw_order_lines["source_quantity"] = (
    order_lines["quantity_clean"]
)

raw_order_lines["source_unit_price"] = (
    order_lines["unit_price_clean"]
)

raw_order_lines["source_line_discount"] = (
    order_lines["line_discount_clean"]
)

raw_order_lines["source_currency"] = (
    order_lines["source_currency"]
)

raw_order_lines["source_file"] = (
    "order_lines_"
    + order_lines["partner_id_clean"]
    + "_"
    + order_lines["order_timestamp_clean"]
    .dt.strftime("%Y%m%d")
    + ".csv"
)

raw_order_lines["ingested_at"] = (
    order_lines["ingested_at"]
    + pd.to_timedelta(
        line_rng.integers(
            0,
            12,
            size=n_order_lines
        ),
        unit="h"
    )
)

In [52]:
# Add realistic source variations to the line-level source data

# Convert selected columns to object so they can contain both
# numeric values and source-style text values.
raw_order_lines["source_quantity"] = (
    raw_order_lines["source_quantity"]
    .astype("object")
)

raw_order_lines["source_unit_price"] = (
    raw_order_lines["source_unit_price"]
    .astype("object")
)

raw_order_lines["source_line_discount"] = (
    raw_order_lines["source_line_discount"]
    .astype("object")
)

# A small number of line quantities arrive as text
quantity_as_text_mask = line_rng.random(
    n_order_lines
) < 0.035

raw_order_lines.loc[
    quantity_as_text_mask,
    "source_quantity"
] = (
    raw_order_lines.loc[
        quantity_as_text_mask,
        "source_quantity"
    ]
    .astype(str)
)

# Some discount values are not supplied by the partner
discount_missing_mask = line_rng.random(
    n_order_lines
) < 0.018

raw_order_lines.loc[
    discount_missing_mask,
    "source_line_discount"
] = np.nan

# Some source files use comma decimals in monetary fields
comma_decimal_mask = line_rng.random(
    n_order_lines
) < 0.018

for column in [
    "source_unit_price",
    "source_line_discount"
]:
    affected_values = raw_order_lines.loc[
        comma_decimal_mask,
        column
    ]

    raw_order_lines.loc[
        comma_decimal_mask,
        column
    ] = (
        pd.to_numeric(
            affected_values,
            errors="coerce"
        )
        .round(2)
        .astype("string")
        .str.replace(".", ",", regex=False)
    )

print("Source-style order-line variations created.")

Source-style order-line variations created.

In [53]:
print(raw_order_lines.head(5).to_string())

print("\nColumn data types:")
display(
    raw_order_lines[
        [
            "source_quantity",
            "source_unit_price",
            "source_line_discount"
        ]
    ]
    .dtypes
    .to_frame("dtype")
)

  source_order_id     source_line_id source_partner_code source_item_code source_quantity source_unit_price source_line_discount source_currency                    source_file         ingested_at
0   ORD-000000001  ORD-000000001-L01                CH_A  CH_A_SKU_000409               1             11.08                  0.0               €  order_lines_CH_A_20251006.csv 2025-10-07 08:19:09
1   ORD-000000001  ORD-000000001-L02                CH_A  CH_A_SKU_002677               1              6.99                  0.0               €  order_lines_CH_A_20251006.csv 2025-10-07 11:19:09
2   ORD-000000001  ORD-000000001-L03                CH_A  CH_A_SKU_001513               1              8.68                  0.0               €  order_lines_CH_A_20251006.csv 2025-10-07 10:19:09
3   ORD-000000002  ORD-000000002-L01                CH_A  CH_A_SKU_000682               1              7.14                  0.0               £  order_lines_CH_A_20260302.csv 2026-03-03 03:37:57
4   ORD-000000002  ORD-000000002-L02                CH_A  CH_A_SKU_001248               3              7.27                  0.0               £  order_lines_CH_A_20260302.csv 2026-03-03 08:37:57

Column data types:

                       dtype
source_quantity       object
source_unit_price     object
source_line_discount  object

In [54]:
# Save the raw order-line export

order_line_path = RAW_DIR / "order_line_export.csv"

raw_order_lines.to_csv(
    order_line_path,
    index=False
)

print(f"Order-line export saved to: {order_line_path}")
print(f"Row count: {len(raw_order_lines):,}")
print(
    f"File size in MB: "
    f"{order_line_path.stat().st_size / 1024**2:.2f}"
)

Order-line export saved to: /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/raw/order_line_export.csv
Row count: 130,522
File size in MB: 14.97

In [55]:
# Inspect the raw order-line export without cleaning it

print("Order-line columns:")
for column in raw_order_lines.columns:
    print(f" - {column}")

print("\nData types:")
display(
    raw_order_lines.dtypes.to_frame("dtype")
)

print("\nMissing values:")
display(
    raw_order_lines.isna()
    .sum()
    .to_frame("missing_count")
    .sort_values(
        "missing_count",
        ascending=False
    )
)

print("\nLines per order:")
display(
    raw_order_lines
    .groupby("source_order_id")
    .size()
    .value_counts()
    .sort_index()
    .to_frame("number_of_orders")
)

print("\nSample rows:")
display(raw_order_lines.head())

Order-line columns:
 - source_order_id
 - source_line_id
 - source_partner_code
 - source_item_code
 - source_quantity
 - source_unit_price
 - source_line_discount
 - source_currency
 - source_file
 - ingested_at

Data types:

                               dtype
source_order_id               object
source_line_id                object
source_partner_code           object
source_item_code              object
source_quantity               object
source_unit_price             object
source_line_discount          object
source_currency               object
source_file                   object
ingested_at           datetime64[ns]

Missing values:

                      missing_count
source_line_discount           2309
source_order_id                   0
source_line_id                    0
source_partner_code               0
source_item_code                  0
source_quantity                   0
source_unit_price                 0
source_currency                   0
source_file                       0
ingested_at                       0

Lines per order:

   number_of_orders
1             35997
2             25490
3             10507
4              3006

Sample rows:

,source_order_id,source_line_id,source_partner_code,source_item_code,source_quantity,source_unit_price,source_line_discount,source_currency,source_file,ingested_at
0,ORD-000000001,ORD-000000001-L01,CH_A,CH_A_SKU_000409,1,11.08,0.0,€,order_lines_CH_A_20251006.csv,2025-10-07 08:19:09
1,ORD-000000001,ORD-000000001-L02,CH_A,CH_A_SKU_002677,1,6.99,0.0,€,order_lines_CH_A_20251006.csv,2025-10-07 11:19:09
2,ORD-000000001,ORD-000000001-L03,CH_A,CH_A_SKU_001513,1,8.68,0.0,€,order_lines_CH_A_20251006.csv,2025-10-07 10:19:09
3,ORD-000000002,ORD-000000002-L01,CH_A,CH_A_SKU_000682,1,7.14,0.0,£,order_lines_CH_A_20260302.csv,2026-03-03 03:37:57
4,ORD-000000002,ORD-000000002-L02,CH_A,CH_A_SKU_001248,3,7.27,0.0,£,order_lines_CH_A_20260302.csv,2026-03-03 08:37:57

## Generate an unfamiliar shipment-event export

This file contains operational events for order lines. Each order line can have multiple events, such as accepted, shipped, delivered, or delivery exception.

The event data will later be used to calculate fulfilment and delivery metrics.

In [57]:
# Prepare the base records for shipment-event generation

shipment_rng = np.random.default_rng(RANDOM_SEED + 70)

shipment_base = order_lines[
    [
        "source_order_id",
        "line_number",
        "partner_id_clean",
        "country_code_clean",
        "order_timestamp_clean",
        "order_status_clean"
    ]
].copy()

shipment_base["source_line_id"] = (
    shipment_base["source_order_id"]
    + "-L"
    + shipment_base["line_number"]
    .astype(str)
    .str.zfill(2)
)

shipment_base["order_age_days"] = (
    pd.Timestamp(PROJECT_END)
    - shipment_base["order_timestamp_clean"].dt.normalize()
).dt.days

n_shipment_lines = len(shipment_base)

print("Shipment line base rows:", f"{n_shipment_lines:,}")
display(shipment_base.head())

Shipment line base rows: 130,522

,source_order_id,line_number,partner_id_clean,country_code_clean,order_timestamp_clean,order_status_clean,source_line_id,order_age_days
0,ORD-000000001,1,CH_A,DE,2025-10-06 19:19:09,delivered,ORD-000000001-L01,267
1,ORD-000000001,2,CH_A,DE,2025-10-06 19:19:09,delivered,ORD-000000001-L02,267
2,ORD-000000001,3,CH_A,DE,2025-10-06 19:19:09,delivered,ORD-000000001-L03,267
3,ORD-000000002,1,CH_A,GB,2026-03-02 09:37:57,cancelled,ORD-000000002-L01,120
4,ORD-000000002,2,CH_A,GB,2026-03-02 09:37:57,cancelled,ORD-000000002-L02,120

In [58]:
# Create different shipment event types

shipment_events = []

# Every non-cancelled order line is normally accepted
accepted_lines = shipment_base[
    shipment_base["order_status_clean"] != "cancelled"
].copy()

accepted_lines["event_type_clean"] = "ACCEPTED"
accepted_lines["event_delay_days"] = shipment_rng.integers(
    0,
    2,
    size=len(accepted_lines)
)

shipment_events.append(accepted_lines)

# Most accepted lines are shipped
shippable_lines = accepted_lines[
    (
        shipment_rng.random(len(accepted_lines))
        < 0.90
    )
].copy()

shippable_lines["event_type_clean"] = "SHIPPED"
shippable_lines["event_delay_days"] = shipment_rng.integers(
    1,
    6,
    size=len(shippable_lines)
)

shipment_events.append(shippable_lines)

# Older shipped lines are more likely to have a delivery event
delivered_lines = shippable_lines[
    (
        shippable_lines["order_age_days"] >= 5
    )
    & (
        shipment_rng.random(len(shippable_lines))
        < 0.91
    )
].copy()

delivered_lines["event_type_clean"] = "DELIVERED"
delivered_lines["event_delay_days"] = shipment_rng.integers(
    3,
    12,
    size=len(delivered_lines)
)

shipment_events.append(delivered_lines)

# A smaller number of shipments receive a delivery exception
exception_lines = shippable_lines[
    shipment_rng.random(len(shippable_lines)) < 0.035
].copy()

exception_lines["event_type_clean"] = "DELIVERY_EXCEPTION"
exception_lines["event_delay_days"] = shipment_rng.integers(
    3,
    14,
    size=len(exception_lines)
)

shipment_events.append(exception_lines)

shipment_events = pd.concat(
    shipment_events,
    ignore_index=True
)

print("Shipment events created:", f"{len(shipment_events):,}")
print("\nEvent types:")
display(
    shipment_events["event_type_clean"]
    .value_counts()
    .to_frame("event_count")
)

Shipment events created: 338,904

Event types:

                    event_count
event_type_clean
ACCEPTED                 123523
SHIPPED                  111230
DELIVERED                100273
DELIVERY_EXCEPTION         3878

In [59]:
# Add event timestamps, carriers, fulfilment locations, and tracking references

n_events = len(shipment_events)

shipment_events["event_timestamp_clean"] = (
    shipment_events["order_timestamp_clean"]
    + pd.to_timedelta(
        shipment_events["event_delay_days"],
        unit="D"
    )
    + pd.to_timedelta(
        shipment_rng.integers(
            0,
            24,
            size=n_events
        ),
        unit="h"
    )
)

shipment_events["carrier_clean"] = shipment_rng.choice(
    [
        "CAR_A",
        "CAR_B",
        "CAR_C",
        "CAR_D"
    ],
    size=n_events,
    p=[0.35, 0.30, 0.20, 0.15]
)

shipment_events["fulfilment_country_clean"] = (
    shipment_events["country_code_clean"]
)

fulfilment_override_mask = shipment_rng.random(
    n_events
) < 0.08

shipment_events.loc[
    fulfilment_override_mask,
    "fulfilment_country_clean"
] = shipment_rng.choice(
    [
        "GB",
        "DE",
        "FR",
        "NL"
    ],
    size=fulfilment_override_mask.sum()
)

shipment_events["promised_delivery_date_clean"] = (
    shipment_events["order_timestamp_clean"].dt.normalize()
    + pd.to_timedelta(
        shipment_rng.integers(
            3,
            9,
            size=n_events
        ),
        unit="D"
    )
)

# Create tracking references using pandas string operations

tracking_numbers = pd.Series(
    shipment_rng.integers(
        10000000,
        99999999,
        size=n_events
    ).astype(str),
    index=shipment_events.index,
    dtype="string"
)

tracking_relevant_mask = (
    shipment_events["event_type_clean"]
    .isin(
        [
            "SHIPPED",
            "DELIVERED",
            "DELIVERY_EXCEPTION"
        ]
    )
)

tracking_references = (
    "TRK-"
    + tracking_numbers
)

shipment_events["tracking_reference_clean"] = (
    tracking_references
    .where(
        tracking_relevant_mask,
        pd.NA
    )
)

print("Operational shipment fields created.")
display(shipment_events.head())

Operational shipment fields created.

,source_order_id,line_number,partner_id_clean,country_code_clean,order_timestamp_clean,order_status_clean,source_line_id,order_age_days,event_type_clean,event_delay_days,event_timestamp_clean,carrier_clean,fulfilment_country_clean,promised_delivery_date_clean,tracking_reference_clean
0,ORD-000000001,1,CH_A,DE,2025-10-06 19:19:09,delivered,ORD-000000001-L01,267,ACCEPTED,1,2025-10-08 12:19:09,CAR_C,DE,2025-10-13,<NA>
1,ORD-000000001,2,CH_A,DE,2025-10-06 19:19:09,delivered,ORD-000000001-L02,267,ACCEPTED,0,2025-10-06 23:19:09,CAR_C,DE,2025-10-14,<NA>
2,ORD-000000001,3,CH_A,DE,2025-10-06 19:19:09,delivered,ORD-000000001-L03,267,ACCEPTED,0,2025-10-06 23:19:09,CAR_A,DE,2025-10-11,<NA>
3,ORD-000000003,1,CH_C,IT,2025-08-29 05:46:06,delivered,ORD-000000003-L01,305,ACCEPTED,1,2025-08-30 06:46:06,CAR_B,IT,2025-09-01,<NA>
4,ORD-000000004,1,CH_C,ES,2025-03-21 07:05:28,delivered,ORD-000000004-L01,466,ACCEPTED,0,2025-03-21 22:05:28,CAR_B,ES,2025-03-29,<NA>

In [60]:
# Repair the missing tracking-reference column

tracking_numbers = pd.Series(
    shipment_rng.integers(
        10000000,
        99999999,
        size=len(shipment_events)
    ).astype(str),
    index=shipment_events.index,
    dtype="string"
)

tracking_relevant_mask = (
    shipment_events["event_type_clean"]
    .isin(
        [
            "SHIPPED",
            "DELIVERED",
            "DELIVERY_EXCEPTION"
        ]
    )
)

shipment_events["tracking_reference_clean"] = (
    (
        "TRK-"
        + tracking_numbers
    )
    .where(
        tracking_relevant_mask,
        pd.NA
    )
)

print("Tracking-reference column repaired.")
print(
    "Column exists:",
    "tracking_reference_clean" in shipment_events.columns
)

Tracking-reference column repaired.
Column exists: True

In [61]:
# Convert shipment events into an unfamiliar source format

def format_event_timestamp(value, format_number):
    if format_number == 0:
        return value.strftime("%Y-%m-%d %H:%M:%S")
    elif format_number == 1:
        return value.strftime("%d/%m/%Y %H:%M")
    else:
        return value.strftime("%Y-%m-%dT%H:%M:%S")


shipment_export = pd.DataFrame()

shipment_export["external_order_id"] = (
    shipment_events["source_order_id"]
)

shipment_export["line_ref"] = (
    shipment_events["source_line_id"]
)

shipment_export["event"] = (
    shipment_events["event_type_clean"]
)

shipment_export["carrier"] = (
    shipment_events["carrier_clean"]
)

shipment_export["tracking_number"] = (
    shipment_events["tracking_reference_clean"]
)

shipment_export["fulfilment_market"] = (
    shipment_events["fulfilment_country_clean"]
    .map({
        "GB": "UK",
        "DE": "DE",
        "FR": "FR",
        "NL": "NLD",
        "IE": "IE",
        "ES": "ESP",
        "IT": "IT",
        "SE": "SWE",
        "DK": "DK",
        "BE": "BE"
    })
)

event_date_formats = shipment_rng.integers(
    0,
    3,
    size=n_events
)

shipment_export["event_time"] = [
    format_event_timestamp(
        timestamp,
        int(format_number)
    )
    for timestamp, format_number in zip(
        shipment_events["event_timestamp_clean"],
        event_date_formats
    )
]

promised_date_formats = shipment_rng.integers(
    0,
    3,
    size=n_events
)

shipment_export["promised_date"] = [
    format_event_timestamp(
        timestamp,
        int(format_number)
    )
    for timestamp, format_number in zip(
        shipment_events["promised_delivery_date_clean"],
        promised_date_formats
    )
]

shipment_export["source_file"] = (
    "shipment_events_"
    + shipment_events["event_timestamp_clean"]
    .dt.strftime("%Y%m%d")
    + ".csv"
)

shipment_export["ingested_at"] = (
    shipment_events["event_timestamp_clean"]
    + pd.to_timedelta(
        shipment_rng.integers(
            1,
            36,
            size=n_events
        ),
        unit="h"
    )
)

In [62]:
# Add plausible missing values to shipment events

tracking_missing_mask = shipment_rng.random(
    n_events
) < 0.018

carrier_missing_mask = shipment_rng.random(
    n_events
) < 0.009

promised_date_missing_mask = shipment_rng.random(
    n_events
) < 0.012

shipment_export.loc[
    tracking_missing_mask,
    "tracking_number"
] = None

shipment_export.loc[
    carrier_missing_mask,
    "carrier"
] = None

shipment_export.loc[
    promised_date_missing_mask,
    "promised_date"
] = None

shipment_event_path = RAW_DIR / "shipment_event_export.csv"

shipment_export.to_csv(
    shipment_event_path,
    index=False
)

print(f"Shipment event export saved to: {shipment_event_path}")
print(f"Row count: {len(shipment_export):,}")
print(
    f"File size in MB: "
    f"{shipment_event_path.stat().st_size / 1024**2:.2f}"
)

Shipment event export saved to: /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/raw/shipment_event_export.csv
Row count: 338,904
File size in MB: 47.02

In [63]:
# Inspect the raw shipment-event export

print("Shipment-event columns:")
for column in shipment_export.columns:
    print(f" - {column}")

print("\nEvent counts:")
display(
    shipment_export["event"]
    .value_counts()
    .to_frame("event_count")
)

print("\nMissing values:")
display(
    shipment_export.isna()
    .sum()
    .to_frame("missing_count")
    .sort_values(
        "missing_count",
        ascending=False
    )
)

print("\nSample rows:")
print(shipment_export.head(10).to_string())

Shipment-event columns:
 - external_order_id
 - line_ref
 - event
 - carrier
 - tracking_number
 - fulfilment_market
 - event_time
 - promised_date
 - source_file
 - ingested_at

Event counts:

                    event_count
event
ACCEPTED                 123523
SHIPPED                  111230
DELIVERED                100273
DELIVERY_EXCEPTION         3878

Missing values:

                   missing_count
tracking_number           127385
promised_date               4145
carrier                     3024
external_order_id              0
line_ref                       0
event                          0
fulfilment_market              0
event_time                     0
source_file                    0
ingested_at                    0

Sample rows:
  external_order_id           line_ref     event carrier tracking_number fulfilment_market           event_time        promised_date                   source_file         ingested_at
0     ORD-000000001  ORD-000000001-L01  ACCEPTED   CAR_C            <NA>                DE  2025-10-08 12:19:09  2025-10-13 00:00:00  shipment_events_20251008.csv 2025-10-08 21:19:09
1     ORD-000000001  ORD-000000001-L02  ACCEPTED   CAR_C            <NA>                DE  2025-10-06T23:19:09  2025-10-14 00:00:00  shipment_events_20251006.csv 2025-10-07 11:19:09
2     ORD-000000001  ORD-000000001-L03  ACCEPTED   CAR_A            <NA>                DE  2025-10-06T23:19:09  2025-10-11 00:00:00  shipment_events_20251006.csv 2025-10-08 07:19:09
3     ORD-000000003  ORD-000000003-L01  ACCEPTED   CAR_B            <NA>                IT  2025-08-30T06:46:06  2025-09-01T00:00:00  shipment_events_20250830.csv 2025-08-30 10:46:06
4     ORD-000000004  ORD-000000004-L01  ACCEPTED   CAR_B            <NA>               ESP  2025-03-21T22:05:28     29/03/2025 00:00  shipment_events_20250321.csv 2025-03-22 06:05:28
5     ORD-000000004  ORD-000000004-L02  ACCEPTED   CAR_A            <NA>               ESP     21/03/2025 09:05  2025-03-29 00:00:00  shipment_events_20250321.csv 2025-03-22 17:05:28
6     ORD-000000005  ORD-000000005-L01  ACCEPTED   CAR_D            <NA>                DE  2025-09-30 01:38:34  2025-10-02 00:00:00  shipment_events_20250930.csv 2025-10-01 01:38:34
7     ORD-000000006  ORD-000000006-L01  ACCEPTED   CAR_A            <NA>                DE     13/05/2025 06:57     15/05/2025 00:00  shipment_events_20250513.csv 2025-05-14 06:57:09
8     ORD-000000007  ORD-000000007-L01  ACCEPTED   CAR_C            <NA>               SWE     26/06/2025 19:23  2025-07-04T00:00:00  shipment_events_20250626.csv 2025-06-27 21:23:19
9     ORD-000000007  ORD-000000007-L02  ACCEPTED   CAR_B            <NA>               SWE  2025-06-27 09:23:19     01/07/2025 00:00  shipment_events_20250627.csv 2025-06-27 10:23:19

## Generate an unfamiliar returns export

This file represents return cases received from fictional partner channels.

Returns may be partial, delayed, associated with different reasons, or reflected in settlement data after the original order date.

In [65]:
# Select synthetic return cases from the order-line population

return_rng = np.random.default_rng(RANDOM_SEED + 80)

return_base = order_lines[
    [
        "source_order_id",
        "line_number",
        "partner_id_clean",
        "country_code_clean",
        "order_timestamp_clean",
        "order_status_clean",
        "line_value_clean",
        "source_currency"
    ]
].copy()

return_base["source_line_id"] = (
    return_base["source_order_id"]
    + "-L"
    + return_base["line_number"]
    .astype(str)
    .str.zfill(2)
)

# Lines from returned or refunded orders are more likely to have a return case
forced_return_mask = return_base[
    "order_status_clean"
].isin(
    [
        "returned",
        "refunded"
    ]
)

additional_return_mask = (
    return_base["order_status_clean"]
    .isin(
        [
            "delivered",
            "shipped"
        ]
    )
    & (
        return_rng.random(len(return_base))
        < 0.105
    )
)

return_case_base = return_base[
    forced_return_mask | additional_return_mask
].copy()

return_case_base = return_case_base.reset_index(
    drop=True
)

n_returns = len(return_case_base)

print("Return cases selected:", f"{n_returns:,}")
display(return_case_base.head())

Return cases selected: 24,963

,source_order_id,line_number,partner_id_clean,country_code_clean,order_timestamp_clean,order_status_clean,line_value_clean,source_currency,source_line_id
0,ORD-000000007,1,CH_D,SE,2025-06-26 12:23:19,delivered,64.45,kr,ORD-000000007-L01
1,ORD-000000008,2,CH_A,DE,2025-07-27 00:30:04,delivered,19.44,EUR,ORD-000000008-L02
2,ORD-000000009,2,CH_A,GB,2025-12-06 10:48:33,delivered,4.21,Pound Sterling,ORD-000000009-L02
3,ORD-000000010,1,CH_B,DE,2026-05-22 20:53:17,refunded,17.96,€,ORD-000000010-L01
4,ORD-000000016,1,CH_B,NL,2025-04-08 19:50:42,delivered,135.64,EUR,ORD-000000016-L01

In [66]:
# Create synthetic return details

return_case_base["return_reason_clean"] = return_rng.choice(
    [
        "size_or_fit",
        "changed_mind",
        "not_as_described",
        "damaged_in_transit",
        "quality_issue",
        "wrong_item",
        "late_delivery"
    ],
    size=n_returns,
    p=[
        0.30,
        0.21,
        0.13,
        0.10,
        0.12,
        0.08,
        0.06
    ]
)

return_case_base["return_request_date_clean"] = (
    return_case_base["order_timestamp_clean"]
    + pd.to_timedelta(
        return_rng.integers(
            5,
            45,
            size=n_returns
        ),
        unit="D"
    )
)

return_case_base["return_received_date_clean"] = (
    return_case_base["return_request_date_clean"]
    + pd.to_timedelta(
        return_rng.integers(
            2,
            18,
            size=n_returns
        ),
        unit="D"
    )
)

return_case_base["refund_amount_clean"] = (
    return_case_base["line_value_clean"]
    * return_rng.uniform(
        0.75,
        1.00,
        size=n_returns
    )
).round(2)

return_case_base["return_disposition_clean"] = return_rng.choice(
    [
        "resalable",
        "discounted_resale",
        "damaged",
        "supplier_review",
        "written_off"
    ],
    size=n_returns,
    p=[
        0.57,
        0.18,
        0.10,
        0.08,
        0.07
    ]
)

return_case_base["return_status_clean"] = return_rng.choice(
    [
        "requested",
        "in_transit",
        "received",
        "refunded",
        "rejected"
    ],
    size=n_returns,
    p=[
        0.08,
        0.10,
        0.14,
        0.64,
        0.04
    ]
)

print("Return details created.")
display(
    return_case_base[
        [
            "return_reason_clean",
            "return_disposition_clean",
            "return_status_clean"
        ]
    ]
    .value_counts()
    .head(15)
    .to_frame("case_count")
)

Return details created.

                                                                  case_count
return_reason_clean return_disposition_clean return_status_clean
size_or_fit         resalable                refunded                   2818
changed_mind        resalable                refunded                   1922
not_as_described    resalable                refunded                   1174
quality_issue       resalable                refunded                   1091
damaged_in_transit  resalable                refunded                    970
size_or_fit         discounted_resale        refunded                    853
wrong_item          resalable                refunded                    746
changed_mind        discounted_resale        refunded                    602
size_or_fit         resalable                received                    595
late_delivery       resalable                refunded                    531
size_or_fit         damaged                  refunded                    439
changed_mind        resalable                received                    420
size_or_fit         resalable                in_transit                  413
                    supplier_review          refunded                    378
not_as_described    discounted_resale        refunded                    356

In [67]:
# Convert returns into an unfamiliar source format

def format_return_date(value, format_number):
    if format_number == 0:
        return value.strftime("%Y-%m-%d")
    elif format_number == 1:
        return value.strftime("%d/%m/%Y")
    else:
        return value.strftime("%Y-%m-%d %H:%M:%S")


return_export = pd.DataFrame()

return_export["return_id"] = [
    f"RET-{number:09d}"
    for number in range(1, n_returns + 1)
]

return_export["external_order_id"] = (
    return_case_base["source_order_id"]
)

return_export["line_ref"] = (
    return_case_base["source_line_id"]
)

return_export["partner_code"] = np.where(
    return_rng.random(n_returns) < 0.022,
    " " + return_case_base["partner_id_clean"] + " ",
    return_case_base["partner_id_clean"]
)

return_export["market"] = (
    return_case_base["country_code_clean"]
    .map({
        "GB": "UK",
        "IE": "IE",
        "DE": "DE",
        "FR": "FR",
        "NL": "NLD",
        "BE": "BE",
        "ES": "ESP",
        "IT": "IT",
        "SE": "SWE",
        "DK": "DK"
    })
)

return_export["reason"] = (
    return_case_base["return_reason_clean"]
)

return_export["status"] = (
    return_case_base["return_status_clean"]
)

return_export["disposition"] = (
    return_case_base["return_disposition_clean"]
)

request_date_formats = return_rng.integers(
    0,
    3,
    size=n_returns
)

return_export["requested_at"] = [
    format_return_date(
        return_date,
        int(format_number)
    )
    for return_date, format_number in zip(
        return_case_base["return_request_date_clean"],
        request_date_formats
    )
]

received_date_formats = return_rng.integers(
    0,
    3,
    size=n_returns
)

return_export["received_at"] = [
    format_return_date(
        return_date,
        int(format_number)
    )
    for return_date, format_number in zip(
        return_case_base["return_received_date_clean"],
        received_date_formats
    )
]

return_export["refund_amount"] = (
    return_case_base["refund_amount_clean"]
)

return_export["currency"] = (
    return_case_base["source_currency"]
)

return_export["source_file"] = (
    "returns_"
    + return_case_base["partner_id_clean"]
    + "_"
    + return_case_base["return_request_date_clean"]
    .dt.strftime("%Y%m%d")
    + ".csv"
)

return_export["ingested_at"] = (
    return_case_base["return_received_date_clean"]
    + pd.to_timedelta(
        return_rng.integers(
            1,
            72,
            size=n_returns
        ),
        unit="h"
    )
)

In [68]:
# Add incomplete source data to the return export

reason_missing_mask = return_rng.random(
    n_returns
) < 0.018

received_date_missing_mask = return_rng.random(
    n_returns
) < 0.012

refund_missing_mask = return_rng.random(
    n_returns
) < 0.009

return_export.loc[
    reason_missing_mask,
    "reason"
] = None

return_export.loc[
    received_date_missing_mask,
    "received_at"
] = None

return_export.loc[
    refund_missing_mask,
    "refund_amount"
] = np.nan

print("Return-source variations created.")
display(
    return_export.isna()
    .sum()
    .to_frame("missing_count")
    .sort_values(
        "missing_count",
        ascending=False
    )
)

Return-source variations created.

                   missing_count
reason                       404
received_at                  285
refund_amount                244
return_id                      0
external_order_id              0
line_ref                       0
partner_code                   0
market                         0
status                         0
disposition                    0
requested_at                   0
currency                       0
source_file                    0
ingested_at                    0

In [69]:
# Save the raw returns export

return_path = RAW_DIR / "return_case_export.csv"

return_export.to_csv(
    return_path,
    index=False
)

print(f"Return export saved to: {return_path}")
print(f"Row count: {len(return_export):,}")
print(
    f"File size in MB: "
    f"{return_path.stat().st_size / 1024**2:.2f}"
)

print("\nSample rows:")
print(return_export.head(10).to_string())

Return export saved to: /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/raw/return_case_export.csv
Row count: 24,963
File size in MB: 4.13

Sample rows:
       return_id external_order_id           line_ref partner_code market              reason      status        disposition         requested_at          received_at  refund_amount        currency                source_file         ingested_at
0  RET-000000001     ORD-000000007  ORD-000000007-L01         CH_D    SWE         size_or_fit    refunded          resalable           2025-07-02           08/07/2025          51.97              kr  returns_CH_D_20250702.csv 2025-07-10 08:23:19
1  RET-000000002     ORD-000000008  ORD-000000008-L02         CH_A     DE         size_or_fit    rejected    supplier_review           15/08/2025           2025-08-17          17.37             EUR  returns_CH_A_20250815.csv 2025-08-19 19:30:04
2  RET-000000003     ORD-000000009  ORD-000000009-L02         CH_A     UK  damaged_in_transit  in_transit          resalable           2026-01-02           12/01/2026           3.53  Pound Sterling  returns_CH_A_20260102.csv 2026-01-14 15:48:33
3  RET-000000004     ORD-000000010  ORD-000000010-L01         CH_B     DE          wrong_item    refunded  discounted_resale           11/06/2026  2026-06-28 20:53:17          17.60               €  returns_CH_B_20260611.csv 2026-06-30 11:53:17
4  RET-000000005     ORD-000000016  ORD-000000016-L01         CH_B    NLD        changed_mind    refunded          resalable           17/04/2025           25/04/2025         134.46             EUR  returns_CH_B_20250417.csv 2025-04-27 22:50:42
5  RET-000000006     ORD-000000018  ORD-000000018-L01         CH_C     DE         size_or_fit    refunded          resalable  2025-10-05 18:53:05           2025-10-18           7.10            Euro  returns_CH_C_20251005.csv 2025-10-19 18:53:05
6  RET-000000007     ORD-000000020  ORD-000000020-L01         CH_D     DE        changed_mind   requested  discounted_resale           28/04/2026  2026-05-10 12:21:50         105.47            Euro  returns_CH_D_20260428.csv 2026-05-10 13:21:50
7  RET-000000008     ORD-000000028  ORD-000000028-L02         CH_C     FR       quality_issue    rejected          resalable           2025-08-04  2025-08-14 03:00:51           5.24             EUR  returns_CH_C_20250804.csv 2025-08-16 22:00:51
8  RET-000000009     ORD-000000031  ORD-000000031-L04         CH_C    ESP         size_or_fit   requested          resalable  2025-07-28 08:45:21           2025-08-14          22.11            Euro  returns_CH_C_20250728.csv 2025-08-16 12:45:21
9  RET-000000010     ORD-000000037  ORD-000000037-L02         CH_B     FR         size_or_fit    refunded    supplier_review  2025-10-24 19:14:41           2025-10-29          36.71            Euro  returns_CH_B_20251024.csv 2025-11-01 07:14:41

## Generate settlement and payout exports

Settlement data represents financial lines reported by fictional partner channels.

The source may report sales, fees, refunds, and adjustments separately. Some settlement lines may be aggregated or lack a direct order reference.

In [308]:
from pathlib import Path

PROJECT_ROOT = Path(
    "/Users/tanayajadhav/Desktop/meridian_partner_commerce_health"
)

RAW_DIR = PROJECT_ROOT / "data" / "raw"
RAW_DIR.mkdir(parents=True, exist_ok=True)

print("RAW_DIR is now:")
print(RAW_DIR)

RAW_DIR is now:
/Users/tanayajadhav/Desktop/meridian_partner_commerce_health/data/raw

In [310]:
# Prepare synthetic settlement sales lines

settlement_rng = np.random.default_rng(RANDOM_SEED + 90)

partner_fee_rates = {
    "CH_A": 0.14,
    "CH_B": 0.16,
    "CH_C": 0.12,
    "CH_D": 0.18
}

sale_orders = order_header[
    order_header["order_status_clean"] != "cancelled"
].copy()

sale_orders = sale_orders.reset_index(drop=True)

sale_lines = pd.DataFrame(index=sale_orders.index)

sale_lines["settlement_line_type_clean"] = "SALE"

sale_lines["external_order_id_clean"] = (
    sale_orders["source_order_id"]
)

sale_lines["partner_id_clean"] = (
    sale_orders["partner_id_clean"]
)

sale_lines["currency_clean"] = (
    sale_orders["currency_clean"]
)

sale_lines["transaction_date_clean"] = (
    sale_orders["order_timestamp_clean"]
    + pd.to_timedelta(
        settlement_rng.integers(
            0,
            3,
            size=len(sale_orders)
        ),
        unit="D"
    )
)

sale_lines["payout_date_clean"] = (
    sale_lines["transaction_date_clean"]
    + pd.to_timedelta(
        settlement_rng.integers(
            7,
            22,
            size=len(sale_orders)
        ),
        unit="D"
    )
)

sale_lines["gross_amount_clean"] = (
    sale_orders["item_amount_clean"]
    - sale_orders["discount_amount_clean"]
    + sale_orders["shipping_amount_clean"]
).round(2)

sale_lines["platform_fee_clean"] = (
    sale_lines["gross_amount_clean"]
    * sale_lines["partner_id_clean"]
    .map(partner_fee_rates)
).round(2)

sale_lines["payment_fee_clean"] = (
    sale_lines["gross_amount_clean"]
    * settlement_rng.uniform(
        0.018,
        0.032,
        size=len(sale_orders)
    )
).round(2)

sale_lines["tax_withheld_clean"] = (
    sale_orders["tax_amount_clean"]
).round(2)

sale_lines["refund_adjustment_clean"] = 0.00
sale_lines["manual_adjustment_clean"] = 0.00

sale_lines["net_amount_clean"] = (
    sale_lines["gross_amount_clean"]
    - sale_lines["platform_fee_clean"]
    - sale_lines["payment_fee_clean"]
    - sale_lines["tax_withheld_clean"]
).round(2)

print("Sale settlement lines:", f"{len(sale_lines):,}")
display(sale_lines.head())

Sale settlement lines: 70,899

,settlement_line_type_clean,external_order_id_clean,partner_id_clean,currency_clean,transaction_date_clean,payout_date_clean,gross_amount_clean,platform_fee_clean,payment_fee_clean,tax_withheld_clean,refund_adjustment_clean,manual_adjustment_clean,net_amount_clean
0,SALE,ORD-000000001,CH_A,EUR,2025-10-08 19:19:09,2025-10-29 19:19:09,32.74,4.58,0.62,5.08,0.0,0.0,22.46
1,SALE,ORD-000000003,CH_C,EUR,2025-08-29 05:46:06,2025-09-09 05:46:06,68.78,8.25,1.78,14.25,0.0,0.0,44.50
2,SALE,ORD-000000004,CH_C,EUR,2025-03-22 07:05:28,2025-04-11 07:05:28,83.17,9.98,2.21,16.63,0.0,0.0,54.35
3,SALE,ORD-000000005,CH_A,EUR,2025-09-30 15:38:34,2025-10-17 15:38:34,46.78,6.55,1.11,7.75,0.0,0.0,31.37
4,SALE,ORD-000000006,CH_C,EUR,2025-05-14 04:57:09,2025-05-23 04:57:09,115.80,13.90,3.32,22.00,0.0,0.0,76.58

In [312]:
# Create refund settlement lines from the return cases

refund_lines = pd.DataFrame(index=return_case_base.index)

refund_lines["settlement_line_type_clean"] = "REFUND"

refund_lines["external_order_id_clean"] = (
    return_case_base["source_order_id"]
)

refund_lines["partner_id_clean"] = (
    return_case_base["partner_id_clean"]
)

refund_lines["currency_clean"] = (
    return_case_base["source_currency"]
    .map({
        "GBP": "GBP",
        "£": "GBP",
        "Pound Sterling": "GBP",
        "EUR": "EUR",
        "€": "EUR",
        "Euro": "EUR",
        "SEK": "SEK",
        "kr": "SEK"
    })
    .fillna("GBP")
)

refund_lines["transaction_date_clean"] = (
    return_case_base["return_received_date_clean"]
)

refund_lines["payout_date_clean"] = (
    refund_lines["transaction_date_clean"]
    + pd.to_timedelta(
        settlement_rng.integers(
            5,
            20,
            size=len(refund_lines)
        ),
        unit="D"
    )
)

refund_lines["gross_amount_clean"] = 0.00
refund_lines["platform_fee_clean"] = 0.00
refund_lines["payment_fee_clean"] = 0.00
refund_lines["tax_withheld_clean"] = 0.00

refund_lines["refund_adjustment_clean"] = (
    -return_case_base["refund_amount_clean"]
).round(2)

refund_lines["manual_adjustment_clean"] = 0.00

refund_lines["net_amount_clean"] = (
    refund_lines["refund_adjustment_clean"]
)

# Create a small number of manual adjustments
adjustment_source = sale_orders.sample(
    n=max(1, int(len(sale_orders) * 0.012)),
    random_state=RANDOM_SEED
).copy()

adjustment_lines = pd.DataFrame(index=adjustment_source.index)

adjustment_lines["settlement_line_type_clean"] = "ADJUSTMENT"

adjustment_lines["external_order_id_clean"] = (
    adjustment_source["source_order_id"]
)

unallocated_adjustment_mask = (
    settlement_rng.random(len(adjustment_source))
    < 0.30
)

adjustment_lines.loc[
    unallocated_adjustment_mask,
    "external_order_id_clean"
] = None

adjustment_lines["partner_id_clean"] = (
    adjustment_source["partner_id_clean"]
)

adjustment_lines["currency_clean"] = (
    adjustment_source["currency_clean"]
)

adjustment_lines["transaction_date_clean"] = (
    adjustment_source["order_timestamp_clean"]
    + pd.to_timedelta(
        settlement_rng.integers(
            3,
            15,
            size=len(adjustment_source)
        ),
        unit="D"
    )
)

adjustment_lines["payout_date_clean"] = (
    adjustment_lines["transaction_date_clean"]
    + pd.to_timedelta(
        settlement_rng.integers(
            7,
            25,
            size=len(adjustment_source)
        ),
        unit="D"
    )
)

adjustment_amounts = (
    settlement_rng.normal(
        loc=0,
        scale=12,
        size=len(adjustment_source)
    )
    .round(2)
)

adjustment_lines["gross_amount_clean"] = 0.00
adjustment_lines["platform_fee_clean"] = 0.00
adjustment_lines["payment_fee_clean"] = 0.00
adjustment_lines["tax_withheld_clean"] = 0.00
adjustment_lines["refund_adjustment_clean"] = 0.00
adjustment_lines["manual_adjustment_clean"] = adjustment_amounts
adjustment_lines["net_amount_clean"] = adjustment_amounts

print("Refund lines:", f"{len(refund_lines):,}")
print("Adjustment lines:", f"{len(adjustment_lines):,}")

Refund lines: 24,963
Adjustment lines: 850

In [314]:
# Combine all settlement line types

settlement_clean = pd.concat(
    [
        sale_lines,
        refund_lines,
        adjustment_lines
    ],
    ignore_index=True
)

settlement_clean["settlement_line_id"] = [
    f"SET-{number:09d}"
    for number in range(
        1,
        len(settlement_clean) + 1
    )
]

print("Total settlement lines:", f"{len(settlement_clean):,}")

display(
    settlement_clean[
        "settlement_line_type_clean"
    ]
    .value_counts()
    .to_frame("line_count")
)

Total settlement lines: 96,712

                            line_count
settlement_line_type_clean
SALE                             70899
REFUND                           24963
ADJUSTMENT                         850

In [316]:
# Convert settlement lines into an unfamiliar source format

def format_settlement_date(value, format_number):
    if format_number == 0:
        return value.strftime("%Y-%m-%d")
    elif format_number == 1:
        return value.strftime("%d/%m/%Y")
    else:
        return value.strftime("%Y-%m-%d %H:%M:%S")


def settlement_currency_alias(currency_code, format_number):
    aliases = {
        "GBP": ["GBP", "£", "Pound Sterling"],
        "EUR": ["EUR", "€", "Euro"],
        "SEK": ["SEK", "kr", "Swedish Krona"],
        "DKK": ["DKK", "kr", "Danish Krone"]
    }

    return aliases[currency_code][format_number]


n_settlement_lines = len(settlement_clean)

settlement_export = pd.DataFrame()

settlement_export["statement_line_id"] = (
    settlement_clean["settlement_line_id"]
)

settlement_export["order_reference"] = (
    settlement_clean["external_order_id_clean"]
)

settlement_export["partner_code"] = np.where(
    settlement_rng.random(n_settlement_lines) < 0.025,
    " " + settlement_clean["partner_id_clean"] + " ",
    settlement_clean["partner_id_clean"]
)

settlement_export["line_type"] = (
    settlement_clean["settlement_line_type_clean"]
)

transaction_date_formats = settlement_rng.integers(
    0,
    3,
    size=n_settlement_lines
)

settlement_export["transaction_date"] = [
    format_settlement_date(
        date_value,
        int(format_number)
    )
    for date_value, format_number in zip(
        settlement_clean["transaction_date_clean"],
        transaction_date_formats
    )
]

payout_date_formats = settlement_rng.integers(
    0,
    3,
    size=n_settlement_lines
)

settlement_export["payout_date"] = [
    format_settlement_date(
        date_value,
        int(format_number)
    )
    for date_value, format_number in zip(
        settlement_clean["payout_date_clean"],
        payout_date_formats
    )
]

currency_formats = settlement_rng.integers(
    0,
    3,
    size=n_settlement_lines
)

settlement_export["currency"] = [
    settlement_currency_alias(
        currency,
        int(format_number)
    )
    for currency, format_number in zip(
        settlement_clean["currency_clean"],
        currency_formats
    )
]

settlement_export["gross_amount"] = (
    settlement_clean["gross_amount_clean"]
)

settlement_export["platform_fee"] = (
    -settlement_clean["platform_fee_clean"]
)

settlement_export["payment_fee"] = (
    -settlement_clean["payment_fee_clean"]
)

settlement_export["tax_withheld"] = (
    -settlement_clean["tax_withheld_clean"]
)

settlement_export["refund_adjustment"] = (
    settlement_clean["refund_adjustment_clean"]
)

settlement_export["manual_adjustment"] = (
    settlement_clean["manual_adjustment_clean"]
)

settlement_export["net_amount"] = (
    settlement_clean["net_amount_clean"]
)

settlement_export["source_file"] = (
    "settlement_"
    + settlement_clean["partner_id_clean"]
    + "_"
    + settlement_clean["payout_date_clean"]
    .dt.strftime("%Y%m%d")
    + ".csv"
)

settlement_export["ingested_at"] = (
    settlement_clean["payout_date_clean"]
    + pd.to_timedelta(
        settlement_rng.integers(
            1,
            72,
            size=n_settlement_lines
        ),
        unit="h"
    )
)

print("Source-style settlement fields created.")
display(settlement_export.head())

Source-style settlement fields created.

,statement_line_id,order_reference,partner_code,line_type,transaction_date,payout_date,currency,gross_amount,platform_fee,payment_fee,tax_withheld,refund_adjustment,manual_adjustment,net_amount,source_file,ingested_at
0,SET-000000001,ORD-000000001,CH_A,SALE,2025-10-08,2025-10-29 19:19:09,€,32.74,-4.58,-0.62,-5.08,0.0,0.0,22.46,settlement_CH_A_20251029.csv,2025-10-30 01:19:09
1,SET-000000002,ORD-000000003,CH_C,SALE,29/08/2025,2025-09-09 05:46:06,EUR,68.78,-8.25,-1.78,-14.25,0.0,0.0,44.50,settlement_CH_C_20250909.csv,2025-09-12 04:46:06
2,SET-000000003,ORD-000000004,CH_C,SALE,2025-03-22 07:05:28,2025-04-11,Euro,83.17,-9.98,-2.21,-16.63,0.0,0.0,54.35,settlement_CH_C_20250411.csv,2025-04-13 10:05:28
3,SET-000000004,ORD-000000005,CH_A,SALE,2025-09-30,17/10/2025,EUR,46.78,-6.55,-1.11,-7.75,0.0,0.0,31.37,settlement_CH_A_20251017.csv,2025-10-18 18:38:34
4,SET-000000005,ORD-000000006,CH_C,SALE,14/05/2025,2025-05-23,Euro,115.80,-13.90,-3.32,-22.00,0.0,0.0,76.58,settlement_CH_C_20250523.csv,2025-05-26 03:57:09

In [318]:
# Add realistic settlement-source variations

# Allow monetary columns to contain both numeric and text formats
for column in [
    "gross_amount",
    "platform_fee",
    "payment_fee",
    "tax_withheld",
    "refund_adjustment",
    "manual_adjustment",
    "net_amount"
]:
    settlement_export[column] = (
        settlement_export[column]
        .astype("object")
    )

comma_decimal_mask = settlement_rng.random(
    n_settlement_lines
) < 0.018

for column in [
    "gross_amount",
    "platform_fee",
    "payment_fee",
    "tax_withheld",
    "refund_adjustment",
    "manual_adjustment",
    "net_amount"
]:
    affected_values = settlement_export.loc[
        comma_decimal_mask,
        column
    ]

    settlement_export.loc[
        comma_decimal_mask,
        column
    ] = (
        pd.to_numeric(
            affected_values,
            errors="coerce"
        )
        .round(2)
        .astype("string")
        .str.replace(".", ",", regex=False)
    )

# A small number of settlement lines have missing order references
# because they are aggregated or adjustment lines.
missing_reference_mask = settlement_rng.random(
    n_settlement_lines
) < 0.012

settlement_export.loc[
    missing_reference_mask,
    "order_reference"
] = None

settlement_path = RAW_DIR / "settlement_line_export.csv"

settlement_export.to_csv(
    settlement_path,
    index=False
)

print(f"Settlement export saved to: {settlement_path}")
print(f"Row count: {len(settlement_export):,}")
print(
    f"File size in MB: "
    f"{settlement_path.stat().st_size / 1024**2:.2f}"
)

Settlement export saved to: /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/data/raw/settlement_line_export.csv
Row count: 96,712
File size in MB: 14.64

In [76]:
# Create payout batches from settlement lines

settlement_clean["payout_week"] = (
    settlement_clean["payout_date_clean"]
    .dt.to_period("W-SUN")
    .dt.start_time
)

payout_batch_clean = (
    settlement_clean
    .groupby(
        [
            "partner_id_clean",
            "currency_clean",
            "payout_week"
        ],
        as_index=False
    )
    .agg(
        payout_amount_clean=(
            "net_amount_clean",
            "sum"
        ),
        settlement_line_count=(
            "settlement_line_id",
            "count"
        )
    )
)

payout_batch_clean["payout_amount_clean"] = (
    payout_batch_clean["payout_amount_clean"]
    .round(2)
)

payout_batch_clean["payout_id"] = [
    f"PAY-{number:07d}"
    for number in range(
        1,
        len(payout_batch_clean) + 1
    )
]

payout_batch_clean["payout_date_clean"] = (
    payout_batch_clean["payout_week"]
    + pd.to_timedelta(
        settlement_rng.integers(
            2,
            8,
            size=len(payout_batch_clean)
        ),
        unit="D"
    )
)

print("Payout batches created:", f"{len(payout_batch_clean):,}")
display(payout_batch_clean.head())

Payout batches created: 595

,partner_id_clean,currency_clean,payout_week,payout_amount_clean,settlement_line_count,payout_id,payout_date_clean
0,CH_A,EUR,2025-01-06,912.24,25,PAY-0000001,2025-01-10
1,CH_A,EUR,2025-01-13,2277.27,75,PAY-0000002,2025-01-20
2,CH_A,EUR,2025-01-20,5201.32,164,PAY-0000003,2025-01-25
3,CH_A,EUR,2025-01-27,5758.24,179,PAY-0000004,2025-01-30
4,CH_A,EUR,2025-02-03,5907.88,207,PAY-0000005,2025-02-06

In [77]:
# Convert and save payout batches

payout_export = pd.DataFrame()

payout_export["payout_id"] = (
    payout_batch_clean["payout_id"]
)

payout_export["partner_code"] = np.where(
    settlement_rng.random(len(payout_batch_clean)) < 0.025,
    " " + payout_batch_clean["partner_id_clean"] + " ",
    payout_batch_clean["partner_id_clean"]
)

payout_export["currency"] = [
    settlement_currency_alias(
        currency,
        int(format_number)
    )
    for currency, format_number in zip(
        payout_batch_clean["currency_clean"],
        settlement_rng.integers(
            0,
            3,
            size=len(payout_batch_clean)
        )
    )
]

payout_date_formats = settlement_rng.integers(
    0,
    3,
    size=len(payout_batch_clean)
)

payout_export["payout_date"] = [
    format_settlement_date(
        date_value,
        int(format_number)
    )
    for date_value, format_number in zip(
        payout_batch_clean["payout_date_clean"],
        payout_date_formats
    )
]

payout_export["payout_amount"] = (
    payout_batch_clean["payout_amount_clean"]
)

payout_export["statement_line_count"] = (
    payout_batch_clean["settlement_line_count"]
)

payout_export["source_file"] = (
    "payout_batches_"
    + payout_batch_clean["payout_date_clean"]
    .dt.strftime("%Y%m%d")
    + ".csv"
)

payout_export["ingested_at"] = (
    payout_batch_clean["payout_date_clean"]
    + pd.to_timedelta(
        settlement_rng.integers(
            1,
            48,
            size=len(payout_batch_clean)
        ),
        unit="h"
    )
)

payout_path = RAW_DIR / "payout_batch_export.csv"

payout_export.to_csv(
    payout_path,
    index=False
)

print(f"Payout export saved to: {payout_path}")
print(f"Row count: {len(payout_export):,}")

Payout export saved to: /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/raw/payout_batch_export.csv
Row count: 595

In [320]:
# Inspect the settlement and payout exports

print("Settlement line types:")
display(
    settlement_export["line_type"]
    .value_counts()
    .to_frame("line_count")
)

print("\nSettlement missing values:")
display(
    settlement_export.isna()
    .sum()
    .to_frame("missing_count")
    .sort_values(
        "missing_count",
        ascending=False
    )
)

print("\nSettlement sample:")
print(settlement_export.head(10).to_string())

print("\nPayout sample:")
print(payout_export.head(10).to_string())

Settlement line types:

            line_count
line_type
SALE             70899
REFUND           24963
ADJUSTMENT         850

Settlement missing values:

                   missing_count
order_reference             1381
statement_line_id              0
partner_code                   0
line_type                      0
transaction_date               0
payout_date                    0
currency                       0
gross_amount                   0
platform_fee                   0
payment_fee                    0
tax_withheld                   0
refund_adjustment              0
manual_adjustment              0
net_amount                     0
source_file                    0
ingested_at                    0

Settlement sample:
  statement_line_id order_reference partner_code line_type     transaction_date          payout_date currency gross_amount platform_fee payment_fee tax_withheld refund_adjustment manual_adjustment net_amount                   source_file         ingested_at
0     SET-000000001   ORD-000000001         CH_A      SALE           2025-10-08  2025-10-29 19:19:09        €        32.74        -4.58       -0.62        -5.08               0.0               0.0      22.46  settlement_CH_A_20251029.csv 2025-10-30 01:19:09
1     SET-000000002   ORD-000000003         CH_C      SALE           29/08/2025  2025-09-09 05:46:06      EUR        68.78        -8.25       -1.78       -14.25               0.0               0.0       44.5  settlement_CH_C_20250909.csv 2025-09-12 04:46:06
2     SET-000000003   ORD-000000004         CH_C      SALE  2025-03-22 07:05:28           2025-04-11     Euro        83.17        -9.98       -2.21       -16.63               0.0               0.0      54.35  settlement_CH_C_20250411.csv 2025-04-13 10:05:28
3     SET-000000004   ORD-000000005         CH_A      SALE           2025-09-30           17/10/2025      EUR        46.78        -6.55       -1.11        -7.75               0.0               0.0      31.37  settlement_CH_A_20251017.csv 2025-10-18 18:38:34
4     SET-000000005   ORD-000000006         CH_C      SALE           14/05/2025           2025-05-23     Euro        115.8        -13.9       -3.32        -22.0               0.0               0.0      76.58  settlement_CH_C_20250523.csv 2025-05-26 03:57:09
5     SET-000000006   ORD-000000007         CH_D      SALE           2025-06-27           2025-07-15      SEK        86.42       -15.56       -1.88       -20.61               0.0               0.0      48.37  settlement_CH_D_20250715.csv 2025-07-18 01:23:19
6     SET-000000007   ORD-000000008         CH_A      SALE  2025-07-27 00:30:04  2025-08-12 00:30:04      EUR        53.76        -7.53        -1.7        -9.46               0.0               0.0      35.07  settlement_CH_A_20250812.csv 2025-08-12 20:30:04
7     SET-000000008   ORD-000000009         CH_A      SALE  2025-12-07 10:48:33           21/12/2025      GBP        31.87        -4.46       -0.76        -5.18               0.0               0.0      21.47  settlement_CH_A_20251221.csv 2025-12-23 00:48:33
8     SET-000000009   ORD-000000010         CH_B      SALE           2026-05-24  2026-06-06 20:53:17        €        23.95        -3.83       -0.72        -3.41               0.0               0.0      15.99  settlement_CH_B_20260606.csv 2026-06-09 16:53:17
9     SET-000000010   ORD-000000011         CH_C      SALE           2026-02-08           2026-02-16      EUR        53.22        -6.39       -1.44        -9.45               0.0               0.0      35.94  settlement_CH_C_20260216.csv 2026-02-16 18:34:42

Payout sample:
     payout_id partner_code currency          payout_date  payout_amount  statement_line_count                  source_file         ingested_at
0  PAY-0000001         CH_A      EUR           2025-01-10         912.24                    25  payout_batches_20250110.csv 2025-01-10 09:00:00
1  PAY-0000002         CH_A      EUR           2025-01-20        2277.27                    75  payout_batches_20250120.csv 2025-01-21 16:00:00
2  PAY-0000003         CH_A     Euro           2025-01-25        5201.32                   164  payout_batches_20250125.csv 2025-01-26 00:00:00
3  PAY-0000004         CH_A     Euro           30/01/2025        5758.24                   179  payout_batches_20250130.csv 2025-01-30 20:00:00
4  PAY-0000005         CH_A        €  2025-02-06 00:00:00        5907.88                   207  payout_batches_20250206.csv 2025-02-07 16:00:00
5  PAY-0000006         CH_A        €  2025-02-14 00:00:00        5366.47                   209  payout_batches_20250214.csv 2025-02-15 12:00:00
6  PAY-0000007         CH_A        €           2025-02-19        7157.37                   269  payout_batches_20250219.csv 2025-02-20 07:00:00
7  PAY-0000008         CH_A     Euro           2025-03-01        6268.16                   278  payout_batches_20250301.csv 2025-03-02 08:00:00
8  PAY-0000009         CH_A     Euro           07/03/2025        6057.04                   277  payout_batches_20250307.csv 2025-03-08 09:00:00
9  PAY-0000010        CH_A       EUR           2025-03-14        6266.44                   276  payout_batches_20250314.csv 2025-03-14 13:00:00

In [322]:
import pandas as pd

corrected_path = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "settlement_line_export.csv"
)

check_settlement = pd.read_csv(corrected_path)

print(check_settlement.shape)
print(check_settlement["line_type"].value_counts(dropna=False))
print("Missing line_type values:")
print(check_settlement["line_type"].isna().sum())

(96712, 16)
line_type
SALE          70899
REFUND        24963
ADJUSTMENT      850
Name: count, dtype: int64
Missing line_type values:
0

## Generate synthetic FX-rate data

This file contains synthetic daily exchange rates to GBP.

The rates are created only for analytical demonstration. They are not historical market rates and should not be treated as financial or tax advice.

In [80]:
# Create synthetic daily FX rates to GBP

fx_rng = np.random.default_rng(RANDOM_SEED + 100)

fx_dates = pd.date_range(
    start=PROJECT_START,
    end=PROJECT_END,
    freq="D"
)

fx_currency_parameters = {
    "GBP": {
        "starting_rate": 1.0000,
        "volatility": 0.0000
    },
    "EUR": {
        "starting_rate": 0.8600,
        "volatility": 0.0025
    },
    "SEK": {
        "starting_rate": 0.0740,
        "volatility": 0.0040
    },
    "DKK": {
        "starting_rate": 0.1150,
        "volatility": 0.0015
    }
}

fx_rows = []

for currency_code, parameters in fx_currency_parameters.items():
    current_rate = parameters["starting_rate"]

    for rate_date in fx_dates:
        daily_change = fx_rng.normal(
            loc=0.0,
            scale=parameters["volatility"]
        )

        current_rate = max(
            current_rate * (1 + daily_change),
            parameters["starting_rate"] * 0.75
        )

        fx_rows.append({
            "rate_date_clean": rate_date,
            "from_currency_clean": currency_code,
            "to_currency_clean": "GBP",
            "rate_to_gbp_clean": round(
                float(current_rate),
                6
            ),
            "rate_source_clean": "synthetic_daily_rate"
        })

fx_clean = pd.DataFrame(fx_rows)

print("FX rows created:", f"{len(fx_clean):,}")
display(fx_clean.head())

FX rows created: 2,184

,rate_date_clean,from_currency_clean,to_currency_clean,rate_to_gbp_clean,rate_source_clean
0,2025-01-01,GBP,GBP,1.0,synthetic_daily_rate
1,2025-01-02,GBP,GBP,1.0,synthetic_daily_rate
2,2025-01-03,GBP,GBP,1.0,synthetic_daily_rate
3,2025-01-04,GBP,GBP,1.0,synthetic_daily_rate
4,2025-01-05,GBP,GBP,1.0,synthetic_daily_rate

In [81]:
# Convert FX data into an unfamiliar source format

def format_fx_date(value, format_number):
    if format_number == 0:
        return value.strftime("%Y-%m-%d")
    elif format_number == 1:
        return value.strftime("%d/%m/%Y")
    else:
        return value.strftime("%Y-%m-%d %H:%M:%S")


n_fx_rows = len(fx_clean)

fx_export = pd.DataFrame()

fx_export["rate_date"] = [
    format_fx_date(
        date_value,
        int(format_number)
    )
    for date_value, format_number in zip(
        fx_clean["rate_date_clean"],
        fx_rng.integers(
            0,
            3,
            size=n_fx_rows
        )
    )
]

fx_export["source_currency"] = (
    fx_clean["from_currency_clean"]
)

fx_export["reporting_currency"] = (
    fx_clean["to_currency_clean"]
)

fx_export["conversion_rate"] = (
    fx_clean["rate_to_gbp_clean"]
)

fx_export["rate_source"] = (
    fx_clean["rate_source_clean"]
)

fx_export["source_file"] = (
    "fx_rates_"
    + fx_clean["rate_date_clean"]
    .dt.strftime("%Y%m%d")
    + ".csv"
)

fx_export["ingested_at"] = (
    fx_clean["rate_date_clean"]
    + pd.to_timedelta(
        fx_rng.integers(
            1,
            24,
            size=n_fx_rows
        ),
        unit="h"
    )
)

print("Source-style FX fields created.")
display(fx_export.head())

Source-style FX fields created.

,rate_date,source_currency,reporting_currency,conversion_rate,rate_source,source_file,ingested_at
0,2025-01-01 00:00:00,GBP,GBP,1.0,synthetic_daily_rate,fx_rates_20250101.csv,2025-01-01 08:00:00
1,2025-01-02 00:00:00,GBP,GBP,1.0,synthetic_daily_rate,fx_rates_20250102.csv,2025-01-02 12:00:00
2,03/01/2025,GBP,GBP,1.0,synthetic_daily_rate,fx_rates_20250103.csv,2025-01-03 23:00:00
3,04/01/2025,GBP,GBP,1.0,synthetic_daily_rate,fx_rates_20250104.csv,2025-01-04 09:00:00
4,2025-01-05 00:00:00,GBP,GBP,1.0,synthetic_daily_rate,fx_rates_20250105.csv,2025-01-05 18:00:00

In [82]:
# Add a small amount of source variation

fx_date_missing_mask = fx_rng.random(
    n_fx_rows
) < 0.004

fx_rate_missing_mask = fx_rng.random(
    n_fx_rows
) < 0.003

fx_export.loc[
    fx_date_missing_mask,
    "rate_date"
] = None

fx_export.loc[
    fx_rate_missing_mask,
    "conversion_rate"
] = np.nan

fx_path = RAW_DIR / "fx_daily_rates_export.csv"

fx_export.to_csv(
    fx_path,
    index=False
)

print(f"FX export saved to: {fx_path}")
print(f"Row count: {len(fx_export):,}")
print(
    f"File size in MB: "
    f"{fx_path.stat().st_size / 1024**2:.2f}"
)

FX export saved to: /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/raw/fx_daily_rates_export.csv
Row count: 2,184
File size in MB: 0.19

In [83]:
# Inspect the raw FX-rate export

print("FX columns:")
for column in fx_export.columns:
    print(f" - {column}")

print("\nMissing values:")
display(
    fx_export.isna()
    .sum()
    .to_frame("missing_count")
    .sort_values(
        "missing_count",
        ascending=False
    )
)

print("\nSample rows:")
print(fx_export.head(10).to_string())

FX columns:
 - rate_date
 - source_currency
 - reporting_currency
 - conversion_rate
 - rate_source
 - source_file
 - ingested_at

Missing values:

                    missing_count
rate_date                      12
conversion_rate                 3
source_currency                 0
reporting_currency              0
rate_source                     0
source_file                     0
ingested_at                     0

Sample rows:
             rate_date source_currency reporting_currency  conversion_rate           rate_source            source_file         ingested_at
0  2025-01-01 00:00:00             GBP                GBP              1.0  synthetic_daily_rate  fx_rates_20250101.csv 2025-01-01 08:00:00
1  2025-01-02 00:00:00             GBP                GBP              1.0  synthetic_daily_rate  fx_rates_20250102.csv 2025-01-02 12:00:00
2           03/01/2025             GBP                GBP              1.0  synthetic_daily_rate  fx_rates_20250103.csv 2025-01-03 23:00:00
3           04/01/2025             GBP                GBP              1.0  synthetic_daily_rate  fx_rates_20250104.csv 2025-01-04 09:00:00
4  2025-01-05 00:00:00             GBP                GBP              1.0  synthetic_daily_rate  fx_rates_20250105.csv 2025-01-05 18:00:00
5           2025-01-06             GBP                GBP              1.0  synthetic_daily_rate  fx_rates_20250106.csv 2025-01-06 02:00:00
6           2025-01-07             GBP                GBP              1.0  synthetic_daily_rate  fx_rates_20250107.csv 2025-01-07 14:00:00
7           08/01/2025             GBP                GBP              1.0  synthetic_daily_rate  fx_rates_20250108.csv 2025-01-08 13:00:00
8  2025-01-09 00:00:00             GBP                GBP              1.0  synthetic_daily_rate  fx_rates_20250109.csv 2025-01-09 08:00:00
9           2025-01-10             GBP                GBP              1.0  synthetic_daily_rate  fx_rates_20250110.csv 2025-01-10 02:00:00

## Profile the raw source files

The raw CSV files are now treated as unfamiliar external data.

We will load them as strings first so that mixed dates, currencies, quantities, and monetary formats are preserved for investigation.

In [85]:
# List the raw source files and their sizes

raw_paths = sorted(
    RAW_DIR.glob("*.csv")
)

raw_file_inventory = []

for path in raw_paths:
    raw_file_inventory.append({
        "file_name": path.name,
        "path": str(path),
        "file_size_mb": round(
            path.stat().st_size / 1024**2,
            2
        )
    })

raw_file_inventory = pd.DataFrame(
    raw_file_inventory
)

print("Raw files found:", len(raw_file_inventory))
display(raw_file_inventory)

Raw files found: 9

,file_name,path,file_size_mb
0,fx_daily_rates_export.csv,/Users/tanayajadhav/Desktop/meridian_partner_c...,0.19
1,inventory_snapshot_export.csv,/Users/tanayajadhav/Desktop/meridian_partner_c...,48.25
2,order_header_export.csv,/Users/tanayajadhav/Desktop/meridian_partner_c...,8.70
3,order_line_export.csv,/Users/tanayajadhav/Desktop/meridian_partner_c...,14.97
4,partner_listing_export.csv,/Users/tanayajadhav/Desktop/meridian_partner_c...,83.61
5,payout_batch_export.csv,/Users/tanayajadhav/Desktop/meridian_partner_c...,0.05
6,return_case_export.csv,/Users/tanayajadhav/Desktop/meridian_partner_c...,4.13
7,settlement_line_export.csv,/Users/tanayajadhav/Desktop/meridian_partner_c...,14.21
8,shipment_event_export.csv,/Users/tanayajadhav/Desktop/meridian_partner_c...,47.02

In [86]:
# Load raw files as strings to preserve source formatting

raw_tables = {}

for path in raw_paths:
    print(f"Loading {path.name}...")

    raw_tables[path.stem] = pd.read_csv(
        path,
        dtype="string",
        low_memory=False
    )

print("\nRaw files loaded successfully.")

for table_name, table in raw_tables.items():
    print(
        f"{table_name}: "
        f"{table.shape[0]:,} rows x "
        f"{table.shape[1]} columns"
    )

Loading fx_daily_rates_export.csv...
Loading inventory_snapshot_export.csv...
Loading order_header_export.csv...
Loading order_line_export.csv...
Loading partner_listing_export.csv...
Loading payout_batch_export.csv...
Loading return_case_export.csv...
Loading settlement_line_export.csv...
Loading shipment_event_export.csv...

Raw files loaded successfully.
fx_daily_rates_export: 2,184 rows x 7 columns
inventory_snapshot_export: 399,575 rows x 11 columns
order_header_export: 75,000 rows x 12 columns
order_line_export: 130,522 rows x 10 columns
partner_listing_export: 401,173 rows x 14 columns
payout_batch_export: 595 rows x 8 columns
return_case_export: 24,963 rows x 14 columns
settlement_line_export: 96,712 rows x 16 columns
shipment_event_export: 338,904 rows x 10 columns

In [87]:
# Create a high-level profile for each raw table

table_profile_rows = []

for table_name, table in raw_tables.items():
    table_profile_rows.append({
        "table_name": table_name,
        "row_count": len(table),
        "column_count": len(table.columns),
        "missing_cell_count": int(
            table.isna().sum().sum()
        ),
        "exact_duplicate_row_count": int(
            table.duplicated().sum()
        ),
        "file_size_mb": raw_file_inventory.loc[
            raw_file_inventory["file_name"]
            == f"{table_name}.csv",
            "file_size_mb"
        ].iloc[0]
    })

raw_table_profile = pd.DataFrame(
    table_profile_rows
).sort_values(
    "row_count",
    ascending=False
)

display(raw_table_profile)

,table_name,row_count,column_count,missing_cell_count,exact_duplicate_row_count,file_size_mb
4,partner_listing_export,401173,14,15864,0,83.61
1,inventory_snapshot_export,399575,11,10298,0,48.25
8,shipment_event_export,338904,10,134554,0,47.02
3,order_line_export,130522,10,2309,0,14.97
7,settlement_line_export,96712,16,98093,0,14.21
2,order_header_export,75000,12,2679,0,8.70
6,return_case_export,24963,14,933,0,4.13
0,fx_daily_rates_export,2184,7,15,0,0.19
5,payout_batch_export,595,8,0,0,0.05

In [88]:
# Create a column-level profile for every raw table

column_profile_rows = []

for table_name, table in raw_tables.items():
    for column in table.columns:
        non_null_values = table[column].dropna()

        sample_values = (
            non_null_values
            .drop_duplicates()
            .head(5)
            .tolist()
        )

        column_profile_rows.append({
            "table_name": table_name,
            "column_name": column,
            "missing_count": int(
                table[column].isna().sum()
            ),
            "missing_percentage": round(
                table[column].isna().mean() * 100,
                2
            ),
            "unique_count": int(
                table[column].nunique(dropna=True)
            ),
            "sample_values": " | ".join(
                str(value)
                for value in sample_values
            )
        })

raw_column_profile = pd.DataFrame(
    column_profile_rows
)

display(
    raw_column_profile.head(30)
)

,table_name,column_name,missing_count,missing_percentage,unique_count,sample_values
0,fx_daily_rates_export,rate_date,12,0.55,1350,2025-01-01 00:00:00 | 2025-01-02 00:00:00 | 03...
1,fx_daily_rates_export,source_currency,0,0.00,4,GBP | EUR | SEK | DKK
2,fx_daily_rates_export,reporting_currency,0,0.00,1,GBP
3,fx_daily_rates_export,conversion_rate,3,0.14,1584,1.0 | 0.861474 | 0.863051 | 0.865762 | 0.866244
4,fx_daily_rates_export,rate_source,0,0.00,1,synthetic_daily_rate
5,fx_daily_rates_export,source_file,0,0.00,546,fx_rates_20250101.csv | fx_rates_20250102.csv ...
6,fx_daily_rates_export,ingested_at,0,0.00,2063,2025-01-01 08:00:00 | 2025-01-02 12:00:00 | 20...
7,inventory_snapshot_export,partner_code,0,0.00,8,CH_A | CH_B | CH_B | CH_A | CH_C
8,inventory_snapshot_export,item_code,0,0.00,11795,CH_A_SKU_000312 | CH_B_SKU_000312 | CH_A_SKU_0...
9,inventory_snapshot_export,market,0,0.00,10,DE | SWE | FR | NLD | IT
10,inventory_snapshot_export,warehouse,1505,0.38,4,WH_CENTRAL | WH_EUROPE | WH_SOUTH | WH_NORTH
11,inventory_snapshot_export,available_qty,2397,0.60,82,2.0 | 15.0 | 5.0 | 7.0 | 14.0
12,inventory_snapshot_export,reserved_qty,3618,0.91,22,0.0 | 1.0 | 3.0 | 8.0 | 4.0
13,inventory_snapshot_export,inbound_qty,0,0.00,13,2 | 1 | 4 | 6 | 3
14,inventory_snapshot_export,inventory_timestamp_clean,0,0.00,9056,2025-01-04 03:00:00 | 2025-01-04 20:00:00 | 20...
15,inventory_snapshot_export,inventory_timestamp,2778,0.70,9615,2025-01-04 03:00:00 | 2025-01-04 20:00:00 | 20...
16,inventory_snapshot_export,source_file,0,0.00,281,inventory_CH_A_20250101.csv | inventory_CH_B_2...
17,inventory_snapshot_export,ingested_at,0,0.00,12328,2025-01-06 01:00:00 | 2025-01-05 13:00:00 | 20...
18,order_header_export,source_order_id,0,0.00,75000,ORD-000000001 | ORD-000000002 | ORD-000000003 ...
19,order_header_export,source_partner_code,0,0.00,8,CH_A | CH_C | CH_D | CH_B | CH_A
20,order_header_export,source_market,0,0.00,10,DE | UK | IT | ESP | SWE
21,order_header_export,source_created_at,0,0.00,74626,2025-10-06 19:19:09 | 2026-03-02 09:37:57 | 20...
22,order_header_export,source_currency,0,0.00,11,€ | £ | Euro | EUR | kr
23,order_header_export,source_status,443,0.59,6,COMPLETED | CANCELLED | OPEN | REFUNDED | RETU...
24,order_header_export,source_item_amount,0,0.00,14314,26.75 | 45.17 | 64.79 | 85.95 | 40.79
25,order_header_export,source_shipping_amount,908,1.21,3,5.99 | 3.99 | 0.0
26,order_header_export,source_discount_amount,0,0.00,2854,0.0 | 6.77 | 15.98 | 5.29 | 14.41
27,order_header_export,source_tax_amount,1328,1.77,4498,5.08 | 9.03 | 14.25 | 16.63 | 7.75
28,order_header_export,source_file,0,0.00,1974,orders_CH_A_20251006.csv | orders_CH_A_2026030...
29,order_header_export,ingested_at,0,0.00,74931,2025-10-07 03:19:09 | 2026-03-02 23:37:57 | 20...

In [89]:
# Review fields with missing values

missing_profile = (
    raw_column_profile[
        raw_column_profile["missing_count"] > 0
    ]
    .sort_values(
        [
            "missing_percentage",
            "table_name"
        ],
        ascending=[False, True]
    )
)

print(
    "Columns containing missing values:",
    len(missing_profile)
)

display(missing_profile)

Columns containing missing values: 21

,table_name,column_name,missing_count,missing_percentage,unique_count,sample_values
79,settlement_line_export,line_type,96712,100.00,0,
96,shipment_event_export,tracking_number,127385,37.59,211251,TRK-29027055 | TRK-76251784 | TRK-75893422 | T...
50,partner_listing_export,source_image_url,7165,1.79,6858,https://fictional.example/images/CH_A_SKU_0003...
27,order_header_export,source_tax_amount,1328,1.77,4498,5.08 | 9.03 | 14.25 | 16.63 | 7.75
36,order_line_export,source_line_discount,2309,1.77,2993,0.0 | 1.28 | 5.49 | 11.26 | 4.72
67,return_case_export,reason,404,1.62,7,size_or_fit | damaged_in_transit | wrong_item ...
77,settlement_line_export,order_reference,1381,1.43,70249,ORD-000000001 | ORD-000000003 | ORD-000000004 ...
99,shipment_event_export,promised_date,4145,1.22,1653,2025-10-13 00:00:00 | 2025-10-14 00:00:00 | 20...
25,order_header_export,source_shipping_amount,908,1.21,3,5.99 | 3.99 | 0.0
48,partner_listing_export,source_title,4726,1.18,2926,Oak & Vale Menswear SKU_000312 | Oak & Vale Ho...
71,return_case_export,received_at,285,1.14,9345,08/07/2025 | 2025-08-17 | 12/01/2026 | 2026-06...
49,partner_listing_export,source_category,3973,0.99,12,Menswear | Home | Womenswear | Accessories | F...
72,return_case_export,refund_amount,244,0.98,7182,51.97 | 17.37 | 3.53 | 17.6 | 134.46
12,inventory_snapshot_export,reserved_qty,3618,0.91,22,0.0 | 1.0 | 3.0 | 8.0 | 4.0
95,shipment_event_export,carrier,3024,0.89,4,CAR_C | CAR_A | CAR_B | CAR_D
15,inventory_snapshot_export,inventory_timestamp,2778,0.70,9615,2025-01-04 03:00:00 | 2025-01-04 20:00:00 | 20...
11,inventory_snapshot_export,available_qty,2397,0.60,82,2.0 | 15.0 | 5.0 | 7.0 | 14.0
23,order_header_export,source_status,443,0.59,6,COMPLETED | CANCELLED | OPEN | REFUNDED | RETU...
0,fx_daily_rates_export,rate_date,12,0.55,1350,2025-01-01 00:00:00 | 2025-01-02 00:00:00 | 03...
10,inventory_snapshot_export,warehouse,1505,0.38,4,WH_CENTRAL | WH_EUROPE | WH_SOUTH | WH_NORTH
3,fx_daily_rates_export,conversion_rate,3,0.14,1584,1.0 | 0.861474 | 0.863051 | 0.865762 | 0.866244

In [90]:
# Display the columns and sample values for each raw table

for table_name, table in raw_tables.items():
    print("\n" + "=" * 80)
    print(f"TABLE: {table_name}")
    print("=" * 80)

    print("Columns:")
    print(list(table.columns))

    print("\nSample rows:")
    print(table.head(3).to_string())

================================================================================
TABLE: fx_daily_rates_export
================================================================================
Columns:
['rate_date', 'source_currency', 'reporting_currency', 'conversion_rate', 'rate_source', 'source_file', 'ingested_at']

Sample rows:
             rate_date source_currency reporting_currency conversion_rate           rate_source            source_file          ingested_at
0  2025-01-01 00:00:00             GBP                GBP             1.0  synthetic_daily_rate  fx_rates_20250101.csv  2025-01-01 08:00:00
1  2025-01-02 00:00:00             GBP                GBP             1.0  synthetic_daily_rate  fx_rates_20250102.csv  2025-01-02 12:00:00
2           03/01/2025             GBP                GBP             1.0  synthetic_daily_rate  fx_rates_20250103.csv  2025-01-03 23:00:00

================================================================================
TABLE: inventory_snapshot_export
================================================================================
Columns:
['partner_code', 'item_code', 'market', 'warehouse', 'available_qty', 'reserved_qty', 'inbound_qty', 'inventory_timestamp_clean', 'inventory_timestamp', 'source_file', 'ingested_at']

Sample rows:
  partner_code        item_code market   warehouse available_qty reserved_qty inbound_qty inventory_timestamp_clean  inventory_timestamp                  source_file          ingested_at
0         CH_A  CH_A_SKU_000312     DE  WH_CENTRAL           2.0          0.0           2       2025-01-04 03:00:00  2025-01-04 03:00:00  inventory_CH_A_20250101.csv  2025-01-06 01:00:00
1         CH_B  CH_B_SKU_000312    SWE   WH_EUROPE          15.0          0.0           1       2025-01-04 20:00:00  2025-01-04 20:00:00  inventory_CH_B_20250101.csv  2025-01-05 13:00:00
2         CH_A  CH_A_SKU_000531    SWE  WH_CENTRAL           5.0          0.0           4       2025-01-04 05:00:00  2025-01-04 05:00:00  inventory_CH_A_20250101.csv  2025-01-05 09:00:00

================================================================================
TABLE: order_header_export
================================================================================
Columns:
['source_order_id', 'source_partner_code', 'source_market', 'source_created_at', 'source_currency', 'source_status', 'source_item_amount', 'source_shipping_amount', 'source_discount_amount', 'source_tax_amount', 'source_file', 'ingested_at']

Sample rows:
  source_order_id source_partner_code source_market    source_created_at source_currency source_status source_item_amount source_shipping_amount source_discount_amount source_tax_amount               source_file          ingested_at
0   ORD-000000001                CH_A            DE  2025-10-06 19:19:09               €     COMPLETED              26.75                   5.99                    0.0              5.08  orders_CH_A_20251006.csv  2025-10-07 03:19:09
1   ORD-000000002                CH_A            UK  2026-03-02 09:37:57               £     CANCELLED              45.17                   5.99                    0.0              9.03  orders_CH_A_20260302.csv  2026-03-02 23:37:57
2   ORD-000000003                CH_C            IT  2025-08-29T05:46:06               €     COMPLETED              64.79                   3.99                    0.0             14.25  orders_CH_C_20250829.csv  2025-08-29 23:46:06

================================================================================
TABLE: order_line_export
================================================================================
Columns:
['source_order_id', 'source_line_id', 'source_partner_code', 'source_item_code', 'source_quantity', 'source_unit_price', 'source_line_discount', 'source_currency', 'source_file', 'ingested_at']

Sample rows:
  source_order_id     source_line_id source_partner_code source_item_code source_quantity source_unit_price source_line_discount source_currency                    source_file          ingested_at
0   ORD-000000001  ORD-000000001-L01                CH_A  CH_A_SKU_000409               1             11.08                  0.0               €  order_lines_CH_A_20251006.csv  2025-10-07 08:19:09
1   ORD-000000001  ORD-000000001-L02                CH_A  CH_A_SKU_002677               1              6.99                  0.0               €  order_lines_CH_A_20251006.csv  2025-10-07 11:19:09
2   ORD-000000001  ORD-000000001-L03                CH_A  CH_A_SKU_001513               1              8.68                  0.0               €  order_lines_CH_A_20251006.csv  2025-10-07 10:19:09

================================================================================
TABLE: partner_listing_export
================================================================================
Columns:
['source_partner_code', 'source_market', 'source_item_code', 'source_snapshot_date', 'source_listing_state', 'source_price', 'source_currency', 'source_stock', 'source_title', 'source_category', 'source_image_url', 'source_inventory_update', 'source_file', 'ingested_at']

Sample rows:
  source_partner_code source_market source_item_code source_snapshot_date source_listing_state source_price source_currency source_stock                    source_title source_category                                      source_image_url source_inventory_update                        source_file          ingested_at
0                CH_A            DE  CH_A_SKU_000312  2025-01-01 00:00:00                 LIVE         42.6               €            3  Oak & Vale Menswear SKU_000312        Menswear  https://fictional.example/images/CH_A_SKU_000312.jpg              2025-01-02  partner_listing_CH_A_20250101.csv  2025-01-03 17:00:00
1               CH_B            SWE  CH_B_SKU_000312  2025-01-01 00:00:00                 LIVE       630.34              kr           15  Oak & Vale Menswear SKU_000312        Menswear  https://fictional.example/images/CH_B_SKU_000312.jpg              04/01/2025  partner_listing_CH_B_20250101.csv  2025-01-03 05:00:00
2                CH_A           SWE  CH_A_SKU_000531  2025-01-01 00:00:00                 LIVE       215.06             SEK            2      Oak & Vale Home SKU_000531            Home  https://fictional.example/images/CH_A_SKU_000531.jpg     2025-01-02 23:00:00  partner_listing_CH_A_20250101.csv  2025-01-03 10:00:00

================================================================================
TABLE: payout_batch_export
================================================================================
Columns:
['payout_id', 'partner_code', 'currency', 'payout_date', 'payout_amount', 'statement_line_count', 'source_file', 'ingested_at']

Sample rows:
     payout_id partner_code currency payout_date payout_amount statement_line_count                  source_file          ingested_at
0  PAY-0000001         CH_A      EUR  2025-01-10        912.24                   25  payout_batches_20250110.csv  2025-01-10 09:00:00
1  PAY-0000002         CH_A      EUR  2025-01-20       2277.27                   75  payout_batches_20250120.csv  2025-01-21 16:00:00
2  PAY-0000003         CH_A     Euro  2025-01-25       5201.32                  164  payout_batches_20250125.csv  2025-01-26 00:00:00

================================================================================
TABLE: return_case_export
================================================================================
Columns:
['return_id', 'external_order_id', 'line_ref', 'partner_code', 'market', 'reason', 'status', 'disposition', 'requested_at', 'received_at', 'refund_amount', 'currency', 'source_file', 'ingested_at']

Sample rows:
       return_id external_order_id           line_ref partner_code market              reason      status      disposition requested_at received_at refund_amount        currency                source_file          ingested_at
0  RET-000000001     ORD-000000007  ORD-000000007-L01         CH_D    SWE         size_or_fit    refunded        resalable   2025-07-02  08/07/2025         51.97              kr  returns_CH_D_20250702.csv  2025-07-10 08:23:19
1  RET-000000002     ORD-000000008  ORD-000000008-L02         CH_A     DE         size_or_fit    rejected  supplier_review   15/08/2025  2025-08-17         17.37             EUR  returns_CH_A_20250815.csv  2025-08-19 19:30:04
2  RET-000000003     ORD-000000009  ORD-000000009-L02         CH_A     UK  damaged_in_transit  in_transit        resalable   2026-01-02  12/01/2026          3.53  Pound Sterling  returns_CH_A_20260102.csv  2026-01-14 15:48:33

================================================================================
TABLE: settlement_line_export
================================================================================
Columns:
['statement_line_id', 'order_reference', 'partner_code', 'line_type', 'transaction_date', 'payout_date', 'currency', 'gross_amount', 'platform_fee', 'payment_fee', 'tax_withheld', 'refund_adjustment', 'manual_adjustment', 'net_amount', 'source_file', 'ingested_at']

Sample rows:
  statement_line_id order_reference partner_code line_type     transaction_date          payout_date currency gross_amount platform_fee payment_fee tax_withheld refund_adjustment manual_adjustment net_amount                   source_file          ingested_at
0     SET-000000001   ORD-000000001         CH_A      <NA>           2025-10-08  2025-10-29 19:19:09        €        32.74        -4.58       -0.62        -5.08               0.0               0.0      22.46  settlement_CH_A_20251029.csv  2025-10-30 01:19:09
1     SET-000000002   ORD-000000003         CH_C      <NA>           29/08/2025  2025-09-09 05:46:06      EUR        68.78        -8.25       -1.78       -14.25               0.0               0.0       44.5  settlement_CH_C_20250909.csv  2025-09-12 04:46:06
2     SET-000000003   ORD-000000004         CH_C      <NA>  2025-03-22 07:05:28           2025-04-11     Euro        83.17        -9.98       -2.21       -16.63               0.0               0.0      54.35  settlement_CH_C_20250411.csv  2025-04-13 10:05:28

================================================================================
TABLE: shipment_event_export
================================================================================
Columns:
['external_order_id', 'line_ref', 'event', 'carrier', 'tracking_number', 'fulfilment_market', 'event_time', 'promised_date', 'source_file', 'ingested_at']

Sample rows:
  external_order_id           line_ref     event carrier tracking_number fulfilment_market           event_time        promised_date                   source_file          ingested_at
0     ORD-000000001  ORD-000000001-L01  ACCEPTED   CAR_C            <NA>                DE  2025-10-08 12:19:09  2025-10-13 00:00:00  shipment_events_20251008.csv  2025-10-08 21:19:09
1     ORD-000000001  ORD-000000001-L02  ACCEPTED   CAR_C            <NA>                DE  2025-10-06T23:19:09  2025-10-14 00:00:00  shipment_events_20251006.csv  2025-10-07 11:19:09
2     ORD-000000001  ORD-000000001-L03  ACCEPTED   CAR_A            <NA>                DE  2025-10-06T23:19:09  2025-10-11 00:00:00  shipment_events_20251006.csv  2025-10-08 07:19:09

In [91]:
# Save profiling outputs for later reference

table_profile_path = (
    PROCESSED_DIR / "raw_table_profile.csv"
)

column_profile_path = (
    PROCESSED_DIR / "raw_column_profile.csv"
)

raw_table_profile.to_csv(
    table_profile_path,
    index=False
)

raw_column_profile.to_csv(
    column_profile_path,
    index=False
)

print(f"Table profile saved to: {table_profile_path}")
print(f"Column profile saved to: {column_profile_path}")

Table profile saved to: /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/raw_table_profile.csv
Column profile saved to: /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/raw_column_profile.csv

## Define the data-quality rule catalogue

These rules are based on the source schemas and the fictional commerce process.

They will be used to classify records as valid, corrected, quarantined, excluded from specific metrics, or retained for investigation.

In [93]:
# Create a documented data-quality rule catalogue

dq_rule_catalog = pd.DataFrame([
    {
        "rule_id": "LIST-001",
        "table_name": "partner_listing_export",
        "field_or_fields": "source_partner_code",
        "rule_description": "Partner code must be present and map to the partner reference table.",
        "severity": "critical",
        "action": "quarantine",
        "business_rationale": "Without a partner identifier, the listing cannot be attributed or investigated."
    },
    {
        "rule_id": "LIST-002",
        "table_name": "partner_listing_export",
        "field_or_fields": "source_item_code",
        "rule_description": "Partner item code must be present after trimming whitespace.",
        "severity": "critical",
        "action": "quarantine",
        "business_rationale": "The product cannot be mapped without a usable partner item code."
    },
    {
        "rule_id": "LIST-003",
        "table_name": "partner_listing_export",
        "field_or_fields": "source_snapshot_date",
        "rule_description": "Snapshot date must parse into a valid date.",
        "severity": "high",
        "action": "quarantine",
        "business_rationale": "A record without a valid snapshot date cannot support trend or freshness analysis."
    },
    {
        "rule_id": "LIST-004",
        "table_name": "partner_listing_export",
        "field_or_fields": "source_market",
        "rule_description": "Country aliases must map to a recognised country code.",
        "severity": "high",
        "action": "correct_or_quarantine",
        "business_rationale": "Country attribution is required for international performance analysis."
    },
    {
        "rule_id": "LIST-005",
        "table_name": "partner_listing_export",
        "field_or_fields": "source_price",
        "rule_description": "Price must be parseable and non-negative.",
        "severity": "high",
        "action": "quarantine",
        "business_rationale": "Invalid prices can affect product availability and commercial reporting."
    },
    {
        "rule_id": "LIST-006",
        "table_name": "partner_listing_export",
        "field_or_fields": "source_stock",
        "rule_description": "Reported stock must be parseable and non-negative.",
        "severity": "high",
        "action": "quarantine_or_investigate",
        "business_rationale": "Invalid stock values can create false availability or overselling risk."
    },
    {
        "rule_id": "LIST-007",
        "table_name": "partner_listing_export",
        "field_or_fields": "source_listing_state",
        "rule_description": "Listing state must belong to the documented source-status vocabulary.",
        "severity": "medium",
        "action": "standardise_or_investigate",
        "business_rationale": "Status values drive live-listing and offline-item metrics."
    },
    {
        "rule_id": "LIST-008",
        "table_name": "partner_listing_export",
        "field_or_fields": "partner_code, item_code, snapshot_date",
        "rule_description": "Repeated business keys require investigation before deduplication.",
        "severity": "medium",
        "action": "retain_or_deduplicate_with_lineage",
        "business_rationale": "Repeated exports may be retries, amendments, or true duplicates."
    },
    {
        "rule_id": "INV-001",
        "table_name": "inventory_snapshot_export",
        "field_or_fields": "partner_code, item_code",
        "rule_description": "Partner and item identifiers must be present after trimming.",
        "severity": "critical",
        "action": "quarantine",
        "business_rationale": "Inventory cannot be reconciled without usable identifiers."
    },
    {
        "rule_id": "INV-002",
        "table_name": "inventory_snapshot_export",
        "field_or_fields": "available_qty, reserved_qty, inbound_qty",
        "rule_description": "Inventory quantities must be numeric and non-negative.",
        "severity": "high",
        "action": "quarantine_or_investigate",
        "business_rationale": "Invalid quantities can distort availability and stock-risk analysis."
    },
    {
        "rule_id": "ORDER-001",
        "table_name": "order_header_export",
        "field_or_fields": "source_order_id",
        "rule_description": "Order identifier must be present.",
        "severity": "critical",
        "action": "quarantine",
        "business_rationale": "Order lines, fulfilment events, returns, and settlement lines depend on the order identifier."
    },
    {
        "rule_id": "ORDER-002",
        "table_name": "order_header_export",
        "field_or_fields": "source_created_at",
        "rule_description": "Order timestamp must parse into a valid timestamp.",
        "severity": "high",
        "action": "quarantine",
        "business_rationale": "Order timing is required for trend, latency, and settlement analysis."
    },
    {
        "rule_id": "ORDER-003",
        "table_name": "order_header_export",
        "field_or_fields": "source_status",
        "rule_description": "Order status must map to the canonical status vocabulary.",
        "severity": "medium",
        "action": "standardise_or_investigate",
        "business_rationale": "Order status determines whether sales, cancellations, and refunds are included in KPIs."
    },
    {
        "rule_id": "LINE-001",
        "table_name": "order_line_export",
        "field_or_fields": "source_order_id, source_line_id",
        "rule_description": "Order and line identifiers must be present.",
        "severity": "critical",
        "action": "quarantine",
        "business_rationale": "A line without an order relationship cannot be reconciled."
    },
    {
        "rule_id": "LINE-002",
        "table_name": "order_line_export",
        "field_or_fields": "source_quantity",
        "rule_description": "Quantity must parse into a positive numeric value.",
        "severity": "high",
        "action": "quarantine",
        "business_rationale": "Quantity is required for units and order-value analysis."
    },
    {
        "rule_id": "SHIP-001",
        "table_name": "shipment_event_export",
        "field_or_fields": "external_order_id, line_ref, event",
        "rule_description": "Shipment event must have an order, line, and recognised event type.",
        "severity": "high",
        "action": "quarantine_or_investigate",
        "business_rationale": "Operational events must be connected to an order line."
    },
    {
        "rule_id": "RETURN-001",
        "table_name": "return_case_export",
        "field_or_fields": "return_id, external_order_id, line_ref",
        "rule_description": "Return identifier and order relationship should be present.",
        "severity": "high",
        "action": "quarantine_or_investigate",
        "business_rationale": "Returns must be connected to sales to calculate net revenue and return rates."
    },
    {
        "rule_id": "SETTLE-001",
        "table_name": "settlement_line_export",
        "field_or_fields": "statement_line_id, partner_code, line_type",
        "rule_description": "Settlement line must have a line identifier, partner, and recognised line type.",
        "severity": "critical",
        "action": "quarantine",
        "business_rationale": "Settlement lines must be attributable and classified."
    },
    {
        "rule_id": "SETTLE-002",
        "table_name": "settlement_line_export",
        "field_or_fields": "net_amount",
        "rule_description": "Net amount must be parseable as a monetary value.",
        "severity": "high",
        "action": "quarantine",
        "business_rationale": "Settlement reconciliation depends on a valid amount."
    },
    {
        "rule_id": "SETTLE-003",
        "table_name": "settlement_line_export",
        "field_or_fields": "order_reference",
        "rule_description": "Missing order references should be retained as unallocated settlement items rather than automatically deleted.",
        "severity": "medium",
        "action": "retain_and_flag",
        "business_rationale": "Aggregated or manual adjustments may legitimately lack an order-level reference."
    }
])

print(
    "Data-quality rules created:",
    len(dq_rule_catalog)
)

display(dq_rule_catalog.head(10))

Data-quality rules created: 20

,rule_id,table_name,field_or_fields,rule_description,severity,action,business_rationale
0,LIST-001,partner_listing_export,source_partner_code,Partner code must be present and map to the pa...,critical,quarantine,"Without a partner identifier, the listing cann..."
1,LIST-002,partner_listing_export,source_item_code,Partner item code must be present after trimmi...,critical,quarantine,The product cannot be mapped without a usable ...
2,LIST-003,partner_listing_export,source_snapshot_date,Snapshot date must parse into a valid date.,high,quarantine,A record without a valid snapshot date cannot ...
3,LIST-004,partner_listing_export,source_market,Country aliases must map to a recognised count...,high,correct_or_quarantine,Country attribution is required for internatio...
4,LIST-005,partner_listing_export,source_price,Price must be parseable and non-negative.,high,quarantine,Invalid prices can affect product availability...
5,LIST-006,partner_listing_export,source_stock,Reported stock must be parseable and non-negat...,high,quarantine_or_investigate,Invalid stock values can create false availabi...
6,LIST-007,partner_listing_export,source_listing_state,Listing state must belong to the documented so...,medium,standardise_or_investigate,Status values drive live-listing and offline-i...
7,LIST-008,partner_listing_export,"partner_code, item_code, snapshot_date",Repeated business keys require investigation b...,medium,retain_or_deduplicate_with_lineage,"Repeated exports may be retries, amendments, o..."
8,INV-001,inventory_snapshot_export,"partner_code, item_code",Partner and item identifiers must be present a...,critical,quarantine,Inventory cannot be reconciled without usable ...
9,INV-002,inventory_snapshot_export,"available_qty, reserved_qty, inbound_qty",Inventory quantities must be numeric and non-n...,high,quarantine_or_investigate,Invalid quantities can distort availability an...

In [94]:
# Review the data-quality rule coverage

print("Rules by table:")
display(
    dq_rule_catalog
    .groupby("table_name")
    .size()
    .reset_index(name="rule_count")
    .sort_values("rule_count", ascending=False)
)

print("\nRules by severity:")
display(
    dq_rule_catalog
    .groupby("severity")
    .size()
    .reset_index(name="rule_count")
    .sort_values("rule_count", ascending=False)
)

print("\nRules by action:")
display(
    dq_rule_catalog
    .groupby("action")
    .size()
    .reset_index(name="rule_count")
    .sort_values("rule_count", ascending=False)
)

Rules by table:

                  table_name  rule_count
3     partner_listing_export           8
1        order_header_export           3
5     settlement_line_export           3
0  inventory_snapshot_export           2
2          order_line_export           2
4         return_case_export           1
6      shipment_event_export           1

Rules by severity:

   severity  rule_count
1      high          10
0  critical           6
2    medium           4

Rules by action:

                               action  rule_count
1                          quarantine          11
2           quarantine_or_investigate           4
5          standardise_or_investigate           2
0               correct_or_quarantine           1
3                     retain_and_flag           1
4  retain_or_deduplicate_with_lineage           1

In [95]:
# Save the data-quality rule catalogue

dq_rule_catalog_path = (
    PROCESSED_DIR / "data_quality_rule_catalog.csv"
)

dq_rule_catalog.to_csv(
    dq_rule_catalog_path,
    index=False
)

print(
    f"Data-quality rule catalogue saved to: "
    f"{dq_rule_catalog_path}"
)

Data-quality rule catalogue saved to: /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/data_quality_rule_catalog.csv

## Build Silver listing and inventory tables

The Silver layer standardises raw values while preserving source lineage and data-quality outcomes.

Records are not automatically deleted. Each record receives a status such as valid, review, or quarantine.

In [97]:
# Helper functions for standardising raw source values

def parse_mixed_datetime(series):
    return pd.to_datetime(
        series.astype("string").str.strip(),
        errors="coerce",
        format="mixed",
        dayfirst=True
    )


def parse_mixed_number(series):
    return pd.to_numeric(
        series
        .astype("string")
        .str.strip()
        .str.replace("£", "", regex=False)
        .str.replace("€", "", regex=False)
        .str.replace(" ", "", regex=False)
        .str.replace(",", ".", regex=False),
        errors="coerce"
    )


country_alias_map = {
    "GB": "GB",
    "UK": "GB",
    "GBR": "GB",
    "IE": "IE",
    "DE": "DE",
    "FR": "FR",
    "NL": "NL",
    "NLD": "NL",
    "BE": "BE",
    "ES": "ES",
    "ESP": "ES",
    "IT": "IT",
    "SE": "SE",
    "SWE": "SE",
    "DK": "DK"
}

partner_code_map = {
    partner_id: partner_id
    for partner_id in partner_ref["partner_id"]
}

canonical_status_map = {
    "LIVE": "LIVE",
    "OFFLINE": "OFFLINE",
    "PAUSED": "PAUSED",
    "PREORDER": "PREORDER"
}

country_currency_map = (
    country_ref
    .set_index("country_code")["currency_code"]
    .to_dict()
)


def standardise_currency(currency_value, country_code):
    if pd.isna(currency_value):
        return pd.NA

    value = str(currency_value).strip()

    if value in ["GBP", "£", "Pound Sterling"]:
        return "GBP"

    if value in ["EUR", "€", "Euro"]:
        return "EUR"

    if value in ["SEK", "Swedish Krona"]:
        return "SEK"

    if value in ["DKK", "Danish Krone"]:
        return "DKK"

    # The alias "kr" is ambiguous, so use the country context.
    if value == "kr":
        return country_currency_map.get(
            country_code,
            pd.NA
        )

    return pd.NA


def combine_reasons(reason_series):
    reasons = [
        str(value)
        for value in reason_series
        if pd.notna(value) and str(value) != ""
    ]

    if not reasons:
        return pd.NA

    return "; ".join(reasons)

In [98]:
# Load and standardise the raw listing export

raw_listing = raw_tables[
    "partner_listing_export"
].copy()

silver_listing = pd.DataFrame()

silver_listing["source_row_number"] = (
    raw_listing.index + 1
)

silver_listing["source_partner_code"] = (
    raw_listing["source_partner_code"]
    .astype("string")
    .str.strip()
    .str.upper()
)

silver_listing["partner_id"] = (
    silver_listing["source_partner_code"]
    .map(partner_code_map)
)

silver_listing["source_item_code"] = (
    raw_listing["source_item_code"]
    .astype("string")
    .str.strip()
)

silver_listing["source_market"] = (
    raw_listing["source_market"]
    .astype("string")
    .str.strip()
    .str.upper()
)

silver_listing["country_code"] = (
    silver_listing["source_market"]
    .map(country_alias_map)
)

silver_listing["snapshot_date"] = (
    parse_mixed_datetime(
        raw_listing["source_snapshot_date"]
    )
    .dt.normalize()
)

silver_listing["listing_status"] = (
    raw_listing["source_listing_state"]
    .astype("string")
    .str.strip()
    .str.upper()
    .map(canonical_status_map)
)

silver_listing["price_local"] = (
    parse_mixed_number(
        raw_listing["source_price"]
    )
)

silver_listing["currency_code"] = [
    standardise_currency(
        currency_value,
        country_code
    )
    for currency_value, country_code in zip(
        raw_listing["source_currency"],
        silver_listing["country_code"]
    )
]

silver_listing["available_units"] = (
    parse_mixed_number(
        raw_listing["source_stock"]
    )
)

silver_listing["inventory_updated_at"] = (
    parse_mixed_datetime(
        raw_listing["source_inventory_update"]
    )
)

silver_listing["title"] = (
    raw_listing["source_title"]
)

silver_listing["category_source"] = (
    raw_listing["source_category"]
    .astype("string")
    .str.strip()
)

silver_listing["image_url"] = (
    raw_listing["source_image_url"]
)

silver_listing["source_file"] = (
    raw_listing["source_file"]
)

silver_listing["ingested_at"] = (
    parse_mixed_datetime(
        raw_listing["ingested_at"]
    )
)

print("Listing source values standardised.")
display(silver_listing.head())

Listing source values standardised.

,source_row_number,source_partner_code,partner_id,source_item_code,source_market,country_code,snapshot_date,listing_status,price_local,currency_code,available_units,inventory_updated_at,title,category_source,image_url,source_file,ingested_at
0,1,CH_A,CH_A,CH_A_SKU_000312,DE,DE,2025-01-01,LIVE,42.6,EUR,3,2025-01-02 00:00:00,Oak & Vale Menswear SKU_000312,Menswear,https://fictional.example/images/CH_A_SKU_0003...,partner_listing_CH_A_20250101.csv,2025-01-03 17:00:00
1,2,CH_B,CH_B,CH_B_SKU_000312,SWE,SE,2025-01-01,LIVE,630.34,SEK,15,2025-01-04 00:00:00,Oak & Vale Menswear SKU_000312,Menswear,https://fictional.example/images/CH_B_SKU_0003...,partner_listing_CH_B_20250101.csv,2025-01-03 05:00:00
2,3,CH_A,CH_A,CH_A_SKU_000531,SWE,SE,2025-01-01,LIVE,215.06,SEK,2,2025-01-02 23:00:00,Oak & Vale Home SKU_000531,Home,https://fictional.example/images/CH_A_SKU_0005...,partner_listing_CH_A_20250101.csv,2025-01-03 10:00:00
3,4,CH_B,CH_B,CH_B_SKU_000531,FR,FR,2025-01-01,LIVE,13.43,EUR,7,2025-01-02 00:00:00,Oak & Vale Home SKU_000531,Home,https://fictional.example/images/CH_B_SKU_0005...,partner_listing_CH_B_20250101.csv,2025-01-01 19:00:00
4,5,CH_B,CH_B,CH_B_SKU_000937,DE,DE,2025-01-01,LIVE,16.31,EUR,11,2025-01-04 00:00:00,Juniper Lane Home SKU_000937,Home,https://fictional.example/images/CH_B_SKU_0009...,partner_listing_CH_B_20250101.csv,2025-01-03 22:00:00

In [99]:
# Map partner item codes to internal products

mapping_lookup = (
    partner_product_map[
        [
            "partner_id",
            "partner_sku",
            "internal_sku"
        ]
    ]
    .drop_duplicates()
)

silver_listing = silver_listing.merge(
    mapping_lookup.rename(
        columns={
            "partner_sku": "source_item_code"
        }
    ),
    on=[
        "partner_id",
        "source_item_code"
    ],
    how="left"
)

# Create product content completeness
silver_listing["title_present"] = (
    silver_listing["title"]
    .notna()
    & silver_listing["title"]
    .astype("string")
    .str.strip()
    .ne("")
)

silver_listing["category_present"] = (
    silver_listing["category_source"]
    .notna()
    & silver_listing["category_source"]
    .astype("string")
    .str.strip()
    .ne("")
)

silver_listing["image_present"] = (
    silver_listing["image_url"]
    .notna()
    & silver_listing["image_url"]
    .astype("string")
    .str.strip()
    .ne("")
)

silver_listing["content_completeness_pct"] = (
    silver_listing[
        [
            "title_present",
            "category_present",
            "image_present"
        ]
    ]
    .mean(axis=1)
    * 100
).round(2)

# Determine whether the record is a possible repeated business key
silver_listing["listing_business_key"] = (
    silver_listing["partner_id"].astype("string")
    + "|"
    + silver_listing["source_item_code"].astype("string")
    + "|"
    + silver_listing["country_code"].astype("string")
    + "|"
    + silver_listing["snapshot_date"].astype("string")
)

silver_listing["possible_duplicate_key"] = (
    silver_listing["listing_business_key"]
    .duplicated(keep=False)
)

print("Listing mappings and quality flags created.")

Listing mappings and quality flags created.

In [100]:
# Apply listing data-quality rules

silver_listing["quality_reasons"] = pd.NA

listing_reason_rows = []

for _, row in silver_listing.iterrows():
    reasons = []

    if pd.isna(row["partner_id"]):
        reasons.append("unrecognised_partner")

    if (
        pd.isna(row["source_item_code"])
        or str(row["source_item_code"]).strip() == ""
    ):
        reasons.append("missing_item_code")

    if pd.isna(row["snapshot_date"]):
        reasons.append("invalid_snapshot_date")

    if pd.isna(row["country_code"]):
        reasons.append("unrecognised_country")

    if pd.isna(row["internal_sku"]):
        reasons.append("unmapped_partner_sku")

    if (
        pd.isna(row["price_local"])
        or row["price_local"] < 0
    ):
        reasons.append("invalid_price")

    if (
        pd.notna(row["available_units"])
        and row["available_units"] < 0
    ):
        reasons.append("negative_stock")

    if pd.isna(row["listing_status"]):
        reasons.append("unrecognised_listing_status")

    if row["possible_duplicate_key"]:
        reasons.append("possible_duplicate_business_key")

    listing_reason_rows.append(
        "; ".join(reasons)
        if reasons
        else pd.NA
    )

silver_listing["quality_reasons"] = (
    listing_reason_rows
)

critical_listing_reasons = [
    "unrecognised_partner",
    "missing_item_code",
    "invalid_snapshot_date",
    "unrecognised_country",
    "unmapped_partner_sku",
    "invalid_price"
]

review_listing_reasons = [
    "negative_stock",
    "unrecognised_listing_status",
    "possible_duplicate_business_key"
]

silver_listing["record_status"] = "valid"

for reason in critical_listing_reasons:
    silver_listing.loc[
        silver_listing["quality_reasons"]
        .fillna("")
        .str.contains(reason, regex=False),
        "record_status"
    ] = "quarantine"

for reason in review_listing_reasons:
    review_mask = (
        silver_listing["quality_reasons"]
        .fillna("")
        .str.contains(reason, regex=False)
        & (
            silver_listing["record_status"]
            == "valid"
        )
    )

    silver_listing.loc[
        review_mask,
        "record_status"
    ] = "review"

silver_listing["analysis_included"] = (
    silver_listing["record_status"]
    != "quarantine"
)

silver_listing["live_listing_flag"] = (
    silver_listing["listing_status"].eq("LIVE")
    & silver_listing["available_units"].gt(0)
    & silver_listing["analysis_included"]
)

print("Listing records by status:")
display(
    silver_listing["record_status"]
    .value_counts()
    .to_frame("record_count")
)

Listing records by status:

               record_count
record_status
valid                397977
review                 3196

In [101]:
# Separate listing records requiring quarantine

quarantine_listing = silver_listing[
    silver_listing["record_status"] == "quarantine"
].copy()

print(
    "Listing quarantine records:",
    f"{len(quarantine_listing):,}"
)

display(
    quarantine_listing[
        [
            "source_row_number",
            "source_partner_code",
            "source_item_code",
            "country_code",
            "internal_sku",
            "quality_reasons"
        ]
    ]
    .head(10)
)

Listing quarantine records: 0

Empty DataFrame
Columns: [source_row_number, source_partner_code, source_item_code, country_code, internal_sku, quality_reasons]
Index: []

In [102]:
# Load and standardise the raw inventory export

raw_inventory = raw_tables[
    "inventory_snapshot_export"
].copy()

silver_inventory = pd.DataFrame()

silver_inventory["source_row_number"] = (
    raw_inventory.index + 1
)

silver_inventory["source_partner_code"] = (
    raw_inventory["partner_code"]
    .astype("string")
    .str.strip()
    .str.upper()
)

silver_inventory["partner_id"] = (
    silver_inventory["source_partner_code"]
    .map(partner_code_map)
)

silver_inventory["source_item_code"] = (
    raw_inventory["item_code"]
    .astype("string")
    .str.strip()
)

silver_inventory["source_market"] = (
    raw_inventory["market"]
    .astype("string")
    .str.strip()
    .str.upper()
)

silver_inventory["country_code"] = (
    silver_inventory["source_market"]
    .map(country_alias_map)
)

silver_inventory["warehouse_code"] = (
    raw_inventory["warehouse"]
    .astype("string")
    .str.strip()
)

silver_inventory["available_units"] = (
    parse_mixed_number(
        raw_inventory["available_qty"]
    )
)

silver_inventory["reserved_units"] = (
    parse_mixed_number(
        raw_inventory["reserved_qty"]
    )
)

silver_inventory["inbound_units"] = (
    parse_mixed_number(
        raw_inventory["inbound_qty"]
    )
)

silver_inventory["inventory_timestamp"] = (
    parse_mixed_datetime(
        raw_inventory["inventory_timestamp"]
    )
)

silver_inventory["source_file"] = (
    raw_inventory["source_file"]
)

silver_inventory["ingested_at"] = (
    parse_mixed_datetime(
        raw_inventory["ingested_at"]
    )
)

silver_inventory = silver_inventory.merge(
    mapping_lookup.rename(
        columns={
            "partner_sku": "source_item_code"
        }
    ),
    on=[
        "partner_id",
        "source_item_code"
    ],
    how="left"
)

print("Inventory source values standardised.")
display(silver_inventory.head())

Inventory source values standardised.

,source_row_number,source_partner_code,partner_id,source_item_code,source_market,country_code,warehouse_code,available_units,reserved_units,inbound_units,inventory_timestamp,source_file,ingested_at,internal_sku
0,1,CH_A,CH_A,CH_A_SKU_000312,DE,DE,WH_CENTRAL,2.0,0.0,2,2025-01-04 03:00:00,inventory_CH_A_20250101.csv,2025-01-06 01:00:00,SKU_000312
1,2,CH_B,CH_B,CH_B_SKU_000312,SWE,SE,WH_EUROPE,15.0,0.0,1,2025-01-04 20:00:00,inventory_CH_B_20250101.csv,2025-01-05 13:00:00,SKU_000312
2,3,CH_A,CH_A,CH_A_SKU_000531,SWE,SE,WH_CENTRAL,5.0,0.0,4,2025-01-04 05:00:00,inventory_CH_A_20250101.csv,2025-01-05 09:00:00,SKU_000531
3,4,CH_B,CH_B,CH_B_SKU_000531,FR,FR,WH_SOUTH,7.0,1.0,2,2025-01-03 05:00:00,inventory_CH_B_20250101.csv,2025-01-04 17:00:00,SKU_000531
4,5,CH_B,CH_B,CH_B_SKU_000937,DE,DE,WH_CENTRAL,14.0,1.0,1,2025-01-03 00:00:00,inventory_CH_B_20250101.csv,2025-01-04 20:00:00,SKU_000937

In [103]:
# Apply inventory data-quality rules

silver_inventory["inventory_business_key"] = (
    silver_inventory["partner_id"].astype("string")
    + "|"
    + silver_inventory["source_item_code"].astype("string")
    + "|"
    + silver_inventory["country_code"].astype("string")
    + "|"
    + silver_inventory["warehouse_code"].astype("string")
    + "|"
    + silver_inventory["inventory_timestamp"].astype("string")
)

silver_inventory["possible_duplicate_key"] = (
    silver_inventory["inventory_business_key"]
    .duplicated(keep=False)
)

inventory_reason_rows = []

for _, row in silver_inventory.iterrows():
    reasons = []

    if pd.isna(row["partner_id"]):
        reasons.append("unrecognised_partner")

    if (
        pd.isna(row["source_item_code"])
        or str(row["source_item_code"]).strip() == ""
    ):
        reasons.append("missing_item_code")

    if pd.isna(row["country_code"]):
        reasons.append("unrecognised_country")

    if pd.isna(row["internal_sku"]):
        reasons.append("unmapped_partner_sku")

    if pd.isna(row["inventory_timestamp"]):
        reasons.append("invalid_inventory_timestamp")

    for quantity_column in [
        "available_units",
        "reserved_units",
        "inbound_units"
    ]:
        if (
            pd.notna(row[quantity_column])
            and row[quantity_column] < 0
        ):
            reasons.append(
                f"negative_{quantity_column}"
            )

    if row["possible_duplicate_key"]:
        reasons.append("possible_duplicate_business_key")

    inventory_reason_rows.append(
        "; ".join(reasons)
        if reasons
        else pd.NA
    )

silver_inventory["quality_reasons"] = (
    inventory_reason_rows
)

critical_inventory_reasons = [
    "unrecognised_partner",
    "missing_item_code",
    "unrecognised_country",
    "unmapped_partner_sku",
    "invalid_inventory_timestamp"
]

review_inventory_reasons = [
    "negative_available_units",
    "negative_reserved_units",
    "negative_inbound_units",
    "possible_duplicate_business_key"
]

silver_inventory["record_status"] = "valid"

for reason in critical_inventory_reasons:
    silver_inventory.loc[
        silver_inventory["quality_reasons"]
        .fillna("")
        .str.contains(reason, regex=False),
        "record_status"
    ] = "quarantine"

for reason in review_inventory_reasons:
    review_mask = (
        silver_inventory["quality_reasons"]
        .fillna("")
        .str.contains(reason, regex=False)
        & (
            silver_inventory["record_status"]
            == "valid"
        )
    )

    silver_inventory.loc[
        review_mask,
        "record_status"
    ] = "review"

silver_inventory["analysis_included"] = (
    silver_inventory["record_status"]
    != "quarantine"
)

print("Inventory records by status:")
display(
    silver_inventory["record_status"]
    .value_counts()
    .to_frame("record_count")
)

Inventory records by status:

               record_count
record_status
valid                395306
quarantine             2778
review                 1491

In [104]:
# Save the cleaned Silver-style listing and inventory tables

silver_listing_path = (
    PROCESSED_DIR / "silver_listing.csv"
)

quarantine_listing_path = (
    PROCESSED_DIR / "quarantine_listing.csv"
)

silver_inventory_path = (
    PROCESSED_DIR / "silver_inventory.csv"
)

quarantine_inventory_path = (
    PROCESSED_DIR / "quarantine_inventory.csv"
)

silver_listing.to_csv(
    silver_listing_path,
    index=False
)

quarantine_listing.to_csv(
    quarantine_listing_path,
    index=False
)

silver_inventory.to_csv(
    silver_inventory_path,
    index=False
)

silver_inventory[
    silver_inventory["record_status"] == "quarantine"
].to_csv(
    quarantine_inventory_path,
    index=False
)

print("Processed files saved:")
print(f" - {silver_listing_path}")
print(f" - {quarantine_listing_path}")
print(f" - {silver_inventory_path}")
print(f" - {quarantine_inventory_path}")

Processed files saved:
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/silver_listing.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/quarantine_listing.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/silver_inventory.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/quarantine_inventory.csv

In [105]:
# Review the main Silver outputs

print("Silver listing shape:", silver_listing.shape)
print("Listing quarantine shape:", quarantine_listing.shape)
print("Silver inventory shape:", silver_inventory.shape)

print("\nListing record statuses:")
display(
    silver_listing["record_status"]
    .value_counts()
    .to_frame("record_count")
)

print("\nInventory record statuses:")
display(
    silver_inventory["record_status"]
    .value_counts()
    .to_frame("record_count")
)

print("\nListing mapping coverage:")
display(
    silver_listing["internal_sku"]
    .notna()
    .value_counts()
    .rename(
        index={
            True: "mapped",
            False: "unmapped"
        }
    )
    .to_frame("record_count")
)

print("\nSample cleaned listing records:")
display(
    silver_listing[
        [
            "partner_id",
            "source_item_code",
            "internal_sku",
            "country_code",
            "snapshot_date",
            "listing_status",
            "price_local",
            "currency_code",
            "available_units",
            "record_status"
        ]
    ]
    .head()
)

Silver listing shape: (401173, 28)
Listing quarantine shape: (0, 28)
Silver inventory shape: (399575, 19)

Listing record statuses:

               record_count
record_status
valid                397977
review                 3196

Inventory record statuses:

               record_count
record_status
valid                395306
quarantine             2778
review                 1491

Listing mapping coverage:

              record_count
internal_sku
mapped              401173

Sample cleaned listing records:

,partner_id,source_item_code,internal_sku,country_code,snapshot_date,listing_status,price_local,currency_code,available_units,record_status
0,CH_A,CH_A_SKU_000312,SKU_000312,DE,2025-01-01,LIVE,42.6,EUR,3,valid
1,CH_B,CH_B_SKU_000312,SKU_000312,SE,2025-01-01,LIVE,630.34,SEK,15,valid
2,CH_A,CH_A_SKU_000531,SKU_000531,SE,2025-01-01,LIVE,215.06,SEK,2,valid
3,CH_B,CH_B_SKU_000531,SKU_000531,FR,2025-01-01,LIVE,13.43,EUR,7,valid
4,CH_B,CH_B_SKU_000937,SKU_000937,DE,2025-01-01,LIVE,16.31,EUR,11,valid

## Build Silver order and order-line tables

Order headers and order lines are standardised separately, then checked against each other.

The final reconciliation compares the order-header merchandise value with the sum of the related order-line values.

In [107]:
# Load and standardise the raw order-header export

raw_order_headers = raw_tables[
    "order_header_export"
].copy()

order_status_map = {
    "COMPLETED": "delivered",
    "DISPATCHED": "shipped",
    "OPEN": "pending",
    "CANCELLED": "cancelled",
    "RETURNED": "returned",
    "REFUNDED": "refunded"
}

silver_order_header = pd.DataFrame()

silver_order_header["source_row_number"] = (
    raw_order_headers.index + 1
)

silver_order_header["order_id"] = (
    raw_order_headers["source_order_id"]
    .astype("string")
    .str.strip()
)

silver_order_header["source_partner_code"] = (
    raw_order_headers["source_partner_code"]
    .astype("string")
    .str.strip()
    .str.upper()
)

silver_order_header["partner_id"] = (
    silver_order_header["source_partner_code"]
    .map(partner_code_map)
)

silver_order_header["source_market"] = (
    raw_order_headers["source_market"]
    .astype("string")
    .str.strip()
    .str.upper()
)

silver_order_header["country_code"] = (
    silver_order_header["source_market"]
    .map(country_alias_map)
)

silver_order_header["order_timestamp"] = (
    parse_mixed_datetime(
        raw_order_headers["source_created_at"]
    )
)

silver_order_header["order_status"] = (
    raw_order_headers["source_status"]
    .astype("string")
    .str.strip()
    .str.upper()
    .map(order_status_map)
)

silver_order_header["currency_code"] = [
    standardise_currency(
        currency_value,
        country_code
    )
    for currency_value, country_code in zip(
        raw_order_headers["source_currency"],
        silver_order_header["country_code"]
    )
]

silver_order_header["item_amount"] = (
    parse_mixed_number(
        raw_order_headers["source_item_amount"]
    )
)

silver_order_header["shipping_amount"] = (
    parse_mixed_number(
        raw_order_headers["source_shipping_amount"]
    )
)

silver_order_header["discount_amount"] = (
    parse_mixed_number(
        raw_order_headers["source_discount_amount"]
    )
)

silver_order_header["tax_amount"] = (
    parse_mixed_number(
        raw_order_headers["source_tax_amount"]
    )
)

silver_order_header["source_file"] = (
    raw_order_headers["source_file"]
)

silver_order_header["ingested_at"] = (
    parse_mixed_datetime(
        raw_order_headers["ingested_at"]
    )
)

silver_order_header["order_gross_amount"] = (
    silver_order_header["item_amount"]
    - silver_order_header["discount_amount"].fillna(0)
    + silver_order_header["shipping_amount"].fillna(0)
).round(2)

print("Order headers standardised.")
display(silver_order_header.head())

Order headers standardised.

,source_row_number,order_id,source_partner_code,partner_id,source_market,country_code,order_timestamp,order_status,currency_code,item_amount,shipping_amount,discount_amount,tax_amount,source_file,ingested_at,order_gross_amount
0,1,ORD-000000001,CH_A,CH_A,DE,DE,2025-10-06 19:19:09,delivered,EUR,26.75,5.99,0.0,5.08,orders_CH_A_20251006.csv,2025-10-07 03:19:09,32.74
1,2,ORD-000000002,CH_A,CH_A,UK,GB,2026-03-02 09:37:57,cancelled,GBP,45.17,5.99,0.0,9.03,orders_CH_A_20260302.csv,2026-03-02 23:37:57,51.16
2,3,ORD-000000003,CH_C,CH_C,IT,IT,2025-08-29 05:46:06,delivered,EUR,64.79,3.99,0.0,14.25,orders_CH_C_20250829.csv,2025-08-29 23:46:06,68.78
3,4,ORD-000000004,CH_C,CH_C,ESP,ES,2025-03-21 07:05:28,delivered,EUR,85.95,3.99,6.77,16.63,orders_CH_C_20250321.csv,2025-03-22 15:05:28,83.17
4,5,ORD-000000005,CH_A,CH_A,DE,DE,2025-09-29 15:38:00,delivered,EUR,40.79,5.99,0.0,7.75,orders_CH_A_20250929.csv,2025-09-30 09:38:34,46.78

In [108]:
# Apply data-quality rules to order headers

silver_order_header["possible_duplicate_order"] = (
    silver_order_header["order_id"]
    .duplicated(keep=False)
)

order_header_reason_rows = []

for _, row in silver_order_header.iterrows():
    reasons = []

    if (
        pd.isna(row["order_id"])
        or str(row["order_id"]).strip() == ""
    ):
        reasons.append("missing_order_id")

    if pd.isna(row["partner_id"]):
        reasons.append("unrecognised_partner")

    if pd.isna(row["country_code"]):
        reasons.append("unrecognised_country")

    if pd.isna(row["order_timestamp"]):
        reasons.append("invalid_order_timestamp")

    if pd.isna(row["order_status"]):
        reasons.append("unrecognised_order_status")

    if (
        pd.isna(row["item_amount"])
        or row["item_amount"] < 0
    ):
        reasons.append("invalid_item_amount")

    if (
        pd.notna(row["shipping_amount"])
        and row["shipping_amount"] < 0
    ):
        reasons.append("negative_shipping_amount")

    if (
        pd.notna(row["discount_amount"])
        and row["discount_amount"] < 0
    ):
        reasons.append("negative_discount_amount")

    if (
        pd.notna(row["tax_amount"])
        and row["tax_amount"] < 0
    ):
        reasons.append("negative_tax_amount")

    if row["possible_duplicate_order"]:
        reasons.append("possible_duplicate_order")

    order_header_reason_rows.append(
        "; ".join(reasons)
        if reasons
        else pd.NA
    )

silver_order_header["quality_reasons"] = (
    order_header_reason_rows
)

critical_order_header_reasons = [
    "missing_order_id",
    "unrecognised_partner",
    "unrecognised_country",
    "invalid_order_timestamp",
    "unrecognised_order_status",
    "invalid_item_amount"
]

review_order_header_reasons = [
    "negative_shipping_amount",
    "negative_discount_amount",
    "negative_tax_amount",
    "possible_duplicate_order"
]

silver_order_header["record_status"] = "valid"

for reason in critical_order_header_reasons:
    silver_order_header.loc[
        silver_order_header["quality_reasons"]
        .fillna("")
        .str.contains(reason, regex=False),
        "record_status"
    ] = "quarantine"

for reason in review_order_header_reasons:
    review_mask = (
        silver_order_header["quality_reasons"]
        .fillna("")
        .str.contains(reason, regex=False)
        & (
            silver_order_header["record_status"]
            == "valid"
        )
    )

    silver_order_header.loc[
        review_mask,
        "record_status"
    ] = "review"

silver_order_header["analysis_included"] = (
    silver_order_header["record_status"]
    != "quarantine"
)

print("Order-header records by status:")
display(
    silver_order_header["record_status"]
    .value_counts()
    .to_frame("record_count")
)

Order-header records by status:

               record_count
record_status
valid                 74557
quarantine              443

In [109]:
# Load and standardise the raw order-line export

raw_order_lines = raw_tables[
    "order_line_export"
].copy()

silver_order_line = pd.DataFrame()

silver_order_line["source_row_number"] = (
    raw_order_lines.index + 1
)

silver_order_line["order_id"] = (
    raw_order_lines["source_order_id"]
    .astype("string")
    .str.strip()
)

silver_order_line["line_id"] = (
    raw_order_lines["source_line_id"]
    .astype("string")
    .str.strip()
)

silver_order_line["source_partner_code"] = (
    raw_order_lines["source_partner_code"]
    .astype("string")
    .str.strip()
    .str.upper()
)

silver_order_line["partner_id"] = (
    silver_order_line["source_partner_code"]
    .map(partner_code_map)
)

silver_order_line["source_item_code"] = (
    raw_order_lines["source_item_code"]
    .astype("string")
    .str.strip()
)

silver_order_line["quantity"] = (
    parse_mixed_number(
        raw_order_lines["source_quantity"]
    )
)

silver_order_line["unit_price"] = (
    parse_mixed_number(
        raw_order_lines["source_unit_price"]
    )
)

silver_order_line["line_discount"] = (
    parse_mixed_number(
        raw_order_lines["source_line_discount"]
    )
    .fillna(0)
)

silver_order_line["currency_code"] = (
    raw_order_lines["source_currency"]
    .astype("string")
    .str.strip()
    .map({
        "GBP": "GBP",
        "£": "GBP",
        "Pound Sterling": "GBP",
        "EUR": "EUR",
        "€": "EUR",
        "Euro": "EUR",
        "SEK": "SEK",
        "kr": "SEK",
        "Swedish Krona": "SEK",
        "DKK": "DKK",
        "Danish Krone": "DKK"
    })
)

silver_order_line["source_file"] = (
    raw_order_lines["source_file"]
)

silver_order_line["ingested_at"] = (
    parse_mixed_datetime(
        raw_order_lines["ingested_at"]
    )
)

# Recalculate the line's gross and net merchandise amounts
silver_order_line["line_gross_amount"] = (
    silver_order_line["quantity"]
    * silver_order_line["unit_price"]
).round(2)

silver_order_line["line_net_amount"] = (
    silver_order_line["line_gross_amount"]
    - silver_order_line["line_discount"]
).round(2)

# Map partner item codes to internal products
silver_order_line = silver_order_line.merge(
    mapping_lookup.rename(
        columns={
            "partner_sku": "source_item_code"
        }
    ),
    on=[
        "partner_id",
        "source_item_code"
    ],
    how="left"
)

print("Order lines standardised.")
display(silver_order_line.head())

Order lines standardised.

,source_row_number,order_id,line_id,source_partner_code,partner_id,source_item_code,quantity,unit_price,line_discount,currency_code,source_file,ingested_at,line_gross_amount,line_net_amount,internal_sku
0,1,ORD-000000001,ORD-000000001-L01,CH_A,CH_A,CH_A_SKU_000409,1,11.08,0.0,EUR,order_lines_CH_A_20251006.csv,2025-10-07 08:19:09,11.08,11.08,SKU_000409
1,2,ORD-000000001,ORD-000000001-L02,CH_A,CH_A,CH_A_SKU_002677,1,6.99,0.0,EUR,order_lines_CH_A_20251006.csv,2025-10-07 11:19:09,6.99,6.99,SKU_002677
2,3,ORD-000000001,ORD-000000001-L03,CH_A,CH_A,CH_A_SKU_001513,1,8.68,0.0,EUR,order_lines_CH_A_20251006.csv,2025-10-07 10:19:09,8.68,8.68,SKU_001513
3,4,ORD-000000002,ORD-000000002-L01,CH_A,CH_A,CH_A_SKU_000682,1,7.14,0.0,GBP,order_lines_CH_A_20260302.csv,2026-03-03 03:37:57,7.14,7.14,SKU_000682
4,5,ORD-000000002,ORD-000000002-L02,CH_A,CH_A,CH_A_SKU_001248,3,7.27,0.0,GBP,order_lines_CH_A_20260302.csv,2026-03-03 08:37:57,21.81,21.81,SKU_001248

In [110]:
# Apply data-quality rules to order lines

silver_order_line["possible_duplicate_line"] = (
    silver_order_line["line_id"]
    .duplicated(keep=False)
)

order_line_reason_rows = []

for _, row in silver_order_line.iterrows():
    reasons = []

    if (
        pd.isna(row["order_id"])
        or str(row["order_id"]).strip() == ""
    ):
        reasons.append("missing_order_id")

    if (
        pd.isna(row["line_id"])
        or str(row["line_id"]).strip() == ""
    ):
        reasons.append("missing_line_id")

    if pd.isna(row["partner_id"]):
        reasons.append("unrecognised_partner")

    if (
        pd.isna(row["source_item_code"])
        or str(row["source_item_code"]).strip() == ""
    ):
        reasons.append("missing_item_code")

    if pd.isna(row["internal_sku"]):
        reasons.append("unmapped_partner_sku")

    if (
        pd.isna(row["quantity"])
        or row["quantity"] <= 0
    ):
        reasons.append("invalid_quantity")

    if (
        pd.isna(row["unit_price"])
        or row["unit_price"] < 0
    ):
        reasons.append("invalid_unit_price")

    if (
        pd.notna(row["line_discount"])
        and row["line_discount"] < 0
    ):
        reasons.append("negative_line_discount")

    if row["possible_duplicate_line"]:
        reasons.append("possible_duplicate_line")

    order_line_reason_rows.append(
        "; ".join(reasons)
        if reasons
        else pd.NA
    )

silver_order_line["quality_reasons"] = (
    order_line_reason_rows
)

critical_order_line_reasons = [
    "missing_order_id",
    "missing_line_id",
    "unrecognised_partner",
    "missing_item_code",
    "unmapped_partner_sku",
    "invalid_quantity",
    "invalid_unit_price"
]

review_order_line_reasons = [
    "negative_line_discount",
    "possible_duplicate_line"
]

silver_order_line["record_status"] = "valid"

for reason in critical_order_line_reasons:
    silver_order_line.loc[
        silver_order_line["quality_reasons"]
        .fillna("")
        .str.contains(reason, regex=False),
        "record_status"
    ] = "quarantine"

for reason in review_order_line_reasons:
    review_mask = (
        silver_order_line["quality_reasons"]
        .fillna("")
        .str.contains(reason, regex=False)
        & (
            silver_order_line["record_status"]
            == "valid"
        )
    )

    silver_order_line.loc[
        review_mask,
        "record_status"
    ] = "review"

silver_order_line["analysis_included"] = (
    silver_order_line["record_status"]
    != "quarantine"
)

print("Order-line records by status:")
display(
    silver_order_line["record_status"]
    .value_counts()
    .to_frame("record_count")
)

Order-line records by status:

               record_count
record_status
valid                130522

In [111]:
# Validate the relationship between order headers and order lines

valid_order_ids = set(
    silver_order_header.loc[
        silver_order_header["analysis_included"],
        "order_id"
    ]
    .dropna()
)

silver_order_line["orphan_order_flag"] = (
    ~silver_order_line["order_id"]
    .isin(valid_order_ids)
)

silver_order_line.loc[
    silver_order_line["orphan_order_flag"],
    "record_status"
] = "quarantine"

silver_order_line.loc[
    silver_order_line["orphan_order_flag"],
    "analysis_included"
] = False

orders_with_lines = set(
    silver_order_line.loc[
        silver_order_line["analysis_included"],
        "order_id"
    ]
    .dropna()
)

silver_order_header["missing_line_flag"] = (
    silver_order_header["analysis_included"]
    & ~silver_order_header["order_id"]
    .isin(orders_with_lines)
)

print(
    "Orphan order lines:",
    int(silver_order_line["orphan_order_flag"].sum())
)

print(
    "Orders without valid lines:",
    int(silver_order_header["missing_line_flag"].sum())
)

Orphan order lines: 764
Orders without valid lines: 0

In [112]:
# Reconcile header merchandise amounts to line-level amounts

valid_lines = silver_order_line[
    silver_order_line["analysis_included"]
].copy()

line_totals = (
    valid_lines
    .groupby("order_id", as_index=False)
    .agg(
        line_gross_amount=("line_gross_amount", "sum"),
        line_discount=("line_discount", "sum"),
        line_net_amount=("line_net_amount", "sum"),
        line_count=("line_id", "nunique")
    )
)

order_reconciliation = (
    silver_order_header[
        silver_order_header["analysis_included"]
    ][
        [
            "order_id",
            "item_amount",
            "discount_amount",
            "order_status",
            "partner_id",
            "country_code"
        ]
    ]
    .merge(
        line_totals,
        on="order_id",
        how="left"
    )
)

order_reconciliation["expected_net_merchandise"] = (
    order_reconciliation["item_amount"]
    - order_reconciliation["discount_amount"].fillna(0)
).round(2)

order_reconciliation["line_net_variance"] = (
    order_reconciliation["line_net_amount"]
    - order_reconciliation["expected_net_merchandise"]
).round(2)

order_reconciliation["reconciliation_status"] = np.select(
    [
        order_reconciliation["line_count"].isna(),
        order_reconciliation["line_net_variance"].abs() <= 0.05,
        order_reconciliation["line_net_variance"].abs() <= 1.00
    ],
    [
        "missing_lines",
        "within_tolerance",
        "minor_variance"
    ],
    default="investigate"
)

print("Order reconciliation statuses:")
display(
    order_reconciliation[
        "reconciliation_status"
    ]
    .value_counts()
    .to_frame("order_count")
)

Order reconciliation statuses:

                       order_count
reconciliation_status
within_tolerance             73941
investigate                    468
minor_variance                 148

In [113]:
# Save Silver order tables and reconciliation outputs

silver_order_header_path = (
    PROCESSED_DIR / "silver_order_header.csv"
)

silver_order_line_path = (
    PROCESSED_DIR / "silver_order_line.csv"
)

quarantine_order_header_path = (
    PROCESSED_DIR / "quarantine_order_header.csv"
)

quarantine_order_line_path = (
    PROCESSED_DIR / "quarantine_order_line.csv"
)

order_reconciliation_path = (
    PROCESSED_DIR / "order_line_reconciliation.csv"
)

silver_order_header.to_csv(
    silver_order_header_path,
    index=False
)

silver_order_line.to_csv(
    silver_order_line_path,
    index=False
)

silver_order_header[
    silver_order_header["record_status"] == "quarantine"
].to_csv(
    quarantine_order_header_path,
    index=False
)

silver_order_line[
    silver_order_line["record_status"] == "quarantine"
].to_csv(
    quarantine_order_line_path,
    index=False
)

order_reconciliation.to_csv(
    order_reconciliation_path,
    index=False
)

print("Order-processing outputs saved:")
print(f" - {silver_order_header_path}")
print(f" - {silver_order_line_path}")
print(f" - {quarantine_order_header_path}")
print(f" - {quarantine_order_line_path}")
print(f" - {order_reconciliation_path}")

Order-processing outputs saved:
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/silver_order_header.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/silver_order_line.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/quarantine_order_header.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/quarantine_order_line.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/order_line_reconciliation.csv

In [114]:
# Review the order-processing outputs

print("Order-header shape:", silver_order_header.shape)
print("Order-line shape:", silver_order_line.shape)
print("Reconciliation shape:", order_reconciliation.shape)

print("\nOrder-header record statuses:")
display(
    silver_order_header["record_status"]
    .value_counts()
    .to_frame("record_count")
)

print("\nOrder-line record statuses:")
display(
    silver_order_line["record_status"]
    .value_counts()
    .to_frame("record_count")
)

print("\nReconciliation statuses:")
display(
    order_reconciliation[
        "reconciliation_status"
    ]
    .value_counts()
    .to_frame("order_count")
)

print("\nExample reconciliation records:")
display(
    order_reconciliation[
        [
            "order_id",
            "item_amount",
            "discount_amount",
            "line_net_amount",
            "expected_net_merchandise",
            "line_net_variance",
            "reconciliation_status"
        ]
    ]
    .head()
)

Order-header shape: (75000, 21)
Order-line shape: (130522, 20)
Reconciliation shape: (74557, 13)

Order-header record statuses:

               record_count
record_status
valid                 74557
quarantine              443

Order-line record statuses:

               record_count
record_status
valid                129758
quarantine              764

Reconciliation statuses:

                       order_count
reconciliation_status
within_tolerance             73941
investigate                    468
minor_variance                 148

Example reconciliation records:

,order_id,item_amount,discount_amount,line_net_amount,expected_net_merchandise,line_net_variance,reconciliation_status
0,ORD-000000001,26.75,0.0,26.75,26.75,0.0,within_tolerance
1,ORD-000000002,45.17,0.0,45.19,45.17,0.02,within_tolerance
2,ORD-000000003,64.79,0.0,64.8,64.79,0.01,within_tolerance
3,ORD-000000004,85.95,6.77,79.19,79.18,0.01,within_tolerance
4,ORD-000000005,40.79,0.0,40.8,40.79,0.01,within_tolerance

## Build Silver shipment and return tables

Shipment events and returns are standardised and checked against valid order-line identifiers.

Missing tracking information is treated differently from an invalid order relationship. The workflow preserves operational exceptions for investigation.

In [116]:
# Load and standardise shipment events

raw_shipments = raw_tables[
    "shipment_event_export"
].copy()

shipment_event_map = {
    "ACCEPTED": "accepted",
    "SHIPPED": "shipped",
    "DELIVERED": "delivered",
    "DELIVERY_EXCEPTION": "delivery_exception"
}

silver_shipment_event = pd.DataFrame()

silver_shipment_event["source_row_number"] = (
    raw_shipments.index + 1
)

silver_shipment_event["order_id"] = (
    raw_shipments["external_order_id"]
    .astype("string")
    .str.strip()
)

silver_shipment_event["line_id"] = (
    raw_shipments["line_ref"]
    .astype("string")
    .str.strip()
)

silver_shipment_event["event_type"] = (
    raw_shipments["event"]
    .astype("string")
    .str.strip()
    .str.upper()
    .map(shipment_event_map)
)

silver_shipment_event["carrier_code"] = (
    raw_shipments["carrier"]
    .astype("string")
    .str.strip()
    .str.upper()
)

silver_shipment_event["tracking_reference"] = (
    raw_shipments["tracking_number"]
    .astype("string")
    .str.strip()
)

silver_shipment_event["fulfilment_market"] = (
    raw_shipments["fulfilment_market"]
    .astype("string")
    .str.strip()
    .str.upper()
)

silver_shipment_event["fulfilment_country"] = (
    silver_shipment_event["fulfilment_market"]
    .map(country_alias_map)
)

silver_shipment_event["event_timestamp"] = (
    parse_mixed_datetime(
        raw_shipments["event_time"]
    )
)

silver_shipment_event["promised_delivery_date"] = (
    parse_mixed_datetime(
        raw_shipments["promised_date"]
    )
    .dt.normalize()
)

silver_shipment_event["source_file"] = (
    raw_shipments["source_file"]
)

silver_shipment_event["ingested_at"] = (
    parse_mixed_datetime(
        raw_shipments["ingested_at"]
    )
)

print("Shipment events standardised.")
display(silver_shipment_event.head())

Shipment events standardised.

,source_row_number,order_id,line_id,event_type,carrier_code,tracking_reference,fulfilment_market,fulfilment_country,event_timestamp,promised_delivery_date,source_file,ingested_at
0,1,ORD-000000001,ORD-000000001-L01,accepted,CAR_C,<NA>,DE,DE,2025-10-08 12:19:09,2025-10-13,shipment_events_20251008.csv,2025-10-08 21:19:09
1,2,ORD-000000001,ORD-000000001-L02,accepted,CAR_C,<NA>,DE,DE,2025-10-06 23:19:09,2025-10-14,shipment_events_20251006.csv,2025-10-07 11:19:09
2,3,ORD-000000001,ORD-000000001-L03,accepted,CAR_A,<NA>,DE,DE,2025-10-06 23:19:09,2025-10-11,shipment_events_20251006.csv,2025-10-08 07:19:09
3,4,ORD-000000003,ORD-000000003-L01,accepted,CAR_B,<NA>,IT,IT,2025-08-30 06:46:06,2025-09-01,shipment_events_20250830.csv,2025-08-30 10:46:06
4,5,ORD-000000004,ORD-000000004-L01,accepted,CAR_B,<NA>,ESP,ES,2025-03-21 22:05:28,2025-03-29,shipment_events_20250321.csv,2025-03-22 06:05:28

In [117]:
# Apply data-quality rules to shipment events

valid_line_ids = set(
    silver_order_line.loc[
        silver_order_line["analysis_included"],
        "line_id"
    ]
    .dropna()
)

silver_shipment_event["orphan_line_flag"] = (
    ~silver_shipment_event["line_id"]
    .isin(valid_line_ids)
)

silver_shipment_event["shipment_business_key"] = (
    silver_shipment_event["order_id"].astype("string")
    + "|"
    + silver_shipment_event["line_id"].astype("string")
    + "|"
    + silver_shipment_event["event_type"].astype("string")
    + "|"
    + silver_shipment_event["event_timestamp"].astype("string")
)

silver_shipment_event["possible_duplicate_event"] = (
    silver_shipment_event["shipment_business_key"]
    .duplicated(keep=False)
)

shipment_reason_rows = []

for _, row in silver_shipment_event.iterrows():
    reasons = []

    if (
        pd.isna(row["order_id"])
        or str(row["order_id"]).strip() == ""
    ):
        reasons.append("missing_order_id")

    if (
        pd.isna(row["line_id"])
        or str(row["line_id"]).strip() == ""
    ):
        reasons.append("missing_line_id")

    if pd.isna(row["event_type"]):
        reasons.append("unrecognised_event_type")

    if pd.isna(row["event_timestamp"]):
        reasons.append("invalid_event_timestamp")

    if pd.isna(row["fulfilment_country"]):
        reasons.append("unrecognised_fulfilment_country")

    if row["orphan_line_flag"]:
        reasons.append("orphan_order_line")

    if row["possible_duplicate_event"]:
        reasons.append("possible_duplicate_event")

    shipment_reason_rows.append(
        "; ".join(reasons)
        if reasons
        else pd.NA
    )

silver_shipment_event["quality_reasons"] = (
    shipment_reason_rows
)

critical_shipment_reasons = [
    "missing_order_id",
    "missing_line_id",
    "unrecognised_event_type",
    "invalid_event_timestamp",
    "orphan_order_line"
]

review_shipment_reasons = [
    "unrecognised_fulfilment_country",
    "possible_duplicate_event"
]

silver_shipment_event["record_status"] = "valid"

for reason in critical_shipment_reasons:
    silver_shipment_event.loc[
        silver_shipment_event["quality_reasons"]
        .fillna("")
        .str.contains(reason, regex=False),
        "record_status"
    ] = "quarantine"

for reason in review_shipment_reasons:
    review_mask = (
        silver_shipment_event["quality_reasons"]
        .fillna("")
        .str.contains(reason, regex=False)
        & (
            silver_shipment_event["record_status"]
            == "valid"
        )
    )

    silver_shipment_event.loc[
        review_mask,
        "record_status"
    ] = "review"

silver_shipment_event["analysis_included"] = (
    silver_shipment_event["record_status"]
    != "quarantine"
)

print("Shipment-event records by status:")
display(
    silver_shipment_event["record_status"]
    .value_counts()
    .to_frame("record_count")
)

Shipment-event records by status:

               record_count
record_status
valid                336926
quarantine             1978

In [118]:
# Load and standardise return cases

raw_returns = raw_tables[
    "return_case_export"
].copy()

return_status_map = {
    "requested": "requested",
    "in_transit": "in_transit",
    "received": "received",
    "refunded": "refunded",
    "rejected": "rejected"
}

return_disposition_map = {
    "resalable": "resalable",
    "discounted_resale": "discounted_resale",
    "damaged": "damaged",
    "supplier_review": "supplier_review",
    "written_off": "written_off"
}

silver_return_case = pd.DataFrame()

silver_return_case["source_row_number"] = (
    raw_returns.index + 1
)

silver_return_case["return_id"] = (
    raw_returns["return_id"]
    .astype("string")
    .str.strip()
)

silver_return_case["order_id"] = (
    raw_returns["external_order_id"]
    .astype("string")
    .str.strip()
)

silver_return_case["line_id"] = (
    raw_returns["line_ref"]
    .astype("string")
    .str.strip()
)

silver_return_case["source_partner_code"] = (
    raw_returns["partner_code"]
    .astype("string")
    .str.strip()
    .str.upper()
)

silver_return_case["partner_id"] = (
    silver_return_case["source_partner_code"]
    .map(partner_code_map)
)

silver_return_case["source_market"] = (
    raw_returns["market"]
    .astype("string")
    .str.strip()
    .str.upper()
)

silver_return_case["country_code"] = (
    silver_return_case["source_market"]
    .map(country_alias_map)
)

silver_return_case["return_reason"] = (
    raw_returns["reason"]
    .astype("string")
    .str.strip()
    .str.lower()
)

silver_return_case["return_status"] = (
    raw_returns["status"]
    .astype("string")
    .str.strip()
    .str.lower()
    .map(return_status_map)
)

silver_return_case["disposition"] = (
    raw_returns["disposition"]
    .astype("string")
    .str.strip()
    .str.lower()
    .map(return_disposition_map)
)

silver_return_case["requested_at"] = (
    parse_mixed_datetime(
        raw_returns["requested_at"]
    )
)

silver_return_case["received_at"] = (
    parse_mixed_datetime(
        raw_returns["received_at"]
    )
)

silver_return_case["refund_amount"] = (
    parse_mixed_number(
        raw_returns["refund_amount"]
    )
)

silver_return_case["currency_code"] = [
    standardise_currency(
        currency_value,
        country_code
    )
    for currency_value, country_code in zip(
        raw_returns["currency"],
        silver_return_case["country_code"]
    )
]

silver_return_case["source_file"] = (
    raw_returns["source_file"]
)

silver_return_case["ingested_at"] = (
    parse_mixed_datetime(
        raw_returns["ingested_at"]
    )
)

print("Return cases standardised.")
display(silver_return_case.head())

Return cases standardised.

,source_row_number,return_id,order_id,line_id,source_partner_code,partner_id,source_market,country_code,return_reason,return_status,disposition,requested_at,received_at,refund_amount,currency_code,source_file,ingested_at
0,1,RET-000000001,ORD-000000007,ORD-000000007-L01,CH_D,CH_D,SWE,SE,size_or_fit,refunded,resalable,2025-07-02,2025-07-08 00:00:00,51.97,SEK,returns_CH_D_20250702.csv,2025-07-10 08:23:19
1,2,RET-000000002,ORD-000000008,ORD-000000008-L02,CH_A,CH_A,DE,DE,size_or_fit,rejected,supplier_review,2025-08-15,2025-08-17 00:00:00,17.37,EUR,returns_CH_A_20250815.csv,2025-08-19 19:30:04
2,3,RET-000000003,ORD-000000009,ORD-000000009-L02,CH_A,CH_A,UK,GB,damaged_in_transit,in_transit,resalable,2026-01-02,2026-01-12 00:00:00,3.53,GBP,returns_CH_A_20260102.csv,2026-01-14 15:48:33
3,4,RET-000000004,ORD-000000010,ORD-000000010-L01,CH_B,CH_B,DE,DE,wrong_item,refunded,discounted_resale,2026-06-11,2026-06-28 20:53:17,17.6,EUR,returns_CH_B_20260611.csv,2026-06-30 11:53:17
4,5,RET-000000005,ORD-000000016,ORD-000000016-L01,CH_B,CH_B,NLD,NL,changed_mind,refunded,resalable,2025-04-17,2025-04-25 00:00:00,134.46,EUR,returns_CH_B_20250417.csv,2025-04-27 22:50:42

In [119]:
# Apply data-quality rules to return cases

valid_order_line_keys = set(
    zip(
        silver_order_line.loc[
            silver_order_line["analysis_included"],
            "order_id"
        ],
        silver_order_line.loc[
            silver_order_line["analysis_included"],
            "line_id"
        ]
    )
)

silver_return_case["orphan_line_flag"] = [
    (order_id, line_id)
    not in valid_order_line_keys
    for order_id, line_id in zip(
        silver_return_case["order_id"],
        silver_return_case["line_id"]
    )
]

silver_return_case["possible_duplicate_return"] = (
    silver_return_case["return_id"]
    .duplicated(keep=False)
)

return_reason_rows = []

for _, row in silver_return_case.iterrows():
    reasons = []

    if (
        pd.isna(row["return_id"])
        or str(row["return_id"]).strip() == ""
    ):
        reasons.append("missing_return_id")

    if (
        pd.isna(row["order_id"])
        or str(row["order_id"]).strip() == ""
    ):
        reasons.append("missing_order_id")

    if (
        pd.isna(row["line_id"])
        or str(row["line_id"]).strip() == ""
    ):
        reasons.append("missing_line_id")

    if pd.isna(row["partner_id"]):
        reasons.append("unrecognised_partner")

    if pd.isna(row["country_code"]):
        reasons.append("unrecognised_country")

    if pd.isna(row["return_status"]):
        reasons.append("unrecognised_return_status")

    if pd.isna(row["requested_at"]):
        reasons.append("invalid_requested_date")

    if (
        pd.notna(row["refund_amount"])
        and row["refund_amount"] < 0
    ):
        reasons.append("negative_refund_amount")

    if row["orphan_line_flag"]:
        reasons.append("orphan_order_line")

    if row["possible_duplicate_return"]:
        reasons.append("possible_duplicate_return")

    return_reason_rows.append(
        "; ".join(reasons)
        if reasons
        else pd.NA
    )

silver_return_case["quality_reasons"] = (
    return_reason_rows
)

critical_return_reasons = [
    "missing_return_id",
    "missing_order_id",
    "missing_line_id",
    "unrecognised_partner",
    "unrecognised_country",
    "unrecognised_return_status",
    "invalid_requested_date",
    "negative_refund_amount",
    "orphan_order_line"
]

review_return_reasons = [
    "possible_duplicate_return",
    "missing_received_date"
]

silver_return_case["record_status"] = "valid"

for reason in critical_return_reasons:
    silver_return_case.loc[
        silver_return_case["quality_reasons"]
        .fillna("")
        .str.contains(reason, regex=False),
        "record_status"
    ] = "quarantine"

# Missing received dates are valid for returns still in progress,
# so classify them as review rather than quarantine.
silver_return_case.loc[
    silver_return_case["received_at"].isna()
    & (
        silver_return_case["record_status"]
        == "valid"
    ),
    "record_status"
] = "review"

for reason in review_return_reasons:
    review_mask = (
        silver_return_case["quality_reasons"]
        .fillna("")
        .str.contains(reason, regex=False)
        & (
            silver_return_case["record_status"]
            == "valid"
        )
    )

    silver_return_case.loc[
        review_mask,
        "record_status"
    ] = "review"

silver_return_case["analysis_included"] = (
    silver_return_case["record_status"]
    != "quarantine"
)

print("Return records by status:")
display(
    silver_return_case["record_status"]
    .value_counts()
    .to_frame("record_count")
)

Return records by status:

               record_count
record_status
valid                 24570
review                  282
quarantine              111

In [120]:
# Save the Silver shipment and return tables

silver_shipment_path = (
    PROCESSED_DIR / "silver_shipment_event.csv"
)

quarantine_shipment_path = (
    PROCESSED_DIR / "quarantine_shipment_event.csv"
)

silver_return_path = (
    PROCESSED_DIR / "silver_return_case.csv"
)

quarantine_return_path = (
    PROCESSED_DIR / "quarantine_return_case.csv"
)

silver_shipment_event.to_csv(
    silver_shipment_path,
    index=False
)

silver_shipment_event[
    silver_shipment_event["record_status"] == "quarantine"
].to_csv(
    quarantine_shipment_path,
    index=False
)

silver_return_case.to_csv(
    silver_return_path,
    index=False
)

silver_return_case[
    silver_return_case["record_status"] == "quarantine"
].to_csv(
    quarantine_return_path,
    index=False
)

print("Shipment and return outputs saved:")
print(f" - {silver_shipment_path}")
print(f" - {quarantine_shipment_path}")
print(f" - {silver_return_path}")
print(f" - {quarantine_return_path}")

Shipment and return outputs saved:
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/silver_shipment_event.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/quarantine_shipment_event.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/silver_return_case.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/quarantine_return_case.csv

In [121]:
# Review shipment and return relationships

print("Shipment-event shape:", silver_shipment_event.shape)
print("Return-case shape:", silver_return_case.shape)

print("\nShipment event types:")
display(
    silver_shipment_event["event_type"]
    .value_counts()
    .to_frame("event_count")
)

print("\nShipment statuses:")
display(
    silver_shipment_event["record_status"]
    .value_counts()
    .to_frame("record_count")
)

print("\nReturn statuses:")
display(
    silver_return_case["return_status"]
    .value_counts()
    .to_frame("return_count")
)

print("\nReturn dispositions:")
display(
    silver_return_case["disposition"]
    .value_counts()
    .to_frame("return_count")
)

print("\nReturns with missing received dates:")
print(
    int(
        silver_return_case["received_at"]
        .isna()
        .sum()
    )
)

Shipment-event shape: (338904, 18)
Return-case shape: (24963, 22)

Shipment event types:

                    event_count
event_type
accepted                 123523
shipped                  111230
delivered                100273
delivery_exception         3878

Shipment statuses:

               record_count
record_status
valid                336926
quarantine             1978

Return statuses:

               return_count
return_status
refunded              16030
received               3485
in_transit             2476
requested              1965
rejected               1007

Return dispositions:

                   return_count
disposition
resalable                 14384
discounted_resale          4343
damaged                    2515
supplier_review            1942
written_off                1779

Returns with missing received dates:
285

## Build Silver settlement, payout, and FX tables

Settlement data is standardised for financial reconciliation.

Order-level settlement references are validated where available. Missing references are retained as unallocated settlement items for investigation.

In [123]:
# Helpers for standardising settlement and payout currencies

partner_base_currency_map = (
    partner_ref
    .set_index("partner_id")["base_currency"]
    .to_dict()
)


def standardise_settlement_currency(
    currency_value,
    partner_id
):
    if pd.isna(currency_value):
        return pd.NA

    value = str(currency_value).strip()

    if value in ["GBP", "£", "Pound Sterling"]:
        return "GBP"

    if value in ["EUR", "€", "Euro"]:
        return "EUR"

    if value in ["SEK", "Swedish Krona"]:
        return "SEK"

    if value in ["DKK", "Danish Krone"]:
        return "DKK"

    # "kr" is ambiguous, so use the partner's base currency.
    if value == "kr":
        return partner_base_currency_map.get(
            partner_id,
            pd.NA
        )

    return pd.NA


settlement_line_type_map = {
    "SALE": "sale",
    "REFUND": "refund",
    "ADJUSTMENT": "adjustment"
}

In [124]:
# Load and standardise settlement lines

raw_settlements = raw_tables[
    "settlement_line_export"
].copy()

silver_settlement_line = pd.DataFrame()

silver_settlement_line["source_row_number"] = (
    raw_settlements.index + 1
)

silver_settlement_line["settlement_line_id"] = (
    raw_settlements["statement_line_id"]
    .astype("string")
    .str.strip()
)

silver_settlement_line["order_reference"] = (
    raw_settlements["order_reference"]
    .astype("string")
    .str.strip()
)

silver_settlement_line["source_partner_code"] = (
    raw_settlements["partner_code"]
    .astype("string")
    .str.strip()
    .str.upper()
)

silver_settlement_line["partner_id"] = (
    silver_settlement_line["source_partner_code"]
    .map(partner_code_map)
)

silver_settlement_line["line_type"] = (
    raw_settlements["line_type"]
    .astype("string")
    .str.strip()
    .str.upper()
    .map(settlement_line_type_map)
)

silver_settlement_line["transaction_date"] = (
    parse_mixed_datetime(
        raw_settlements["transaction_date"]
    )
)

silver_settlement_line["payout_date"] = (
    parse_mixed_datetime(
        raw_settlements["payout_date"]
    )
)

silver_settlement_line["currency_code"] = [
    standardise_settlement_currency(
        currency_value,
        partner_id
    )
    for currency_value, partner_id in zip(
        raw_settlements["currency"],
        silver_settlement_line["partner_id"]
    )
]

for source_column, clean_column in [
    ("gross_amount", "gross_amount"),
    ("platform_fee", "platform_fee"),
    ("payment_fee", "payment_fee"),
    ("tax_withheld", "tax_withheld"),
    ("refund_adjustment", "refund_adjustment"),
    ("manual_adjustment", "manual_adjustment"),
    ("net_amount", "net_amount")
]:
    silver_settlement_line[clean_column] = (
        parse_mixed_number(
            raw_settlements[source_column]
        )
    )

silver_settlement_line["source_file"] = (
    raw_settlements["source_file"]
)

silver_settlement_line["ingested_at"] = (
    parse_mixed_datetime(
        raw_settlements["ingested_at"]
    )
)

print("Settlement lines standardised.")
display(silver_settlement_line.head())

Settlement lines standardised.

,source_row_number,settlement_line_id,order_reference,source_partner_code,partner_id,line_type,transaction_date,payout_date,currency_code,gross_amount,platform_fee,payment_fee,tax_withheld,refund_adjustment,manual_adjustment,net_amount,source_file,ingested_at
0,1,SET-000000001,ORD-000000001,CH_A,CH_A,NaN,2025-10-08 00:00:00,2025-10-29 19:19:09,EUR,32.74,-4.58,-0.62,-5.08,0.0,0.0,22.46,settlement_CH_A_20251029.csv,2025-10-30 01:19:09
1,2,SET-000000002,ORD-000000003,CH_C,CH_C,NaN,2025-08-29 00:00:00,2025-09-09 05:46:06,EUR,68.78,-8.25,-1.78,-14.25,0.0,0.0,44.5,settlement_CH_C_20250909.csv,2025-09-12 04:46:06
2,3,SET-000000003,ORD-000000004,CH_C,CH_C,NaN,2025-03-22 07:05:28,2025-04-11 00:00:00,EUR,83.17,-9.98,-2.21,-16.63,0.0,0.0,54.35,settlement_CH_C_20250411.csv,2025-04-13 10:05:28
3,4,SET-000000004,ORD-000000005,CH_A,CH_A,NaN,2025-09-30 00:00:00,2025-10-17 00:00:00,EUR,46.78,-6.55,-1.11,-7.75,0.0,0.0,31.37,settlement_CH_A_20251017.csv,2025-10-18 18:38:34
4,5,SET-000000005,ORD-000000006,CH_C,CH_C,NaN,2025-05-14 00:00:00,2025-05-23 00:00:00,EUR,115.8,-13.9,-3.32,-22.0,0.0,0.0,76.58,settlement_CH_C_20250523.csv,2025-05-26 03:57:09

In [125]:
# Apply settlement data-quality rules

valid_order_ids = set(
    silver_order_header.loc[
        silver_order_header["analysis_included"],
        "order_id"
    ]
    .dropna()
)

silver_settlement_line["unallocated_order_flag"] = (
    silver_settlement_line["order_reference"].isna()
)

silver_settlement_line["unknown_order_reference_flag"] = (
    silver_settlement_line["order_reference"].notna()
    & ~silver_settlement_line["order_reference"]
    .isin(valid_order_ids)
)

silver_settlement_line["possible_duplicate_line"] = (
    silver_settlement_line["settlement_line_id"]
    .duplicated(keep=False)
)

settlement_reason_rows = []

for _, row in silver_settlement_line.iterrows():
    reasons = []

    if (
        pd.isna(row["settlement_line_id"])
        or str(row["settlement_line_id"]).strip() == ""
    ):
        reasons.append("missing_settlement_line_id")

    if pd.isna(row["partner_id"]):
        reasons.append("unrecognised_partner")

    if pd.isna(row["line_type"]):
        reasons.append("unrecognised_settlement_line_type")

    if pd.isna(row["transaction_date"]):
        reasons.append("invalid_transaction_date")

    if pd.isna(row["payout_date"]):
        reasons.append("invalid_payout_date")

    if pd.isna(row["currency_code"]):
        reasons.append("unrecognised_currency")

    if (
        pd.isna(row["net_amount"])
    ):
        reasons.append("invalid_net_amount")

    if row["unknown_order_reference_flag"]:
        reasons.append("unknown_order_reference")

    if row["unallocated_order_flag"]:
        reasons.append("unallocated_settlement_line")

    if row["possible_duplicate_line"]:
        reasons.append("possible_duplicate_settlement_line")

    settlement_reason_rows.append(
        "; ".join(reasons)
        if reasons
        else pd.NA
    )

silver_settlement_line["quality_reasons"] = (
    settlement_reason_rows
)

critical_settlement_reasons = [
    "missing_settlement_line_id",
    "unrecognised_partner",
    "unrecognised_settlement_line_type",
    "invalid_transaction_date",
    "invalid_payout_date",
    "unrecognised_currency",
    "invalid_net_amount",
    "unknown_order_reference"
]

review_settlement_reasons = [
    "unallocated_settlement_line",
    "possible_duplicate_settlement_line"
]

silver_settlement_line["record_status"] = "valid"

for reason in critical_settlement_reasons:
    silver_settlement_line.loc[
        silver_settlement_line["quality_reasons"]
        .fillna("")
        .str.contains(reason, regex=False),
        "record_status"
    ] = "quarantine"

for reason in review_settlement_reasons:
    review_mask = (
        silver_settlement_line["quality_reasons"]
        .fillna("")
        .str.contains(reason, regex=False)
        & (
            silver_settlement_line["record_status"]
            == "valid"
        )
    )

    silver_settlement_line.loc[
        review_mask,
        "record_status"
    ] = "review"

silver_settlement_line["analysis_included"] = (
    silver_settlement_line["record_status"]
    != "quarantine"
)

print("Settlement records by status:")
display(
    silver_settlement_line["record_status"]
    .value_counts()
    .to_frame("record_count")
)

print("\nUnallocated settlement lines:")
print(
    int(
        silver_settlement_line[
            "unallocated_order_flag"
        ].sum()
    )
)

Settlement records by status:

               record_count
record_status
quarantine            96712

Unallocated settlement lines:
1381

In [126]:
# Load and standardise payout batches

raw_payouts = raw_tables[
    "payout_batch_export"
].copy()

silver_payout_batch = pd.DataFrame()

silver_payout_batch["source_row_number"] = (
    raw_payouts.index + 1
)

silver_payout_batch["payout_id"] = (
    raw_payouts["payout_id"]
    .astype("string")
    .str.strip()
)

silver_payout_batch["source_partner_code"] = (
    raw_payouts["partner_code"]
    .astype("string")
    .str.strip()
    .str.upper()
)

silver_payout_batch["partner_id"] = (
    silver_payout_batch["source_partner_code"]
    .map(partner_code_map)
)

silver_payout_batch["currency_code"] = [
    standardise_settlement_currency(
        currency_value,
        partner_id
    )
    for currency_value, partner_id in zip(
        raw_payouts["currency"],
        silver_payout_batch["partner_id"]
    )
]

silver_payout_batch["payout_date"] = (
    parse_mixed_datetime(
        raw_payouts["payout_date"]
    )
)

silver_payout_batch["payout_amount"] = (
    parse_mixed_number(
        raw_payouts["payout_amount"]
    )
)

silver_payout_batch["statement_line_count"] = (
    parse_mixed_number(
        raw_payouts["statement_line_count"]
    )
)

silver_payout_batch["source_file"] = (
    raw_payouts["source_file"]
)

silver_payout_batch["ingested_at"] = (
    parse_mixed_datetime(
        raw_payouts["ingested_at"]
    )
)

print("Payout batches standardised.")
display(silver_payout_batch.head())

Payout batches standardised.

,source_row_number,payout_id,source_partner_code,partner_id,currency_code,payout_date,payout_amount,statement_line_count,source_file,ingested_at
0,1,PAY-0000001,CH_A,CH_A,EUR,2025-01-10,912.24,25,payout_batches_20250110.csv,2025-01-10 09:00:00
1,2,PAY-0000002,CH_A,CH_A,EUR,2025-01-20,2277.27,75,payout_batches_20250120.csv,2025-01-21 16:00:00
2,3,PAY-0000003,CH_A,CH_A,EUR,2025-01-25,5201.32,164,payout_batches_20250125.csv,2025-01-26 00:00:00
3,4,PAY-0000004,CH_A,CH_A,EUR,2025-01-30,5758.24,179,payout_batches_20250130.csv,2025-01-30 20:00:00
4,5,PAY-0000005,CH_A,CH_A,EUR,2025-02-06,5907.88,207,payout_batches_20250206.csv,2025-02-07 16:00:00

In [127]:
# Apply data-quality rules to payout batches

silver_payout_batch["possible_duplicate_payout"] = (
    silver_payout_batch["payout_id"]
    .duplicated(keep=False)
)

payout_reason_rows = []

for _, row in silver_payout_batch.iterrows():
    reasons = []

    if (
        pd.isna(row["payout_id"])
        or str(row["payout_id"]).strip() == ""
    ):
        reasons.append("missing_payout_id")

    if pd.isna(row["partner_id"]):
        reasons.append("unrecognised_partner")

    if pd.isna(row["currency_code"]):
        reasons.append("unrecognised_currency")

    if pd.isna(row["payout_date"]):
        reasons.append("invalid_payout_date")

    if pd.isna(row["payout_amount"]):
        reasons.append("invalid_payout_amount")

    if row["possible_duplicate_payout"]:
        reasons.append("possible_duplicate_payout")

    payout_reason_rows.append(
        "; ".join(reasons)
        if reasons
        else pd.NA
    )

silver_payout_batch["quality_reasons"] = (
    payout_reason_rows
)

critical_payout_reasons = [
    "missing_payout_id",
    "unrecognised_partner",
    "unrecognised_currency",
    "invalid_payout_date",
    "invalid_payout_amount"
]

review_payout_reasons = [
    "possible_duplicate_payout"
]

silver_payout_batch["record_status"] = "valid"

for reason in critical_payout_reasons:
    silver_payout_batch.loc[
        silver_payout_batch["quality_reasons"]
        .fillna("")
        .str.contains(reason, regex=False),
        "record_status"
    ] = "quarantine"

for reason in review_payout_reasons:
    review_mask = (
        silver_payout_batch["quality_reasons"]
        .fillna("")
        .str.contains(reason, regex=False)
        & (
            silver_payout_batch["record_status"]
            == "valid"
        )
    )

    silver_payout_batch.loc[
        review_mask,
        "record_status"
    ] = "review"

silver_payout_batch["analysis_included"] = (
    silver_payout_batch["record_status"]
    != "quarantine"
)

print("Payout records by status:")
display(
    silver_payout_batch["record_status"]
    .value_counts()
    .to_frame("record_count")
)

Payout records by status:

               record_count
record_status
valid                   595

In [128]:
# Load and standardise synthetic FX rates

raw_fx = raw_tables[
    "fx_daily_rates_export"
].copy()

silver_fx_rate = pd.DataFrame()

silver_fx_rate["source_row_number"] = (
    raw_fx.index + 1
)

silver_fx_rate["rate_date"] = (
    parse_mixed_datetime(
        raw_fx["rate_date"]
    )
    .dt.normalize()
)

silver_fx_rate["from_currency"] = (
    raw_fx["source_currency"]
    .astype("string")
    .str.strip()
    .str.upper()
)

silver_fx_rate["to_currency"] = (
    raw_fx["reporting_currency"]
    .astype("string")
    .str.strip()
    .str.upper()
)

silver_fx_rate["rate_to_gbp"] = (
    parse_mixed_number(
        raw_fx["conversion_rate"]
    )
)

silver_fx_rate["rate_source"] = (
    raw_fx["rate_source"]
    .astype("string")
    .str.strip()
)

silver_fx_rate["source_file"] = (
    raw_fx["source_file"]
)

silver_fx_rate["ingested_at"] = (
    parse_mixed_datetime(
        raw_fx["ingested_at"]
    )
)

silver_fx_rate["possible_duplicate_rate"] = (
    silver_fx_rate[
        [
            "rate_date",
            "from_currency",
            "to_currency"
        ]
    ]
    .duplicated(keep=False)
)

fx_reason_rows = []

for _, row in silver_fx_rate.iterrows():
    reasons = []

    if pd.isna(row["rate_date"]):
        reasons.append("invalid_rate_date")

    if pd.isna(row["from_currency"]):
        reasons.append("missing_source_currency")

    if pd.isna(row["to_currency"]):
        reasons.append("missing_reporting_currency")

    if (
        pd.isna(row["rate_to_gbp"])
        or row["rate_to_gbp"] <= 0
    ):
        reasons.append("invalid_fx_rate")

    if row["possible_duplicate_rate"]:
        reasons.append("possible_duplicate_fx_rate")

    fx_reason_rows.append(
        "; ".join(reasons)
        if reasons
        else pd.NA
    )

silver_fx_rate["quality_reasons"] = (
    fx_reason_rows
)

critical_fx_reasons = [
    "invalid_rate_date",
    "missing_source_currency",
    "missing_reporting_currency",
    "invalid_fx_rate"
]

review_fx_reasons = [
    "possible_duplicate_fx_rate"
]

silver_fx_rate["record_status"] = "valid"

for reason in critical_fx_reasons:
    silver_fx_rate.loc[
        silver_fx_rate["quality_reasons"]
        .fillna("")
        .str.contains(reason, regex=False),
        "record_status"
    ] = "quarantine"

for reason in review_fx_reasons:
    review_mask = (
        silver_fx_rate["quality_reasons"]
        .fillna("")
        .str.contains(reason, regex=False)
        & (
            silver_fx_rate["record_status"]
            == "valid"
        )
    )

    silver_fx_rate.loc[
        review_mask,
        "record_status"
    ] = "review"

silver_fx_rate["analysis_included"] = (
    silver_fx_rate["record_status"]
    != "quarantine"
)

print("FX records by status:")
display(
    silver_fx_rate["record_status"]
    .value_counts()
    .to_frame("record_count")
)

FX records by status:

               record_count
record_status
valid                  2169
quarantine               15

In [129]:
# Save Silver and quarantine tables

silver_settlement_path = (
    PROCESSED_DIR / "silver_settlement_line.csv"
)

quarantine_settlement_path = (
    PROCESSED_DIR / "quarantine_settlement_line.csv"
)

silver_payout_path = (
    PROCESSED_DIR / "silver_payout_batch.csv"
)

quarantine_payout_path = (
    PROCESSED_DIR / "quarantine_payout_batch.csv"
)

silver_fx_path = (
    PROCESSED_DIR / "silver_fx_rate.csv"
)

quarantine_fx_path = (
    PROCESSED_DIR / "quarantine_fx_rate.csv"
)

silver_settlement_line.to_csv(
    silver_settlement_path,
    index=False
)

silver_settlement_line[
    silver_settlement_line["record_status"] == "quarantine"
].to_csv(
    quarantine_settlement_path,
    index=False
)

silver_payout_batch.to_csv(
    silver_payout_path,
    index=False
)

silver_payout_batch[
    silver_payout_batch["record_status"] == "quarantine"
].to_csv(
    quarantine_payout_path,
    index=False
)

silver_fx_rate.to_csv(
    silver_fx_path,
    index=False
)

silver_fx_rate[
    silver_fx_rate["record_status"] == "quarantine"
].to_csv(
    quarantine_fx_path,
    index=False
)

print("Settlement, payout, and FX outputs saved:")
print(f" - {silver_settlement_path}")
print(f" - {quarantine_settlement_path}")
print(f" - {silver_payout_path}")
print(f" - {quarantine_payout_path}")
print(f" - {silver_fx_path}")
print(f" - {quarantine_fx_path}")

Settlement, payout, and FX outputs saved:
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/silver_settlement_line.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/quarantine_settlement_line.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/silver_payout_batch.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/quarantine_payout_batch.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/silver_fx_rate.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/quarantine_fx_rate.csv

In [130]:
# Review settlement, payout, and FX outputs

print("Settlement-line shape:", silver_settlement_line.shape)
print("Payout-batch shape:", silver_payout_batch.shape)
print("FX-rate shape:", silver_fx_rate.shape)

print("\nSettlement line types:")
display(
    silver_settlement_line["line_type"]
    .value_counts()
    .to_frame("line_count")
)

print("\nSettlement record statuses:")
display(
    silver_settlement_line["record_status"]
    .value_counts()
    .to_frame("record_count")
)

print("\nPayout record statuses:")
display(
    silver_payout_batch["record_status"]
    .value_counts()
    .to_frame("record_count")
)

print("\nFX currencies:")
display(
    silver_fx_rate["from_currency"]
    .value_counts()
    .to_frame("rate_count")
)

print("\nUnallocated settlement examples:")
display(
    silver_settlement_line[
        silver_settlement_line["unallocated_order_flag"]
    ][
        [
            "settlement_line_id",
            "partner_id",
            "line_type",
            "currency_code",
            "net_amount",
            "quality_reasons"
        ]
    ]
    .head()
)

Settlement-line shape: (96712, 24)
Payout-batch shape: (595, 14)
FX-rate shape: (2184, 12)

Settlement line types:

Empty DataFrame
Columns: [line_count]
Index: []

Settlement record statuses:

               record_count
record_status
quarantine            96712

Payout record statuses:

               record_count
record_status
valid                   595

FX currencies:

               rate_count
from_currency
GBP                   546
EUR                   546
SEK                   546
DKK                   546

Unallocated settlement examples:

,settlement_line_id,partner_id,line_type,currency_code,net_amount,quality_reasons
41,SET-000000042,CH_C,NaN,EUR,16.63,unrecognised_settlement_line_type; unallocated...
119,SET-000000120,CH_A,NaN,EUR,21.18,unrecognised_settlement_line_type; unallocated...
180,SET-000000181,CH_A,NaN,GBP,167.14,unrecognised_settlement_line_type; unallocated...
187,SET-000000188,CH_C,NaN,EUR,34.97,unrecognised_settlement_line_type; unallocated...
195,SET-000000196,CH_D,NaN,DKK,13.3,unrecognised_settlement_line_type; unallocated...

## Build Gold analytical tables

The Gold layer contains business-ready tables.

These tables use only records that passed the relevant Silver-layer inclusion rules, while keeping quality flags available for investigation.

In [132]:
# Aggregate valid order lines to the order level

valid_order_lines = silver_order_line[
    silver_order_line["analysis_included"]
].copy()

order_line_totals = (
    valid_order_lines
    .groupby("order_id", as_index=False)
    .agg(
        line_count=("line_id", "nunique"),
        units=("quantity", "sum"),
        line_gross_amount=("line_gross_amount", "sum"),
        line_discount=("line_discount", "sum"),
        line_net_amount=("line_net_amount", "sum")
    )
)

valid_order_headers = silver_order_header[
    silver_order_header["analysis_included"]
].copy()

gold_order_metrics = (
    valid_order_headers[
        [
            "order_id",
            "partner_id",
            "country_code",
            "order_timestamp",
            "order_status",
            "currency_code",
            "shipping_amount",
            "tax_amount"
        ]
    ]
    .merge(
        order_line_totals,
        on="order_id",
        how="left"
    )
)

gold_order_metrics["order_date"] = (
    gold_order_metrics["order_timestamp"]
    .dt.normalize()
)

gold_order_metrics["missing_line_data_flag"] = (
    gold_order_metrics["line_count"].isna()
)

gold_order_metrics["line_count"] = (
    gold_order_metrics["line_count"]
    .fillna(0)
)

gold_order_metrics["units"] = (
    gold_order_metrics["units"]
    .fillna(0)
)

for column in [
    "line_gross_amount",
    "line_discount",
    "line_net_amount"
]:
    gold_order_metrics[column] = (
        gold_order_metrics[column]
        .fillna(0)
    )

gold_order_metrics["shipping_amount"] = (
    gold_order_metrics["shipping_amount"]
    .fillna(0)
)

gold_order_metrics["tax_amount"] = (
    gold_order_metrics["tax_amount"]
    .fillna(0)
)

gold_order_metrics["gross_merchandise_value"] = (
    gold_order_metrics["line_gross_amount"]
)

gold_order_metrics["net_merchandise_value"] = (
    gold_order_metrics["line_net_amount"]
)

gold_order_metrics["net_sales_before_returns"] = (
    gold_order_metrics["net_merchandise_value"]
    + gold_order_metrics["shipping_amount"]
).round(2)

gold_order_metrics["cancelled_flag"] = (
    gold_order_metrics["order_status"]
    == "cancelled"
)

gold_order_metrics["returned_or_refunded_flag"] = (
    gold_order_metrics["order_status"]
    .isin(["returned", "refunded"])
)

print("Gold order metrics created:")
print(gold_order_metrics.shape)

display(
    gold_order_metrics.head()
)

Gold order metrics created:
(74557, 20)

,order_id,partner_id,country_code,order_timestamp,order_status,currency_code,shipping_amount,tax_amount,line_count,units,line_gross_amount,line_discount,line_net_amount,order_date,missing_line_data_flag,gross_merchandise_value,net_merchandise_value,net_sales_before_returns,cancelled_flag,returned_or_refunded_flag
0,ORD-000000001,CH_A,DE,2025-10-06 19:19:09,delivered,EUR,5.99,5.08,3,3,26.75,0.0,26.75,2025-10-06,False,26.75,26.75,32.74,False,False
1,ORD-000000002,CH_A,GB,2026-03-02 09:37:57,cancelled,GBP,5.99,9.03,3,5,45.19,0.0,45.19,2026-03-02,False,45.19,45.19,51.18,True,False
2,ORD-000000003,CH_C,IT,2025-08-29 05:46:06,delivered,EUR,3.99,14.25,1,2,64.8,0.0,64.8,2025-08-29,False,64.8,64.8,68.79,False,False
3,ORD-000000004,CH_C,ES,2025-03-21 07:05:28,delivered,EUR,3.99,16.63,2,6,85.96,6.77,79.19,2025-03-21,False,85.96,79.19,83.18,False,False
4,ORD-000000005,CH_A,DE,2025-09-29 15:38:00,delivered,EUR,5.99,7.75,1,2,40.8,0.0,40.8,2025-09-29,False,40.8,40.8,46.79,False,False

In [133]:
# Prepare one FX rate per currency and date

valid_fx = silver_fx_rate[
    silver_fx_rate["analysis_included"]
].copy()

valid_fx = (
    valid_fx
    .sort_values("ingested_at")
    .drop_duplicates(
        subset=[
            "rate_date",
            "from_currency",
            "to_currency"
        ],
        keep="last"
    )
)

fx_for_orders = valid_fx[
    [
        "rate_date",
        "from_currency",
        "to_currency",
        "rate_to_gbp"
    ]
].rename(
    columns={
        "rate_date": "order_date",
        "from_currency": "currency_code"
    }
)

gold_order_metrics = gold_order_metrics.merge(
    fx_for_orders,
    on=[
        "order_date",
        "currency_code"
    ],
    how="left"
)

gold_order_metrics["fx_missing_flag"] = (
    gold_order_metrics["rate_to_gbp"].isna()
)

gold_order_metrics["rate_to_gbp"] = (
    gold_order_metrics["rate_to_gbp"]
    .fillna(1.0)
)

for column in [
    "gross_merchandise_value",
    "net_merchandise_value",
    "net_sales_before_returns",
    "shipping_amount",
    "tax_amount"
]:
    gold_order_metrics[
        f"{column}_gbp"
    ] = (
        gold_order_metrics[column]
        * gold_order_metrics["rate_to_gbp"]
    ).round(2)

print("Order values converted to GBP.")
display(
    gold_order_metrics[
        [
            "order_id",
            "currency_code",
            "rate_to_gbp",
            "net_sales_before_returns",
            "net_sales_before_returns_gbp",
            "fx_missing_flag"
        ]
    ].head()
)

Order values converted to GBP.

,order_id,currency_code,rate_to_gbp,net_sales_before_returns,net_sales_before_returns_gbp,fx_missing_flag
0,ORD-000000001,EUR,0.86343,32.74,28.27,False
1,ORD-000000002,GBP,1.0,51.18,51.18,False
2,ORD-000000003,EUR,0.860679,68.79,59.21,False
3,ORD-000000004,EUR,0.847549,83.18,70.5,False
4,ORD-000000005,EUR,0.862788,46.79,40.37,False

In [134]:
# Aggregate order metrics by partner, country, and day

gold_partner_daily_metrics = (
    gold_order_metrics
    .groupby(
        [
            "order_date",
            "partner_id",
            "country_code"
        ],
        as_index=False
    )
    .agg(
        order_count=("order_id", "nunique"),
        units=("units", "sum"),
        gross_merchandise_value_gbp=(
            "gross_merchandise_value_gbp",
            "sum"
        ),
        net_merchandise_value_gbp=(
            "net_merchandise_value_gbp",
            "sum"
        ),
        net_sales_before_returns_gbp=(
            "net_sales_before_returns_gbp",
            "sum"
        ),
        cancelled_order_count=(
            "cancelled_flag",
            "sum"
        ),
        returned_or_refunded_order_count=(
            "returned_or_refunded_flag",
            "sum"
        ),
        orders_missing_line_data=(
            "missing_line_data_flag",
            "sum"
        ),
        orders_missing_fx=(
            "fx_missing_flag",
            "sum"
        )
    )
)

gold_partner_daily_metrics["average_order_value_gbp"] = (
    gold_partner_daily_metrics[
        "net_sales_before_returns_gbp"
    ]
    / gold_partner_daily_metrics["order_count"]
).round(2)

gold_partner_daily_metrics["cancellation_rate"] = (
    gold_partner_daily_metrics[
        "cancelled_order_count"
    ]
    / gold_partner_daily_metrics["order_count"]
).round(4)

gold_partner_daily_metrics["return_or_refund_rate"] = (
    gold_partner_daily_metrics[
        "returned_or_refunded_order_count"
    ]
    / gold_partner_daily_metrics["order_count"]
).round(4)

print("Partner daily metrics created.")
display(gold_partner_daily_metrics.head())

Partner daily metrics created.

,order_date,partner_id,country_code,order_count,units,gross_merchandise_value_gbp,net_merchandise_value_gbp,net_sales_before_returns_gbp,cancelled_order_count,returned_or_refunded_order_count,orders_missing_line_data,orders_missing_fx,average_order_value_gbp,cancellation_rate,return_or_refund_rate
0,2025-01-01,CH_A,DE,12,23,550.91,539.6,589.46,0,3,0,0,49.12,0.0000,0.2500
1,2025-01-01,CH_A,GB,49,96,2458.57,2323.79,2567.34,3,6,0,0,52.39,0.0612,0.1224
2,2025-01-01,CH_A,IE,19,48,577.53,565.14,657.99,0,1,0,0,34.63,0.0000,0.0526
3,2025-01-01,CH_B,BE,5,13,380.44,371.61,385.37,0,0,0,0,77.07,0.0000,0.0000
4,2025-01-01,CH_B,DE,13,27,1059.11,1009.31,1048.87,0,0,0,0,80.68,0.0000,0.0000

In [135]:
# Select the latest usable listing snapshot per partner, product, and country

valid_listings = silver_listing[
    silver_listing["analysis_included"]
].copy()

valid_listings = (
    valid_listings
    .sort_values(
        [
            "partner_id",
            "internal_sku",
            "country_code",
            "snapshot_date",
            "ingested_at"
        ]
    )
    .drop_duplicates(
        subset=[
            "partner_id",
            "internal_sku",
            "country_code"
        ],
        keep="last"
    )
)

listing_health = valid_listings[
    [
        "partner_id",
        "source_item_code",
        "internal_sku",
        "country_code",
        "snapshot_date",
        "listing_status",
        "price_local",
        "currency_code",
        "available_units",
        "content_completeness_pct",
        "live_listing_flag",
        "quality_reasons"
    ]
].copy()

listing_health = listing_health.rename(
    columns={
        "available_units": "listing_available_units"
    }
)

print(
    "Latest listing health rows:",
    f"{len(listing_health):,}"
)

Latest listing health rows: 67,003

In [136]:
# Select the latest inventory record per partner, product, country, and warehouse

valid_inventory = silver_inventory[
    silver_inventory["analysis_included"]
].copy()

valid_inventory = (
    valid_inventory
    .sort_values(
        [
            "partner_id",
            "internal_sku",
            "country_code",
            "warehouse_code",
            "inventory_timestamp",
            "ingested_at"
        ]
    )
    .drop_duplicates(
        subset=[
            "partner_id",
            "internal_sku",
            "country_code",
            "warehouse_code"
        ],
        keep="last"
    )
)

inventory_health = (
    valid_inventory
    .groupby(
        [
            "partner_id",
            "internal_sku",
            "country_code"
        ],
        as_index=False
    )
    .agg(
        inventory_available_units=(
            "available_units",
            "sum"
        ),
        inventory_reserved_units=(
            "reserved_units",
            "sum"
        ),
        inventory_inbound_units=(
            "inbound_units",
            "sum"
        ),
        latest_inventory_timestamp=(
            "inventory_timestamp",
            "max"
        ),
        warehouse_count=(
            "warehouse_code",
            "nunique"
        )
    )
)

listing_health = listing_health.merge(
    inventory_health,
    on=[
        "partner_id",
        "internal_sku",
        "country_code"
    ],
    how="left"
)

listing_health["inventory_missing_flag"] = (
    listing_health[
        "latest_inventory_timestamp"
    ].isna()
)

listing_health["listing_inventory_difference"] = (
    listing_health["listing_available_units"]
    - listing_health["inventory_available_units"]
)

listing_health["listing_inventory_disagreement_flag"] = (
    listing_health["listing_inventory_difference"]
    .abs()
    > 2
)

listing_health["listing_offline_flag"] = (
    listing_health["listing_status"]
    .isin(
        [
            "OFFLINE",
            "PAUSED"
        ]
    )
)

listing_health["incomplete_content_flag"] = (
    listing_health["content_completeness_pct"]
    < 100
)

listing_health["inventory_stale_flag"] = (
    (
        listing_health["latest_inventory_timestamp"]
        - listing_health["snapshot_date"]
    )
    .dt.total_seconds()
    .div(3600)
    .abs()
    > 48
)

print("Listing health indicators created.")
display(
    listing_health.head()
)

Listing health indicators created.

,partner_id,source_item_code,internal_sku,country_code,snapshot_date,listing_status,price_local,currency_code,listing_available_units,content_completeness_pct,...,inventory_reserved_units,inventory_inbound_units,latest_inventory_timestamp,warehouse_count,inventory_missing_flag,listing_inventory_difference,listing_inventory_disagreement_flag,listing_offline_flag,incomplete_content_flag,inventory_stale_flag
0,CH_A,CH_A_SKU_000003,SKU_000003,BE,2026-06-17,LIVE,7.96,EUR,20,100.0,...,9.0,4,2026-06-17 04:00:00,3.0,False,-30.0,True,False,False,False
1,CH_A,CH_A_SKU_000003,SKU_000003,DE,2026-04-01,LIVE,12.44,EUR,7,100.0,...,7.0,11,2026-04-04 00:00:00,4.0,False,-33.0,True,False,False,True
2,CH_A,CH_A_SKU_000003,SKU_000003,DK,2025-08-13,OFFLINE,96.27,DKK,0,100.0,...,0.0,0,2025-08-17 00:00:00,1.0,False,0.0,False,True,False,True
3,CH_A,CH_A_SKU_000003,SKU_000003,ES,2026-05-27,LIVE,13.22,EUR,28,100.0,...,12.0,11,2026-05-27 00:00:00,4.0,False,-50.0,True,False,False,False
4,CH_A,CH_A_SKU_000003,SKU_000003,FR,2026-04-29,LIVE,8.23,EUR,11,100.0,...,3.0,11,2026-05-03 00:00:00,3.0,False,-21.0,True,False,False,True

In [137]:
# Create a summary of current listing health

listing_health_summary = pd.DataFrame({
    "metric": [
        "listing_count",
        "live_listing_count",
        "offline_or_paused_count",
        "listing_inventory_disagreement_count",
        "incomplete_content_count",
        "stale_inventory_count",
        "missing_inventory_count"
    ],
    "value": [
        len(listing_health),
        int(
            listing_health["live_listing_flag"]
            .sum()
        ),
        int(
            listing_health["listing_offline_flag"]
            .sum()
        ),
        int(
            listing_health[
                "listing_inventory_disagreement_flag"
            ].sum()
        ),
        int(
            listing_health[
                "incomplete_content_flag"
            ].sum()
        ),
        int(
            listing_health[
                "inventory_stale_flag"
            ].sum()
        ),
        int(
            listing_health[
                "inventory_missing_flag"
            ].sum()
        )
    ]
})

display(listing_health_summary)

                                 metric  value
0                         listing_count  67003
1                    live_listing_count  57926
2               offline_or_paused_count   9077
3  listing_inventory_disagreement_count  57682
4              incomplete_content_count   2574
5                 stale_inventory_count  31915
6               missing_inventory_count     33

In [138]:
# Save Gold analytical tables

gold_order_metrics_path = (
    PROCESSED_DIR / "gold_order_metrics.csv"
)

gold_partner_daily_path = (
    PROCESSED_DIR / "gold_partner_daily_metrics.csv"
)

gold_listing_health_path = (
    PROCESSED_DIR / "gold_listing_health.csv"
)

gold_order_metrics.to_csv(
    gold_order_metrics_path,
    index=False
)

gold_partner_daily_metrics.to_csv(
    gold_partner_daily_path,
    index=False
)

listing_health.to_csv(
    gold_listing_health_path,
    index=False
)

print("Gold tables saved:")
print(f" - {gold_order_metrics_path}")
print(f" - {gold_partner_daily_path}")
print(f" - {gold_listing_health_path}")

Gold tables saved:
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/gold_order_metrics.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/gold_partner_daily_metrics.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/gold_listing_health.csv

In [139]:
# Review partner-level performance

partner_summary = (
    gold_partner_daily_metrics
    .groupby("partner_id", as_index=False)
    .agg(
        order_count=("order_count", "sum"),
        units=("units", "sum"),
        net_sales_gbp=(
            "net_sales_before_returns_gbp",
            "sum"
        ),
        cancelled_orders=(
            "cancelled_order_count",
            "sum"
        ),
        returned_or_refunded_orders=(
            "returned_or_refunded_order_count",
            "sum"
        )
    )
)

partner_summary["cancellation_rate"] = (
    partner_summary["cancelled_orders"]
    / partner_summary["order_count"]
).round(4)

partner_summary["return_or_refund_rate"] = (
    partner_summary[
        "returned_or_refunded_orders"
    ]
    / partner_summary["order_count"]
).round(4)

display(
    partner_summary.sort_values(
        "net_sales_gbp",
        ascending=False
    )
)

,partner_id,order_count,units,net_sales_gbp,cancelled_orders,returned_or_refunded_orders,cancellation_rate,return_or_refund_rate
0,CH_A,32506,80263,1638549.86,1808,3463,0.0556,0.1065
1,CH_B,21979,54136,1013038.64,1218,2271,0.0554,0.1033
2,CH_C,13497,33771,616064.57,698,1419,0.0517,0.1051
3,CH_D,6575,16267,104928.03,350,736,0.0532,0.1119

## Reconcile expected and reported settlement amounts

This table compares an explainable expected settlement amount with the amount reported by the fictional partner.

Differences are prioritised for investigation rather than automatically labelled as errors.

In [141]:
# Prepare FX rates for settlement-date conversion

valid_fx_for_settlement = silver_fx_rate[
    silver_fx_rate["analysis_included"]
].copy()

valid_fx_for_settlement = (
    valid_fx_for_settlement
    .sort_values(
        [
            "from_currency",
            "rate_date",
            "ingested_at"
        ]
    )
    .drop_duplicates(
        subset=[
            "from_currency",
            "to_currency",
            "rate_date"
        ],
        keep="last"
    )
)

latest_fx_rate_by_currency = (
    valid_fx_for_settlement
    .sort_values("rate_date")
    .groupby("from_currency")
    .tail(1)
    .set_index("from_currency")["rate_to_gbp"]
    .to_dict()
)

settlement_for_reconciliation = (
    silver_settlement_line[
        silver_settlement_line["analysis_included"]
    ]
    .copy()
)

settlement_for_reconciliation["payout_date_only"] = (
    settlement_for_reconciliation["payout_date"]
    .dt.normalize()
)

settlement_for_reconciliation = (
    settlement_for_reconciliation
    .merge(
        valid_fx_for_settlement[
            [
                "rate_date",
                "from_currency",
                "to_currency",
                "rate_to_gbp"
            ]
        ].rename(
            columns={
                "rate_date": "payout_date_only",
                "from_currency": "currency_code"
            }
        ),
        on=[
            "payout_date_only",
            "currency_code"
        ],
        how="left"
    )
)

settlement_for_reconciliation["fx_missing_flag"] = (
    settlement_for_reconciliation["rate_to_gbp"]
    .isna()
)

settlement_for_reconciliation["rate_to_gbp"] = (
    settlement_for_reconciliation["rate_to_gbp"]
    .fillna(
        settlement_for_reconciliation[
            "currency_code"
        ].map(latest_fx_rate_by_currency)
    )
    .fillna(1.0)
)

settlement_for_reconciliation["net_amount_gbp"] = (
    settlement_for_reconciliation["net_amount"]
    * settlement_for_reconciliation["rate_to_gbp"]
).round(2)

print("Settlement amounts converted to GBP.")
display(
    settlement_for_reconciliation[
        [
            "settlement_line_id",
            "partner_id",
            "currency_code",
            "net_amount",
            "rate_to_gbp",
            "net_amount_gbp",
            "fx_missing_flag"
        ]
    ].head()
)

Settlement amounts converted to GBP.

Empty DataFrame
Columns: [settlement_line_id, partner_id, currency_code, net_amount, rate_to_gbp, net_amount_gbp, fx_missing_flag]
Index: []

In [142]:
# Aggregate reported settlement amounts by order

reported_settlement_by_order = (
    settlement_for_reconciliation[
        settlement_for_reconciliation[
            "order_reference"
        ].notna()
    ]
    .groupby(
        "order_reference",
        as_index=False
    )
    .agg(
        reported_settlement_gbp=(
            "net_amount_gbp",
            "sum"
        ),
        settlement_line_count=(
            "settlement_line_id",
            "nunique"
        ),
        settlement_fx_missing_count=(
            "fx_missing_flag",
            "sum"
        )
    )
    .rename(
        columns={
            "order_reference": "order_id"
        }
    )
)

print(
    "Orders with reported settlement:",
    f"{len(reported_settlement_by_order):,}"
)

display(
    reported_settlement_by_order.head()
)

Orders with reported settlement: 0

Empty DataFrame
Columns: [order_id, reported_settlement_gbp, settlement_line_count, settlement_fx_missing_count]
Index: []

In [143]:
# Create an explainable expected settlement amount per order

expected_settlement = gold_order_metrics[
    gold_order_metrics["order_status"] != "cancelled"
].copy()

expected_settlement["expected_gross_settlement_gbp"] = (
    expected_settlement["net_merchandise_value_gbp"]
    + expected_settlement["shipping_amount_gbp"]
).round(2)

expected_settlement["expected_platform_fee_gbp"] = (
    expected_settlement["expected_gross_settlement_gbp"]
    * expected_settlement["partner_id"].map(
        partner_fee_rates
    )
).round(2)

# Use a documented synthetic payment-fee assumption
expected_settlement["expected_payment_fee_gbp"] = (
    expected_settlement["expected_gross_settlement_gbp"]
    * 0.025
).round(2)

expected_settlement["expected_tax_withheld_gbp"] = (
    expected_settlement["tax_amount_gbp"]
).round(2)

expected_settlement["expected_sale_settlement_gbp"] = (
    expected_settlement["expected_gross_settlement_gbp"]
    - expected_settlement["expected_platform_fee_gbp"]
    - expected_settlement["expected_payment_fee_gbp"]
    - expected_settlement["expected_tax_withheld_gbp"]
).round(2)

print("Expected order settlements created.")

display(
    expected_settlement[
        [
            "order_id",
            "partner_id",
            "expected_gross_settlement_gbp",
            "expected_platform_fee_gbp",
            "expected_payment_fee_gbp",
            "expected_tax_withheld_gbp",
            "expected_sale_settlement_gbp"
        ]
    ].head()
)

Expected order settlements created.

,order_id,partner_id,expected_gross_settlement_gbp,expected_platform_fee_gbp,expected_payment_fee_gbp,expected_tax_withheld_gbp,expected_sale_settlement_gbp
0,ORD-000000001,CH_A,28.27,3.96,0.71,4.39,19.21
2,ORD-000000003,CH_C,59.2,7.1,1.48,12.26,38.36
3,ORD-000000004,CH_C,70.5,8.46,1.76,14.09,46.19
4,ORD-000000005,CH_A,40.37,5.65,1.01,6.69,27.02
5,ORD-000000006,CH_C,97.45,11.69,2.44,18.51,64.81

In [144]:
# Convert return refunds to GBP and aggregate by order

valid_returns_for_reconciliation = silver_return_case[
    silver_return_case["analysis_included"]
].copy()

valid_returns_for_reconciliation["received_date_only"] = (
    valid_returns_for_reconciliation["received_at"]
    .dt.normalize()
)

valid_returns_for_reconciliation = (
    valid_returns_for_reconciliation
    .merge(
        valid_fx_for_settlement[
            [
                "rate_date",
                "from_currency",
                "to_currency",
                "rate_to_gbp"
            ]
        ].rename(
            columns={
                "rate_date": "received_date_only",
                "from_currency": "currency_code"
            }
        ),
        on=[
            "received_date_only",
            "currency_code"
        ],
        how="left"
    )
)

valid_returns_for_reconciliation["rate_to_gbp"] = (
    valid_returns_for_reconciliation["rate_to_gbp"]
    .fillna(
        valid_returns_for_reconciliation[
            "currency_code"
        ].map(latest_fx_rate_by_currency)
    )
    .fillna(1.0)
)

valid_returns_for_reconciliation["refund_amount_gbp"] = (
    valid_returns_for_reconciliation["refund_amount"]
    * valid_returns_for_reconciliation["rate_to_gbp"]
).round(2)

refunds_by_order = (
    valid_returns_for_reconciliation
    .groupby("order_id", as_index=False)
    .agg(
        expected_refund_amount_gbp=(
            "refund_amount_gbp",
            "sum"
        ),
        return_case_count=(
            "return_id",
            "nunique"
        )
    )
)

expected_settlement = expected_settlement.merge(
    refunds_by_order,
    on="order_id",
    how="left"
)

expected_settlement[
    "expected_refund_amount_gbp"
] = (
    expected_settlement[
        "expected_refund_amount_gbp"
    ]
    .fillna(0)
)

expected_settlement[
    "expected_net_settlement_gbp"
] = (
    expected_settlement[
        "expected_sale_settlement_gbp"
    ]
    - expected_settlement[
        "expected_refund_amount_gbp"
    ]
).round(2)

print("Expected refunds included.")
display(
    expected_settlement[
        [
            "order_id",
            "expected_sale_settlement_gbp",
            "expected_refund_amount_gbp",
            "expected_net_settlement_gbp"
        ]
    ].head()
)

Expected refunds included.

,order_id,expected_sale_settlement_gbp,expected_refund_amount_gbp,expected_net_settlement_gbp
0,ORD-000000001,19.21,0.0,19.21
1,ORD-000000003,38.36,0.0,38.36
2,ORD-000000004,46.19,0.0,46.19
3,ORD-000000005,27.02,0.0,27.02
4,ORD-000000006,64.81,0.0,64.81

In [145]:
# Compare expected settlement with reported settlement

gold_settlement_reconciliation = (
    expected_settlement[
        [
            "order_id",
            "partner_id",
            "country_code",
            "order_date",
            "order_status",
            "expected_gross_settlement_gbp",
            "expected_platform_fee_gbp",
            "expected_payment_fee_gbp",
            "expected_tax_withheld_gbp",
            "expected_sale_settlement_gbp",
            "expected_refund_amount_gbp",
            "expected_net_settlement_gbp",
            "return_case_count"
        ]
    ]
    .merge(
        reported_settlement_by_order,
        on="order_id",
        how="left"
    )
)

gold_settlement_reconciliation[
    "reported_settlement_gbp"
] = (
    gold_settlement_reconciliation[
        "reported_settlement_gbp"
    ]
    .fillna(0)
)

gold_settlement_reconciliation[
    "settlement_line_count"
] = (
    gold_settlement_reconciliation[
        "settlement_line_count"
    ]
    .fillna(0)
)

gold_settlement_reconciliation[
    "settlement_fx_missing_count"
] = (
    gold_settlement_reconciliation[
        "settlement_fx_missing_count"
    ]
    .fillna(0)
)

gold_settlement_reconciliation[
    "settlement_variance_gbp"
] = (
    gold_settlement_reconciliation[
        "reported_settlement_gbp"
    ]
    - gold_settlement_reconciliation[
        "expected_net_settlement_gbp"
    ]
).round(2)

gold_settlement_reconciliation[
    "absolute_variance_gbp"
] = (
    gold_settlement_reconciliation[
        "settlement_variance_gbp"
    ]
    .abs()
)

gold_settlement_reconciliation[
    "settlement_present_flag"
] = (
    gold_settlement_reconciliation[
        "settlement_line_count"
    ]
    > 0
)

gold_settlement_reconciliation[
    "reconciliation_status"
] = np.select(
    [
        (
            ~gold_settlement_reconciliation[
                "settlement_present_flag"
            ]
            & gold_settlement_reconciliation[
                "order_status"
            ].eq("pending")
        ),
        gold_settlement_reconciliation[
            "absolute_variance_gbp"
        ] <= 1.00,
        gold_settlement_reconciliation[
            "absolute_variance_gbp"
        ] <= 5.00,
        ~gold_settlement_reconciliation[
            "settlement_present_flag"
        ]
    ],
    [
        "not_yet_settled",
        "within_tolerance",
        "minor_variance",
        "missing_reported_settlement"
    ],
    default="investigate"
)

gold_settlement_reconciliation[
    "commercial_priority"
] = np.select(
    [
        gold_settlement_reconciliation[
            "absolute_variance_gbp"
        ] >= 100,
        gold_settlement_reconciliation[
            "absolute_variance_gbp"
        ] >= 25
    ],
    [
        "high",
        "medium"
    ],
    default="low"
)

print("Settlement reconciliation created.")
display(
    gold_settlement_reconciliation[
        "reconciliation_status"
    ]
    .value_counts()
    .to_frame("order_count")
)

Settlement reconciliation created.

                             order_count
reconciliation_status
missing_reported_settlement        58716
minor_variance                      7752
within_tolerance                    2786
not_yet_settled                     1229

In [146]:
# Summarise settlement lines without an order-level reference

unallocated_settlement = (
    settlement_for_reconciliation[
        settlement_for_reconciliation[
            "unallocated_order_flag"
        ]
    ]
    .groupby(
        [
            "partner_id",
            "currency_code",
            "line_type",
            "payout_date_only"
        ],
        as_index=False
    )
    .agg(
        unallocated_line_count=(
            "settlement_line_id",
            "nunique"
        ),
        unallocated_amount_gbp=(
            "net_amount_gbp",
            "sum"
        ),
        absolute_unallocated_amount_gbp=(
            "net_amount_gbp",
            lambda values: values.abs().sum()
        )
    )
)

unallocated_settlement[
    "commercial_priority"
] = np.select(
    [
        unallocated_settlement[
            "absolute_unallocated_amount_gbp"
        ] >= 100,
        unallocated_settlement[
            "absolute_unallocated_amount_gbp"
        ] >= 25
    ],
    [
        "high",
        "medium"
    ],
    default="low"
)

print("Unallocated settlement summary created.")
display(
    unallocated_settlement.head()
)

Unallocated settlement summary created.

Empty DataFrame
Columns: [partner_id, currency_code, line_type, payout_date_only, unallocated_line_count, unallocated_amount_gbp, absolute_unallocated_amount_gbp, commercial_priority]
Index: []

In [147]:
# Save settlement reconciliation outputs

gold_settlement_reconciliation_path = (
    PROCESSED_DIR
    / "gold_settlement_reconciliation.csv"
)

gold_unallocated_settlement_path = (
    PROCESSED_DIR
    / "gold_unallocated_settlement.csv"
)

gold_settlement_reconciliation.to_csv(
    gold_settlement_reconciliation_path,
    index=False
)

unallocated_settlement.to_csv(
    gold_unallocated_settlement_path,
    index=False
)

print("Settlement outputs saved:")
print(f" - {gold_settlement_reconciliation_path}")
print(f" - {gold_unallocated_settlement_path}")

Settlement outputs saved:
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/gold_settlement_reconciliation.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/gold_unallocated_settlement.csv

In [148]:
# Review reconciliation results

print("Reconciliation rows:")
print(
    len(gold_settlement_reconciliation)
)

print("\nReconciliation-status distribution:")
display(
    gold_settlement_reconciliation[
        "reconciliation_status"
    ]
    .value_counts()
    .to_frame("order_count")
)

print("\nVariance summary:")
display(
    gold_settlement_reconciliation[
        [
            "expected_net_settlement_gbp",
            "reported_settlement_gbp",
            "settlement_variance_gbp",
            "absolute_variance_gbp"
        ]
    ]
    .describe()
)

print("\nHighest-value reconciliation exceptions:")
display(
    gold_settlement_reconciliation
    .sort_values(
        "absolute_variance_gbp",
        ascending=False
    )[
        [
            "order_id",
            "partner_id",
            "country_code",
            "expected_net_settlement_gbp",
            "reported_settlement_gbp",
            "settlement_variance_gbp",
            "reconciliation_status",
            "commercial_priority"
        ]
    ]
    .head(15)
)

Reconciliation rows:
70483

Reconciliation-status distribution:

                             order_count
reconciliation_status
missing_reported_settlement        58716
minor_variance                      7752
within_tolerance                    2786
not_yet_settled                     1229

Variance summary:

,expected_net_settlement_gbp,reported_settlement_gbp,settlement_variance_gbp,absolute_variance_gbp
count,70483.0,70483.0,70483.0,70483.0
mean,21.8163,0.0,-21.8163,24.546998
std,25.429015,0.0,25.429015,22.804141
min,-186.17,0.0,-518.75,0.0
25%,8.32,0.0,-31.4,10.51
50%,18.65,0.0,-18.65,19.52
75%,31.4,0.0,-8.32,31.94
max,518.75,0.0,186.17,518.75

Highest-value reconciliation exceptions:

,order_id,partner_id,country_code,expected_net_settlement_gbp,reported_settlement_gbp,settlement_variance_gbp,reconciliation_status,commercial_priority
26744,ORD-000028474,CH_C,ES,518.75,0.0,-518.75,missing_reported_settlement,high
42505,ORD-000045224,CH_C,DE,412.45,0.0,-412.45,missing_reported_settlement,high
50146,ORD-000053368,CH_A,GB,404.65,0.0,-404.65,missing_reported_settlement,high
68263,ORD-000072626,CH_A,GB,392.54,0.0,-392.54,missing_reported_settlement,high
66298,ORD-000070539,CH_B,NL,383.59,0.0,-383.59,missing_reported_settlement,high
10411,ORD-000011107,CH_A,GB,370.2,0.0,-370.2,missing_reported_settlement,high
21514,ORD-000022929,CH_B,FR,352.38,0.0,-352.38,missing_reported_settlement,high
43245,ORD-000046029,CH_A,GB,324.59,0.0,-324.59,missing_reported_settlement,high
26130,ORD-000027827,CH_B,DE,324.0,0.0,-324.0,missing_reported_settlement,high
14571,ORD-000015544,CH_C,DE,314.76,0.0,-314.76,missing_reported_settlement,high
61301,ORD-000065212,CH_C,ES,305.98,0.0,-305.98,missing_reported_settlement,high
7107,ORD-000007569,CH_A,DE,302.04,0.0,-302.04,missing_reported_settlement,high
36554,ORD-000038901,CH_A,DE,299.62,0.0,-299.62,missing_reported_settlement,high
39621,ORD-000042165,CH_A,GB,298.31,0.0,-298.31,missing_reported_settlement,high
50362,ORD-000053603,CH_B,FR,294.42,0.0,-294.42,missing_reported_settlement,high

## Detect anomalies and build the exception queue

The exception queue combines commercial anomalies and data-quality issues.

Anomaly detection uses rolling historical baselines. Every flagged item includes evidence, commercial impact, and a recommended next action.

In [150]:
# Calculate rolling partner and country baselines

metric_baseline_parts = []

metric_group_columns = [
    "partner_id",
    "country_code"
]

for group_key, group in gold_partner_daily_metrics.groupby(
    metric_group_columns,
    dropna=False
):
    group = group.sort_values(
        "order_date"
    ).copy()

    sales_series = (
        group["net_sales_before_returns_gbp"]
        .astype(float)
    )

    order_series = (
        group["order_count"]
        .astype(float)
    )

    group["sales_baseline_gbp"] = (
        sales_series
        .shift(1)
        .rolling(
            window=28,
            min_periods=7
        )
        .median()
    )

    group["sales_baseline_std_gbp"] = (
        sales_series
        .shift(1)
        .rolling(
            window=28,
            min_periods=7
        )
        .std()
    )

    group["orders_baseline"] = (
        order_series
        .shift(1)
        .rolling(
            window=28,
            min_periods=7
        )
        .median()
    )

    group["sales_deviation_gbp"] = (
        group["net_sales_before_returns_gbp"]
        - group["sales_baseline_gbp"]
    ).round(2)

    group["sales_deviation_pct"] = (
        group["sales_deviation_gbp"]
        / group["sales_baseline_gbp"]
        .replace(0, np.nan)
    ).round(4)

    group["sales_z_score"] = (
        group["sales_deviation_gbp"]
        / group["sales_baseline_std_gbp"]
        .replace(0, np.nan)
    ).round(2)

    group["orders_deviation_pct"] = (
        (
            group["order_count"]
            - group["orders_baseline"]
        )
        / group["orders_baseline"]
        .replace(0, np.nan)
    ).round(4)

    metric_baseline_parts.append(group)

gold_partner_metric_anomalies = pd.concat(
    metric_baseline_parts,
    ignore_index=True
)

print(
    "Baseline metrics created:",
    gold_partner_metric_anomalies.shape
)

display(
    gold_partner_metric_anomalies[
        [
            "order_date",
            "partner_id",
            "country_code",
            "net_sales_before_returns_gbp",
            "sales_baseline_gbp",
            "sales_deviation_pct",
            "sales_z_score"
        ]
    ].tail()
)

Baseline metrics created: (6942, 22)

,order_date,partner_id,country_code,net_sales_before_returns_gbp,sales_baseline_gbp,sales_deviation_pct,sales_z_score
6937,2026-06-26,CH_D,SE,17.16,22.980,-0.2533,-0.47
6938,2026-06-27,CH_D,SE,29.43,22.980,0.2807,0.52
6939,2026-06-28,CH_D,SE,35.56,23.125,0.5379,1.03
6940,2026-06-29,CH_D,SE,23.34,23.125,0.0091,0.02
6941,2026-06-30,CH_D,SE,17.61,23.275,-0.2432,-0.49

In [151]:
# Classify explainable partner metric anomalies

gold_partner_metric_anomalies["metric_anomaly_reason"] = pd.NA

low_sales_mask = (
    gold_partner_metric_anomalies[
        "sales_deviation_pct"
    ] <= -0.40
) & (
    gold_partner_metric_anomalies[
        "sales_baseline_gbp"
    ] > 0
)

high_sales_mask = (
    gold_partner_metric_anomalies[
        "sales_deviation_pct"
    ] >= 0.80
) & (
    gold_partner_metric_anomalies[
        "sales_baseline_gbp"
    ] > 0
)

large_z_score_mask = (
    gold_partner_metric_anomalies[
        "sales_z_score"
    ].abs() >= 3
)

high_cancellation_mask = (
    gold_partner_metric_anomalies[
        "cancellation_rate"
    ] >= 0.15
)

metric_anomaly_reason = np.select(
    [
        low_sales_mask & large_z_score_mask,
        high_sales_mask & large_z_score_mask,
        low_sales_mask,
        high_sales_mask,
        high_cancellation_mask
    ],
    [
        "sales_significantly_below_baseline",
        "sales_significantly_above_baseline",
        "sales_below_baseline",
        "sales_above_baseline",
        "high_cancellation_rate"
    ],
    default=None
)

gold_partner_metric_anomalies[
    "metric_anomaly_reason"
] = metric_anomaly_reason

gold_partner_metric_anomalies["metric_anomaly_flag"] = (
    gold_partner_metric_anomalies[
        "metric_anomaly_reason"
    ].notna()
)

gold_partner_metric_anomalies[
    "estimated_metric_impact_gbp"
] = (
    gold_partner_metric_anomalies[
        "sales_deviation_gbp"
    ].abs()
)

print("Metric anomalies detected:")
display(
    gold_partner_metric_anomalies[
        "metric_anomaly_reason"
    ]
    .value_counts(dropna=False)
    .to_frame("row_count")
)

Metric anomalies detected:

                                    row_count
metric_anomaly_reason
None                                     4671
sales_below_baseline                     1096
high_cancellation_rate                    594
sales_above_baseline                      483
sales_significantly_above_baseline         97
sales_significantly_below_baseline          1

In [152]:
# Create listing and inventory exception records

listing_exception_base = listing_health.copy()

listing_exception_base["currency_rate_to_gbp"] = (
    listing_exception_base["currency_code"]
    .map(latest_fx_rate_by_currency)
    .fillna(1.0)
)

listing_exception_base[
    "estimated_inventory_value_at_risk_gbp"
] = (
    listing_exception_base[
        "inventory_available_units"
    ]
    .fillna(0)
    .clip(lower=0)
    * listing_exception_base[
        "price_local"
    ].fillna(0)
    * listing_exception_base[
        "currency_rate_to_gbp"
    ]
).round(2)

listing_exception_frames = []

offline_records = listing_exception_base[
    listing_exception_base["listing_offline_flag"]
].copy()

offline_records["issue_type"] = (
    "listing_offline_or_paused"
)

offline_records["evidence"] = (
    "Listing status is offline or paused"
)

offline_records["recommended_action"] = (
    "Investigate source status, content requirements, and inventory availability"
)

listing_exception_frames.append(
    offline_records
)

inventory_disagreement_records = listing_exception_base[
    listing_exception_base[
        "listing_inventory_disagreement_flag"
    ]
].copy()

inventory_disagreement_records["issue_type"] = (
    "listing_inventory_disagreement"
)

inventory_disagreement_records["evidence"] = (
    "Listing stock differs materially from latest inventory stock"
)

inventory_disagreement_records["recommended_action"] = (
    "Compare feed timestamps, reservations, and partner inventory rules"
)

listing_exception_frames.append(
    inventory_disagreement_records
)

stale_inventory_records = listing_exception_base[
    listing_exception_base["inventory_stale_flag"]
].copy()

stale_inventory_records["issue_type"] = (
    "stale_inventory"
)

stale_inventory_records["evidence"] = (
    "Latest inventory update is more than 48 hours from the listing snapshot"
)

stale_inventory_records["recommended_action"] = (
    "Investigate feed freshness and confirm the expected update frequency"
)

listing_exception_frames.append(
    stale_inventory_records
)

incomplete_content_records = listing_exception_base[
    listing_exception_base["incomplete_content_flag"]
].copy()

incomplete_content_records["issue_type"] = (
    "incomplete_listing_content"
)

incomplete_content_records["evidence"] = (
    "One or more required listing-content fields are missing"
)

incomplete_content_records["recommended_action"] = (
    "Review missing title, category, image, or other required attributes"
)

listing_exception_frames.append(
    incomplete_content_records
)

listing_exception_records = pd.concat(
    listing_exception_frames,
    ignore_index=True
)

print(
    "Listing exception records:",
    f"{len(listing_exception_records):,}"
)

display(
    listing_exception_records[
        "issue_type"
    ]
    .value_counts()
    .to_frame("record_count")
)

Listing exception records: 101,248

                                record_count
issue_type
listing_inventory_disagreement         57682
stale_inventory                        31915
listing_offline_or_paused               9077
incomplete_listing_content              2574

In [153]:
# Create settlement reconciliation exception records

settlement_exception_records = (
    gold_settlement_reconciliation[
        gold_settlement_reconciliation[
            "reconciliation_status"
        ].isin(
            [
                "investigate",
                "missing_reported_settlement"
            ]
        )
    ]
    .copy()
)

settlement_exception_records["issue_type"] = (
    "settlement_variance"
)

settlement_exception_records["evidence"] = (
    settlement_exception_records[
        "reconciliation_status"
    ]
    + " with variance of GBP "
    + settlement_exception_records[
        "settlement_variance_gbp"
    ]
    .round(2)
    .astype(str)
)

settlement_exception_records["recommended_action"] = (
    "Review settlement line types, fees, refunds, FX, timing, and order references"
)

settlement_exception_records[
    "commercial_impact_gbp"
] = (
    settlement_exception_records[
        "absolute_variance_gbp"
    ]
)

unallocated_exception_records = (
    unallocated_settlement[
        unallocated_settlement[
            "absolute_unallocated_amount_gbp"
        ] > 0
    ]
    .copy()
)

unallocated_exception_records["issue_type"] = (
    "unallocated_settlement"
)

unallocated_exception_records["evidence"] = (
    "Settlement amount has no direct order-level reference"
)

unallocated_exception_records["recommended_action"] = (
    "Investigate statement or payout-batch allocation rules"
)

unallocated_exception_records[
    "commercial_impact_gbp"
] = (
    unallocated_exception_records[
        "absolute_unallocated_amount_gbp"
    ]
)

print(
    "Settlement exception records:",
    f"{len(settlement_exception_records):,}"
)

print(
    "Unallocated settlement records:",
    f"{len(unallocated_exception_records):,}"
)

Settlement exception records: 58,716
Unallocated settlement records: 0

In [154]:
# Create a common exception-queue structure

exception_frames = []

# Listing exceptions
if len(listing_exception_records) > 0:
    listing_queue = pd.DataFrame({
        "source_table": "gold_listing_health",
        "issue_type": listing_exception_records[
            "issue_type"
        ],
        "partner_id": listing_exception_records[
            "partner_id"
        ],
        "country_code": listing_exception_records[
            "country_code"
        ],
        "internal_sku": listing_exception_records[
            "internal_sku"
        ],
        "order_id": pd.NA,
        "event_date": listing_exception_records[
            "snapshot_date"
        ],
        "commercial_impact_gbp": listing_exception_records[
            "estimated_inventory_value_at_risk_gbp"
        ],
        "evidence": listing_exception_records[
            "evidence"
        ],
        "recommended_action": listing_exception_records[
            "recommended_action"
        ]
    })

    exception_frames.append(listing_queue)

# Settlement exceptions
if len(settlement_exception_records) > 0:
    settlement_queue = pd.DataFrame({
        "source_table": "gold_settlement_reconciliation",
        "issue_type": settlement_exception_records[
            "issue_type"
        ],
        "partner_id": settlement_exception_records[
            "partner_id"
        ],
        "country_code": settlement_exception_records[
            "country_code"
        ],
        "internal_sku": pd.NA,
        "order_id": settlement_exception_records[
            "order_id"
        ],
        "event_date": settlement_exception_records[
            "order_date"
        ],
        "commercial_impact_gbp": settlement_exception_records[
            "commercial_impact_gbp"
        ],
        "evidence": settlement_exception_records[
            "evidence"
        ],
        "recommended_action": settlement_exception_records[
            "recommended_action"
        ]
    })

    exception_frames.append(settlement_queue)

# Unallocated settlement exceptions
if len(unallocated_exception_records) > 0:
    unallocated_queue = pd.DataFrame({
        "source_table": "gold_unallocated_settlement",
        "issue_type": unallocated_exception_records[
            "issue_type"
        ],
        "partner_id": unallocated_exception_records[
            "partner_id"
        ],
        "country_code": pd.NA,
        "internal_sku": pd.NA,
        "order_id": pd.NA,
        "event_date": unallocated_exception_records[
            "payout_date_only"
        ],
        "commercial_impact_gbp": unallocated_exception_records[
            "commercial_impact_gbp"
        ],
        "evidence": unallocated_exception_records[
            "evidence"
        ],
        "recommended_action": unallocated_exception_records[
            "recommended_action"
        ]
    })

    exception_frames.append(unallocated_queue)

# Partner metric anomalies
metric_anomaly_records = (
    gold_partner_metric_anomalies[
        gold_partner_metric_anomalies[
            "metric_anomaly_flag"
        ]
    ]
    .copy()
)

if len(metric_anomaly_records) > 0:
    metric_queue = pd.DataFrame({
        "source_table": "gold_partner_daily_metrics",
        "issue_type": "partner_metric_anomaly",
        "partner_id": metric_anomaly_records[
            "partner_id"
        ],
        "country_code": metric_anomaly_records[
            "country_code"
        ],
        "internal_sku": pd.NA,
        "order_id": pd.NA,
        "event_date": metric_anomaly_records[
            "order_date"
        ],
        "commercial_impact_gbp": metric_anomaly_records[
            "estimated_metric_impact_gbp"
        ],
        "evidence": (
            metric_anomaly_records[
                "metric_anomaly_reason"
            ]
            + "; observed sales GBP "
            + metric_anomaly_records[
                "net_sales_before_returns_gbp"
            ]
            .round(2)
            .astype(str)
            + "; baseline sales GBP "
            + metric_anomaly_records[
                "sales_baseline_gbp"
            ]
            .round(2)
            .astype(str)
        ),
        "recommended_action": (
            "Review source completeness, partner activity, promotions, and operational events"
        )
    })

    exception_frames.append(metric_queue)

# Standardise exception-frame columns before concatenation

exception_queue_columns = [
    "source_table",
    "issue_type",
    "partner_id",
    "country_code",
    "internal_sku",
    "order_id",
    "event_date",
    "commercial_impact_gbp",
    "evidence",
    "recommended_action"
]

string_exception_columns = [
    "source_table",
    "issue_type",
    "partner_id",
    "country_code",
    "internal_sku",
    "order_id",
    "evidence",
    "recommended_action"
]

normalised_exception_frames = []

for frame in exception_frames:
    frame = frame.reindex(
        columns=exception_queue_columns
    ).copy()

    for column in string_exception_columns:
        frame[column] = frame[column].astype("string")

    frame["commercial_impact_gbp"] = pd.to_numeric(
        frame["commercial_impact_gbp"],
        errors="coerce"
    ).astype("float64")

    normalised_exception_frames.append(frame)

gold_exception_queue = pd.concat(
    normalised_exception_frames,
    ignore_index=True
)

gold_exception_queue["commercial_impact_gbp"] = (
    pd.to_numeric(
        gold_exception_queue[
            "commercial_impact_gbp"
        ],
        errors="coerce"
    )
    .fillna(0)
    .round(2)
)

impact_q75 = gold_exception_queue[
    "commercial_impact_gbp"
].quantile(0.75)

impact_q95 = gold_exception_queue[
    "commercial_impact_gbp"
].quantile(0.95)

gold_exception_queue["severity"] = np.select(
    [
        gold_exception_queue[
            "commercial_impact_gbp"
        ] >= impact_q95,
        gold_exception_queue[
            "commercial_impact_gbp"
        ] >= impact_q75
    ],
    [
        "high",
        "medium"
    ],
    default="low"
)

gold_exception_queue["review_status"] = (
    "open"
)

gold_exception_queue["review_comment"] = (
    pd.NA
)

gold_exception_queue["exception_id"] = [
    f"EXC-{number:07d}"
    for number in range(
        1,
        len(gold_exception_queue) + 1
    )
]

gold_exception_queue = gold_exception_queue[
    [
        "exception_id",
        "source_table",
        "issue_type",
        "partner_id",
        "country_code",
        "internal_sku",
        "order_id",
        "event_date",
        "severity",
        "commercial_impact_gbp",
        "evidence",
        "recommended_action",
        "review_status",
        "review_comment"
    ]
]

print(
    "Exception queue rows:",
    f"{len(gold_exception_queue):,}"
)

display(
    gold_exception_queue.head()
)

Exception queue rows: 162,235

,exception_id,source_table,issue_type,partner_id,country_code,internal_sku,order_id,event_date,severity,commercial_impact_gbp,evidence,recommended_action,review_status,review_comment
0,EXC-0000001,gold_listing_health,listing_offline_or_paused,CH_A,DK,SKU_000003,<NA>,2025-08-13,low,0.00,Listing status is offline or paused,"Investigate source status, content requirement...",open,<NA>
1,EXC-0000002,gold_listing_health,listing_offline_or_paused,CH_A,NL,SKU_000003,<NA>,2025-06-11,low,0.00,Listing status is offline or paused,"Investigate source status, content requirement...",open,<NA>
2,EXC-0000003,gold_listing_health,listing_offline_or_paused,CH_A,DE,SKU_000004,<NA>,2026-02-25,low,437.37,Listing status is offline or paused,"Investigate source status, content requirement...",open,<NA>
3,EXC-0000004,gold_listing_health,listing_offline_or_paused,CH_A,IE,SKU_000004,<NA>,2026-02-11,low,325.16,Listing status is offline or paused,"Investigate source status, content requirement...",open,<NA>
4,EXC-0000005,gold_listing_health,listing_offline_or_paused,CH_A,DK,SKU_000006,<NA>,2026-05-06,medium,1014.46,Listing status is offline or paused,"Investigate source status, content requirement...",open,<NA>

In [155]:
# Save anomaly and exception outputs

gold_anomalies_path = (
    PROCESSED_DIR
    / "gold_partner_metric_anomalies.csv"
)

gold_exception_queue_path = (
    PROCESSED_DIR
    / "gold_exception_queue.csv"
)

gold_partner_metric_anomalies.to_csv(
    gold_anomalies_path,
    index=False
)

gold_exception_queue.to_csv(
    gold_exception_queue_path,
    index=False
)

print("Anomaly and exception files saved:")
print(f" - {gold_anomalies_path}")
print(f" - {gold_exception_queue_path}")

Anomaly and exception files saved:
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/gold_partner_metric_anomalies.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/gold_exception_queue.csv

In [156]:
# Review the exception queue

print("Exceptions by type:")
display(
    gold_exception_queue[
        "issue_type"
    ]
    .value_counts()
    .to_frame("exception_count")
)

print("\nExceptions by severity:")
display(
    gold_exception_queue[
        "severity"
    ]
    .value_counts()
    .to_frame("exception_count")
)

print("\nHighest-impact open exceptions:")
display(
    gold_exception_queue
    .sort_values(
        "commercial_impact_gbp",
        ascending=False
    )
    .head(20)
)

Exceptions by type:

                                exception_count
issue_type
settlement_variance                       58716
listing_inventory_disagreement            57682
stale_inventory                           31915
listing_offline_or_paused                  9077
incomplete_listing_content                 2574
partner_metric_anomaly                     2271

Exceptions by severity:

          exception_count
severity
low                121676
medium              32446
high                 8113

Highest-impact open exceptions:

,exception_id,source_table,issue_type,partner_id,country_code,internal_sku,order_id,event_date,severity,commercial_impact_gbp,evidence,recommended_action,review_status,review_comment
29891,EXC-0029892,gold_listing_health,listing_inventory_disagreement,CH_B,GB,SKU_000357,<NA>,2026-06-10,high,18526.84,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>
71727,EXC-0071728,gold_listing_health,stale_inventory,CH_A,ES,SKU_001423,<NA>,2026-06-03,high,16773.22,Latest inventory update is more than 48 hours ...,Investigate feed freshness and confirm the exp...,open,<NA>
18074,EXC-0018075,gold_listing_health,listing_inventory_disagreement,CH_A,ES,SKU_001423,<NA>,2026-06-03,high,16773.22,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>
35797,EXC-0035798,gold_listing_health,listing_inventory_disagreement,CH_B,FR,SKU_001423,<NA>,2026-02-04,high,16542.20,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>
98297,EXC-0098298,gold_listing_health,stale_inventory,CH_D,GB,SKU_002787,<NA>,2026-05-06,high,16465.92,Latest inventory update is more than 48 hours ...,Investigate feed freshness and confirm the exp...,open,<NA>
66099,EXC-0066100,gold_listing_health,listing_inventory_disagreement,CH_D,GB,SKU_002787,<NA>,2026-05-06,high,16465.92,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>
29469,EXC-0029470,gold_listing_health,listing_inventory_disagreement,CH_B,FR,SKU_000275,<NA>,2026-06-17,high,14667.66,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>
18752,EXC-0018753,gold_listing_health,listing_inventory_disagreement,CH_A,GB,SKU_001535,<NA>,2026-06-17,high,14567.28,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>
17928,EXC-0017929,gold_listing_health,listing_inventory_disagreement,CH_A,GB,SKU_001398,<NA>,2026-04-29,high,14539.56,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>
74999,EXC-0075000,gold_listing_health,stale_inventory,CH_A,GB,SKU_002365,<NA>,2026-06-17,high,14188.32,Latest inventory update is more than 48 hours ...,Investigate feed freshness and confirm the exp...,open,<NA>
23976,EXC-0023977,gold_listing_health,listing_inventory_disagreement,CH_A,GB,SKU_002365,<NA>,2026-06-17,high,14188.32,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>
35794,EXC-0035795,gold_listing_health,listing_inventory_disagreement,CH_B,DE,SKU_001423,<NA>,2026-05-13,high,13604.81,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>
78966,EXC-0078967,gold_listing_health,stale_inventory,CH_B,GB,SKU_000621,<NA>,2026-06-10,high,13578.95,Latest inventory update is more than 48 hours ...,Investigate feed freshness and confirm the exp...,open,<NA>
31299,EXC-0031300,gold_listing_health,listing_inventory_disagreement,CH_B,GB,SKU_000621,<NA>,2026-06-10,high,13578.95,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>
72535,EXC-0072536,gold_listing_health,stale_inventory,CH_A,DE,SKU_001657,<NA>,2026-03-25,high,13174.93,Latest inventory update is more than 48 hours ...,Investigate feed freshness and confirm the exp...,open,<NA>
19519,EXC-0019520,gold_listing_health,listing_inventory_disagreement,CH_A,DE,SKU_001657,<NA>,2026-03-25,high,13174.93,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>
11285,EXC-0011286,gold_listing_health,listing_inventory_disagreement,CH_A,GB,SKU_000357,<NA>,2026-05-06,high,12440.95,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>
384,EXC-0000385,gold_listing_health,listing_offline_or_paused,CH_A,GB,SKU_000357,<NA>,2026-05-06,high,12440.95,Listing status is offline or paused,"Investigate source status, content requirement...",open,<NA>
11541,EXC-0011542,gold_listing_health,listing_inventory_disagreement,CH_A,DE,SKU_000405,<NA>,2026-06-10,high,12410.42,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>
81403,EXC-0081404,gold_listing_health,stale_inventory,CH_B,SE,SKU_001423,<NA>,2026-03-25,high,12334.56,Latest inventory update is more than 48 hours ...,Investigate feed freshness and confirm the exp...,open,<NA>

## Create prioritised review and data-quality outputs

The full exception queue is retained for auditability.

A separate prioritised queue ranks exceptions by severity and commercial impact so that an analyst can focus on the most important items first.

In [158]:
# Summarise exceptions by issue type, partner, and severity

gold_exception_summary = (
    gold_exception_queue
    .groupby(
        [
            "source_table",
            "issue_type",
            "partner_id",
            "severity"
        ],
        dropna=False,
        as_index=False
    )
    .agg(
        exception_count=(
            "exception_id",
            "nunique"
        ),
        total_commercial_impact_gbp=(
            "commercial_impact_gbp",
            "sum"
        ),
        maximum_commercial_impact_gbp=(
            "commercial_impact_gbp",
            "max"
        ),
        open_exception_count=(
            "review_status",
            lambda values: (values == "open").sum()
        )
    )
)

gold_exception_summary[
    "total_commercial_impact_gbp"
] = (
    gold_exception_summary[
        "total_commercial_impact_gbp"
    ]
    .round(2)
)

gold_exception_summary[
    "maximum_commercial_impact_gbp"
] = (
    gold_exception_summary[
        "maximum_commercial_impact_gbp"
    ]
    .round(2)
)

print("Exception summary created:")
display(
    gold_exception_summary
    .sort_values(
        "total_commercial_impact_gbp",
        ascending=False
    )
    .head(20)
)

Exception summary created:

,source_table,issue_type,partner_id,severity,exception_count,total_commercial_impact_gbp,maximum_commercial_impact_gbp,open_exception_count
14,gold_listing_health,listing_inventory_disagreement,CH_A,medium,6478,8650913.91,2290.51,6478
17,gold_listing_health,listing_inventory_disagreement,CH_B,medium,5697,7635175.91,2290.60,5697
12,gold_listing_health,listing_inventory_disagreement,CH_A,high,1662,6099214.72,16773.22,1662
20,gold_listing_health,listing_inventory_disagreement,CH_C,medium,4262,5683049.07,2290.46,4262
15,gold_listing_health,listing_inventory_disagreement,CH_B,high,1507,5503552.52,18526.84,1507
13,gold_listing_health,listing_inventory_disagreement,CH_A,low,10701,4651895.23,829.60,10701
23,gold_listing_health,listing_inventory_disagreement,CH_D,medium,3253,4308223.63,2290.13,3253
38,gold_listing_health,stale_inventory,CH_A,medium,3179,4225553.80,2290.51,3179
16,gold_listing_health,listing_inventory_disagreement,CH_B,low,9357,4055527.34,829.49,9357
41,gold_listing_health,stale_inventory,CH_B,medium,2810,3753252.21,2290.60,2810
18,gold_listing_health,listing_inventory_disagreement,CH_C,high,1044,3662720.17,11055.96,1044
19,gold_listing_health,listing_inventory_disagreement,CH_C,low,7210,3143441.45,829.28,7210
36,gold_listing_health,stale_inventory,CH_A,high,821,2975259.26,16773.22,821
21,gold_listing_health,listing_inventory_disagreement,CH_D,high,800,2803129.97,16465.92,800
44,gold_listing_health,stale_inventory,CH_C,medium,2118,2783069.54,2290.46,2118
39,gold_listing_health,stale_inventory,CH_B,high,736,2681560.21,13578.95,736
37,gold_listing_health,stale_inventory,CH_A,low,6373,2509660.28,829.60,6373
22,gold_listing_health,listing_inventory_disagreement,CH_D,low,5711,2459618.47,829.59,5711
40,gold_listing_health,stale_inventory,CH_B,low,5511,2178747.76,829.49,5511
47,gold_listing_health,stale_inventory,CH_D,medium,1637,2163199.53,2289.11,1637

In [159]:
# Create a ranked exception queue for operational review

severity_score_map = {
    "high": 3,
    "medium": 2,
    "low": 1
}

prioritised_queue = gold_exception_queue.copy()

prioritised_queue["severity_score"] = (
    prioritised_queue["severity"]
    .map(severity_score_map)
    .fillna(0)
)

prioritised_queue["commercial_impact_log"] = (
    np.log1p(
        prioritised_queue[
            "commercial_impact_gbp"
        ].clip(lower=0)
    )
)

prioritised_queue["priority_score"] = (
    prioritised_queue["severity_score"] * 10
    + prioritised_queue["commercial_impact_log"]
).round(4)

prioritised_queue = (
    prioritised_queue
    .sort_values(
        [
            "priority_score",
            "commercial_impact_gbp"
        ],
        ascending=False
    )
    .reset_index(drop=True)
)

prioritised_queue["dashboard_rank"] = (
    np.arange(len(prioritised_queue))
    + 1
)

# Keep the full ranked queue available, but create a compact
# dashboard queue for faster review.
gold_prioritised_exception_queue = (
    prioritised_queue
    .head(10000)
    .copy()
)

gold_prioritised_exception_queue = (
    gold_prioritised_exception_queue[
        [
            "dashboard_rank",
            "exception_id",
            "source_table",
            "issue_type",
            "partner_id",
            "country_code",
            "internal_sku",
            "order_id",
            "event_date",
            "severity",
            "commercial_impact_gbp",
            "evidence",
            "recommended_action",
            "review_status",
            "review_comment",
            "priority_score"
        ]
    ]
)

print(
    "Full exception queue:",
    f"{len(gold_exception_queue):,}"
)

print(
    "Dashboard exception queue:",
    f"{len(gold_prioritised_exception_queue):,}"
)

display(
    gold_prioritised_exception_queue.head(20)
)

Full exception queue: 162,235
Dashboard exception queue: 10,000

,dashboard_rank,exception_id,source_table,issue_type,partner_id,country_code,internal_sku,order_id,event_date,severity,commercial_impact_gbp,evidence,recommended_action,review_status,review_comment,priority_score
0,1,EXC-0029892,gold_listing_health,listing_inventory_disagreement,CH_B,GB,SKU_000357,<NA>,2026-06-10,high,18526.84,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>,39.8270
1,2,EXC-0018075,gold_listing_health,listing_inventory_disagreement,CH_A,ES,SKU_001423,<NA>,2026-06-03,high,16773.22,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>,39.7276
2,3,EXC-0071728,gold_listing_health,stale_inventory,CH_A,ES,SKU_001423,<NA>,2026-06-03,high,16773.22,Latest inventory update is more than 48 hours ...,Investigate feed freshness and confirm the exp...,open,<NA>,39.7276
3,4,EXC-0035798,gold_listing_health,listing_inventory_disagreement,CH_B,FR,SKU_001423,<NA>,2026-02-04,high,16542.20,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>,39.7137
4,5,EXC-0066100,gold_listing_health,listing_inventory_disagreement,CH_D,GB,SKU_002787,<NA>,2026-05-06,high,16465.92,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>,39.7091
5,6,EXC-0098298,gold_listing_health,stale_inventory,CH_D,GB,SKU_002787,<NA>,2026-05-06,high,16465.92,Latest inventory update is more than 48 hours ...,Investigate feed freshness and confirm the exp...,open,<NA>,39.7091
6,7,EXC-0029470,gold_listing_health,listing_inventory_disagreement,CH_B,FR,SKU_000275,<NA>,2026-06-17,high,14667.66,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>,39.5935
7,8,EXC-0018753,gold_listing_health,listing_inventory_disagreement,CH_A,GB,SKU_001535,<NA>,2026-06-17,high,14567.28,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>,39.5866
8,9,EXC-0017929,gold_listing_health,listing_inventory_disagreement,CH_A,GB,SKU_001398,<NA>,2026-04-29,high,14539.56,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>,39.5847
9,10,EXC-0023977,gold_listing_health,listing_inventory_disagreement,CH_A,GB,SKU_002365,<NA>,2026-06-17,high,14188.32,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>,39.5602
10,11,EXC-0075000,gold_listing_health,stale_inventory,CH_A,GB,SKU_002365,<NA>,2026-06-17,high,14188.32,Latest inventory update is more than 48 hours ...,Investigate feed freshness and confirm the exp...,open,<NA>,39.5602
11,12,EXC-0035795,gold_listing_health,listing_inventory_disagreement,CH_B,DE,SKU_001423,<NA>,2026-05-13,high,13604.81,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>,39.5183
12,13,EXC-0031300,gold_listing_health,listing_inventory_disagreement,CH_B,GB,SKU_000621,<NA>,2026-06-10,high,13578.95,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>,39.5163
13,14,EXC-0078967,gold_listing_health,stale_inventory,CH_B,GB,SKU_000621,<NA>,2026-06-10,high,13578.95,Latest inventory update is more than 48 hours ...,Investigate feed freshness and confirm the exp...,open,<NA>,39.5163
14,15,EXC-0019520,gold_listing_health,listing_inventory_disagreement,CH_A,DE,SKU_001657,<NA>,2026-03-25,high,13174.93,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>,39.4861
15,16,EXC-0072536,gold_listing_health,stale_inventory,CH_A,DE,SKU_001657,<NA>,2026-03-25,high,13174.93,Latest inventory update is more than 48 hours ...,Investigate feed freshness and confirm the exp...,open,<NA>,39.4861
16,17,EXC-0000385,gold_listing_health,listing_offline_or_paused,CH_A,GB,SKU_000357,<NA>,2026-05-06,high,12440.95,Listing status is offline or paused,"Investigate source status, content requirement...",open,<NA>,39.4288
17,18,EXC-0011286,gold_listing_health,listing_inventory_disagreement,CH_A,GB,SKU_000357,<NA>,2026-05-06,high,12440.95,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>,39.4288
18,19,EXC-0011542,gold_listing_health,listing_inventory_disagreement,CH_A,DE,SKU_000405,<NA>,2026-06-10,high,12410.42,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>,39.4264
19,20,EXC-0035802,gold_listing_health,listing_inventory_disagreement,CH_B,SE,SKU_001423,<NA>,2026-03-25,high,12334.56,Listing stock differs materially from latest i...,"Compare feed timestamps, reservations, and par...",open,<NA>,39.4202

In [160]:
# Create a data-quality summary across all Silver tables

silver_tables_for_quality = {
    "silver_listing": silver_listing,
    "silver_inventory": silver_inventory,
    "silver_order_header": silver_order_header,
    "silver_order_line": silver_order_line,
    "silver_shipment_event": silver_shipment_event,
    "silver_return_case": silver_return_case,
    "silver_settlement_line": silver_settlement_line,
    "silver_payout_batch": silver_payout_batch,
    "silver_fx_rate": silver_fx_rate
}

quality_summary_rows = []

for table_name, table in silver_tables_for_quality.items():
    row_count = len(table)

    if "record_status" in table.columns:
        valid_count = int(
            (table["record_status"] == "valid").sum()
        )

        review_count = int(
            (table["record_status"] == "review").sum()
        )

        quarantine_count = int(
            (table["record_status"] == "quarantine").sum()
        )

        analysis_included_count = int(
            table["analysis_included"].sum()
        )
    else:
        valid_count = row_count
        review_count = 0
        quarantine_count = 0
        analysis_included_count = row_count

    quality_summary_rows.append({
        "table_name": table_name,
        "row_count": row_count,
        "valid_count": valid_count,
        "review_count": review_count,
        "quarantine_count": quarantine_count,
        "analysis_included_count": analysis_included_count,
        "valid_percentage": round(
            valid_count / row_count * 100,
            2
        ) if row_count else 0,
        "review_percentage": round(
            review_count / row_count * 100,
            2
        ) if row_count else 0,
        "quarantine_percentage": round(
            quarantine_count / row_count * 100,
            2
        ) if row_count else 0
    })

data_quality_summary = pd.DataFrame(
    quality_summary_rows
)

display(data_quality_summary)

,table_name,row_count,valid_count,review_count,quarantine_count,analysis_included_count,valid_percentage,review_percentage,quarantine_percentage
0,silver_listing,401173,397977,3196,0,401173,99.20,0.80,0.00
1,silver_inventory,399575,395306,1491,2778,396797,98.93,0.37,0.70
2,silver_order_header,75000,74557,0,443,74557,99.41,0.00,0.59
3,silver_order_line,130522,129758,0,764,129758,99.41,0.00,0.59
4,silver_shipment_event,338904,336926,0,1978,336926,99.42,0.00,0.58
5,silver_return_case,24963,24570,282,111,24852,98.43,1.13,0.44
6,silver_settlement_line,96712,0,0,96712,0,0.00,0.00,100.00
7,silver_payout_batch,595,595,0,0,595,100.00,0.00,0.00
8,silver_fx_rate,2184,2169,0,15,2169,99.31,0.00,0.69

In [161]:
# Add overall data-quality indicators

overall_quality_summary = pd.DataFrame([
    {
        "metric": "raw_table_count",
        "value": len(raw_tables)
    },
    {
        "metric": "full_exception_queue_rows",
        "value": len(gold_exception_queue)
    },
    {
        "metric": "dashboard_exception_queue_rows",
        "value": len(
            gold_prioritised_exception_queue
        )
    },
    {
        "metric": "high_severity_exception_count",
        "value": int(
            (
                gold_exception_queue["severity"]
                == "high"
            ).sum()
        )
    },
    {
        "metric": "medium_severity_exception_count",
        "value": int(
            (
                gold_exception_queue["severity"]
                == "medium"
            ).sum()
        )
    },
    {
        "metric": "open_exception_count",
        "value": int(
            (
                gold_exception_queue["review_status"]
                == "open"
            ).sum()
        )
    },
    {
        "metric": "total_exception_impact_gbp",
        "value": round(
            gold_exception_queue[
                "commercial_impact_gbp"
            ].sum(),
            2
        )
    }
])

print("Overall quality indicators:")
display(overall_quality_summary)

Overall quality indicators:

                            metric        value
0                  raw_table_count         9.00
1        full_exception_queue_rows    162235.00
2   dashboard_exception_queue_rows     10000.00
3    high_severity_exception_count      8113.00
4  medium_severity_exception_count     32446.00
5             open_exception_count    162235.00
6       total_exception_impact_gbp  99226897.19

In [162]:
# Save exception summaries and quality reports

exception_summary_path = (
    PROCESSED_DIR
    / "gold_exception_summary.csv"
)

prioritised_queue_path = (
    PROCESSED_DIR
    / "gold_prioritised_exception_queue.csv"
)

data_quality_summary_path = (
    PROCESSED_DIR
    / "data_quality_summary.csv"
)

overall_quality_summary_path = (
    PROCESSED_DIR
    / "overall_quality_summary.csv"
)

gold_exception_summary.to_csv(
    exception_summary_path,
    index=False
)

gold_prioritised_exception_queue.to_csv(
    prioritised_queue_path,
    index=False
)

data_quality_summary.to_csv(
    data_quality_summary_path,
    index=False
)

overall_quality_summary.to_csv(
    overall_quality_summary_path,
    index=False
)

print("Step 20 outputs saved:")
print(f" - {exception_summary_path}")
print(f" - {prioritised_queue_path}")
print(f" - {data_quality_summary_path}")
print(f" - {overall_quality_summary_path}")

Step 20 outputs saved:
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/gold_exception_summary.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/gold_prioritised_exception_queue.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/data_quality_summary.csv
 - /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/processed/overall_quality_summary.csv

In [163]:
# Review the most important exceptions

print("Highest-priority exception types:")
display(
    gold_prioritised_exception_queue
    .groupby(
        [
            "issue_type",
            "severity"
        ],
        as_index=False
    )
    .agg(
        exception_count=(
            "exception_id",
            "count"
        ),
        total_commercial_impact_gbp=(
            "commercial_impact_gbp",
            "sum"
        )
    )
    .sort_values(
        "total_commercial_impact_gbp",
        ascending=False
    )
    .head(20)
)

print("\nTop 20 exceptions for review:")
display(
    gold_prioritised_exception_queue[
        [
            "dashboard_rank",
            "exception_id",
            "issue_type",
            "partner_id",
            "country_code",
            "internal_sku",
            "order_id",
            "severity",
            "commercial_impact_gbp",
            "recommended_action"
        ]
    ]
    .head(20)
)

Highest-priority exception types:

,issue_type,severity,exception_count,total_commercial_impact_gbp
2,listing_inventory_disagreement,high,5013,18068617.38
6,stale_inventory,high,2448,8779754.27
3,listing_inventory_disagreement,medium,1167,2539448.79
4,listing_offline_or_paused,high,455,1609239.94
7,stale_inventory,medium,555,1207718.95
0,incomplete_listing_content,high,197,691713.62
5,listing_offline_or_paused,medium,126,274078.20
1,incomplete_listing_content,medium,39,84346.40

Top 20 exceptions for review:

,dashboard_rank,exception_id,issue_type,partner_id,country_code,internal_sku,order_id,severity,commercial_impact_gbp,recommended_action
0,1,EXC-0029892,listing_inventory_disagreement,CH_B,GB,SKU_000357,<NA>,high,18526.84,"Compare feed timestamps, reservations, and par..."
1,2,EXC-0018075,listing_inventory_disagreement,CH_A,ES,SKU_001423,<NA>,high,16773.22,"Compare feed timestamps, reservations, and par..."
2,3,EXC-0071728,stale_inventory,CH_A,ES,SKU_001423,<NA>,high,16773.22,Investigate feed freshness and confirm the exp...
3,4,EXC-0035798,listing_inventory_disagreement,CH_B,FR,SKU_001423,<NA>,high,16542.20,"Compare feed timestamps, reservations, and par..."
4,5,EXC-0066100,listing_inventory_disagreement,CH_D,GB,SKU_002787,<NA>,high,16465.92,"Compare feed timestamps, reservations, and par..."
5,6,EXC-0098298,stale_inventory,CH_D,GB,SKU_002787,<NA>,high,16465.92,Investigate feed freshness and confirm the exp...
6,7,EXC-0029470,listing_inventory_disagreement,CH_B,FR,SKU_000275,<NA>,high,14667.66,"Compare feed timestamps, reservations, and par..."
7,8,EXC-0018753,listing_inventory_disagreement,CH_A,GB,SKU_001535,<NA>,high,14567.28,"Compare feed timestamps, reservations, and par..."
8,9,EXC-0017929,listing_inventory_disagreement,CH_A,GB,SKU_001398,<NA>,high,14539.56,"Compare feed timestamps, reservations, and par..."
9,10,EXC-0023977,listing_inventory_disagreement,CH_A,GB,SKU_002365,<NA>,high,14188.32,"Compare feed timestamps, reservations, and par..."
10,11,EXC-0075000,stale_inventory,CH_A,GB,SKU_002365,<NA>,high,14188.32,Investigate feed freshness and confirm the exp...
11,12,EXC-0035795,listing_inventory_disagreement,CH_B,DE,SKU_001423,<NA>,high,13604.81,"Compare feed timestamps, reservations, and par..."
12,13,EXC-0031300,listing_inventory_disagreement,CH_B,GB,SKU_000621,<NA>,high,13578.95,"Compare feed timestamps, reservations, and par..."
13,14,EXC-0078967,stale_inventory,CH_B,GB,SKU_000621,<NA>,high,13578.95,Investigate feed freshness and confirm the exp...
14,15,EXC-0019520,listing_inventory_disagreement,CH_A,DE,SKU_001657,<NA>,high,13174.93,"Compare feed timestamps, reservations, and par..."
15,16,EXC-0072536,stale_inventory,CH_A,DE,SKU_001657,<NA>,high,13174.93,Investigate feed freshness and confirm the exp...
16,17,EXC-0000385,listing_offline_or_paused,CH_A,GB,SKU_000357,<NA>,high,12440.95,"Investigate source status, content requirement..."
17,18,EXC-0011286,listing_inventory_disagreement,CH_A,GB,SKU_000357,<NA>,high,12440.95,"Compare feed timestamps, reservations, and par..."
18,19,EXC-0011542,listing_inventory_disagreement,CH_A,DE,SKU_000405,<NA>,high,12410.42,"Compare feed timestamps, reservations, and par..."
19,20,EXC-0035802,listing_inventory_disagreement,CH_B,SE,SKU_001423,<NA>,high,12334.56,"Compare feed timestamps, reservations, and par..."

In [164]:
from pathlib import Path
import os

print("Current working directory:")
print(Path.cwd())

print("\nSearching for settlement_line_export.csv...")

matches = []

# Search the current folder and its parent folders
for folder in [Path.cwd(), *Path.cwd().parents]:
    candidate = folder / "data" / "raw" / "settlement_line_export.csv"
    if candidate.exists():
        matches.append(candidate)

# Also search common Mac project locations
for base_folder in [
    Path.home() / "Desktop",
    Path.home() / "Documents",
    Path.home() / "Downloads",
]:
    if base_folder.exists():
        matches.extend(
            base_folder.glob("**/settlement_line_export.csv")
        )

# Remove duplicates
matches = list(dict.fromkeys(matches))

print("\nMatches found:")
for match in matches:
    print(match)

if not matches:
    print("\nThe file was not found automatically.")
    print("Use the Jupyter file browser to locate your Meridian folder.")
else:
    raw_path = matches[0]
    print("\nUsing this file:")
    print(raw_path)

Current working directory:
/Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter

Searching for settlement_line_export.csv...

Matches found:
/Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/raw/settlement_line_export.csv
/Users/tanayajadhav/Desktop/meridian_partner_commerce_health/data/raw/settlement_line_export.csv

Using this file:
/Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/data/raw/settlement_line_export.csv

In [165]:
import pandas as pd

settlement_raw = pd.read_csv(raw_path)

print("Shape:", settlement_raw.shape)

print("\nColumns:")
print(settlement_raw.columns.tolist())

print("\nPotential type-related columns:")
print([
    column for column in settlement_raw.columns
    if any(term in column.lower() for term in ["type", "kind", "category", "class"])
])

print("\nFirst five rows:")
display(settlement_raw.head())

if "line_type" in settlement_raw.columns:
    print("\nline_type value counts:")
    print(settlement_raw["line_type"].value_counts(dropna=False))

Shape: (96712, 16)

Columns:
['statement_line_id', 'order_reference', 'partner_code', 'line_type', 'transaction_date', 'payout_date', 'currency', 'gross_amount', 'platform_fee', 'payment_fee', 'tax_withheld', 'refund_adjustment', 'manual_adjustment', 'net_amount', 'source_file', 'ingested_at']

Potential type-related columns:
['line_type']

First five rows:

,statement_line_id,order_reference,partner_code,line_type,transaction_date,payout_date,currency,gross_amount,platform_fee,payment_fee,tax_withheld,refund_adjustment,manual_adjustment,net_amount,source_file,ingested_at
0,SET-000000001,ORD-000000001,CH_A,NaN,2025-10-08,2025-10-29 19:19:09,€,32.74,-4.58,-0.62,-5.08,0.0,0.0,22.46,settlement_CH_A_20251029.csv,2025-10-30 01:19:09
1,SET-000000002,ORD-000000003,CH_C,NaN,29/08/2025,2025-09-09 05:46:06,EUR,68.78,-8.25,-1.78,-14.25,0.0,0.0,44.5,settlement_CH_C_20250909.csv,2025-09-12 04:46:06
2,SET-000000003,ORD-000000004,CH_C,NaN,2025-03-22 07:05:28,2025-04-11,Euro,83.17,-9.98,-2.21,-16.63,0.0,0.0,54.35,settlement_CH_C_20250411.csv,2025-04-13 10:05:28
3,SET-000000004,ORD-000000005,CH_A,NaN,2025-09-30,17/10/2025,EUR,46.78,-6.55,-1.11,-7.75,0.0,0.0,31.37,settlement_CH_A_20251017.csv,2025-10-18 18:38:34
4,SET-000000005,ORD-000000006,CH_C,NaN,14/05/2025,2025-05-23,Euro,115.8,-13.9,-3.32,-22.0,0.0,0.0,76.58,settlement_CH_C_20250523.csv,2025-05-26 03:57:09

line_type value counts:
line_type
NaN    96712
Name: count, dtype: int64

In [166]:
from pathlib import Path
import json

# Find the Meridian project root automatically
project_root = None

for folder in [Path.cwd(), *Path.cwd().parents]:
    if (folder / "data" / "raw").exists():
        project_root = folder
        break

print("Project root:", project_root)

if project_root is None:
    raise FileNotFoundError(
        "Could not find the Meridian project root containing data/raw."
    )

# Find all notebooks in the Meridian project
notebook_files = sorted(project_root.rglob("*.ipynb"))

print("\nNotebook files found:")
for notebook_file in notebook_files:
    print(notebook_file)

# Search notebook cells for settlement and line_type logic
print("\nCells containing settlement and line_type references:")

for notebook_file in notebook_files:
    try:
        notebook = json.loads(
            notebook_file.read_text(encoding="utf-8")
        )
    except Exception as error:
        print(f"Could not read {notebook_file}: {error}")
        continue

    for cell_number, cell in enumerate(
        notebook.get("cells", []),
        start=1
    ):
        cell_text = "".join(cell.get("source", []))

        lower_text = cell_text.lower()

        if "settlement" in lower_text and "line_type" in lower_text:
            print(f"\n--- {notebook_file.name}, Cell {cell_number} ---")
            print(cell_text)

Project root: /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter

Notebook files found:
/Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/.ipynb_checkpoints/01_syndata-checkpoint.ipynb
/Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/01_syndata.ipynb
/Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/02_business_analysis_and_kpis.ipynb

Cells containing settlement and line_type references:

--- 01_syndata-checkpoint.ipynb, Cell 64 ---
# Prepare synthetic settlement sales lines

settlement_rng = np.random.default_rng(RANDOM_SEED + 90)

partner_fee_rates = {
    "CH_A": 0.14,
    "CH_B": 0.16,
    "CH_C": 0.12,
    "CH_D": 0.18
}

sale_orders = order_header[
    order_header["order_status_clean"] != "cancelled"
].copy()

sale_orders = sale_orders.reset_index(drop=True)

sale_lines = pd.DataFrame()

sale_lines["settlement_line_type_clean"] = "SALE"

sale_lines["external_order_id_clean"] = (
    sale_orders["source_order_id"]
)

sale_lines["partner_id_clean"] = (
    sale_orders["partner_id_clean"]
)

sale_lines["currency_clean"] = (
    sale_orders["currency_clean"]
)

sale_lines["transaction_date_clean"] = (
    sale_orders["order_timestamp_clean"]
    + pd.to_timedelta(
        settlement_rng.integers(
            0,
            3,
            size=len(sale_orders)
        ),
        unit="D"
    )
)

sale_lines["payout_date_clean"] = (
    sale_lines["transaction_date_clean"]
    + pd.to_timedelta(
        settlement_rng.integers(
            7,
            22,
            size=len(sale_orders)
        ),
        unit="D"
    )
)

sale_lines["gross_amount_clean"] = (
    sale_orders["item_amount_clean"]
    - sale_orders["discount_amount_clean"]
    + sale_orders["shipping_amount_clean"]
).round(2)

sale_lines["platform_fee_clean"] = (
    sale_lines["gross_amount_clean"]
    * sale_lines["partner_id_clean"]
    .map(partner_fee_rates)
).round(2)

sale_lines["payment_fee_clean"] = (
    sale_lines["gross_amount_clean"]
    * settlement_rng.uniform(
        0.018,
        0.032,
        size=len(sale_orders)
    )
).round(2)

sale_lines["tax_withheld_clean"] = (
    sale_orders["tax_amount_clean"]
).round(2)

sale_lines["refund_adjustment_clean"] = 0.00
sale_lines["manual_adjustment_clean"] = 0.00

sale_lines["net_amount_clean"] = (
    sale_lines["gross_amount_clean"]
    - sale_lines["platform_fee_clean"]
    - sale_lines["payment_fee_clean"]
    - sale_lines["tax_withheld_clean"]
).round(2)

print("Sale settlement lines:", f"{len(sale_lines):,}")
display(sale_lines.head())

--- 01_syndata-checkpoint.ipynb, Cell 65 ---
# Create refund settlement lines from the return cases

refund_lines = pd.DataFrame()

refund_lines["settlement_line_type_clean"] = "REFUND"

refund_lines["external_order_id_clean"] = (
    return_case_base["source_order_id"]
)

refund_lines["partner_id_clean"] = (
    return_case_base["partner_id_clean"]
)

refund_lines["currency_clean"] = (
    return_case_base["source_currency"]
    .map({
        "GBP": "GBP",
        "£": "GBP",
        "Pound Sterling": "GBP",
        "EUR": "EUR",
        "€": "EUR",
        "Euro": "EUR",
        "SEK": "SEK",
        "kr": "SEK"
    })
    .fillna("GBP")
)

refund_lines["transaction_date_clean"] = (
    return_case_base["return_received_date_clean"]
)

refund_lines["payout_date_clean"] = (
    refund_lines["transaction_date_clean"]
    + pd.to_timedelta(
        settlement_rng.integers(
            5,
            20,
            size=len(refund_lines)
        ),
        unit="D"
    )
)

refund_lines["gross_amount_clean"] = 0.00
refund_lines["platform_fee_clean"] = 0.00
refund_lines["payment_fee_clean"] = 0.00
refund_lines["tax_withheld_clean"] = 0.00

refund_lines["refund_adjustment_clean"] = (
    -return_case_base["refund_amount_clean"]
).round(2)

refund_lines["manual_adjustment_clean"] = 0.00

refund_lines["net_amount_clean"] = (
    refund_lines["refund_adjustment_clean"]
)

# Create a small number of manual adjustments
adjustment_source = sale_orders.sample(
    n=max(1, int(len(sale_orders) * 0.012)),
    random_state=RANDOM_SEED
).copy()

adjustment_lines = pd.DataFrame()

adjustment_lines["settlement_line_type_clean"] = "ADJUSTMENT"

adjustment_lines["external_order_id_clean"] = (
    adjustment_source["source_order_id"]
)

unallocated_adjustment_mask = (
    settlement_rng.random(len(adjustment_source))
    < 0.30
)

adjustment_lines.loc[
    unallocated_adjustment_mask,
    "external_order_id_clean"
] = None

adjustment_lines["partner_id_clean"] = (
    adjustment_source["partner_id_clean"]
)

adjustment_lines["currency_clean"] = (
    adjustment_source["currency_clean"]
)

adjustment_lines["transaction_date_clean"] = (
    adjustment_source["order_timestamp_clean"]
    + pd.to_timedelta(
        settlement_rng.integers(
            3,
            15,
            size=len(adjustment_source)
        ),
        unit="D"
    )
)

adjustment_lines["payout_date_clean"] = (
    adjustment_lines["transaction_date_clean"]
    + pd.to_timedelta(
        settlement_rng.integers(
            7,
            25,
            size=len(adjustment_source)
        ),
        unit="D"
    )
)

adjustment_amounts = (
    settlement_rng.normal(
        loc=0,
        scale=12,
        size=len(adjustment_source)
    )
    .round(2)
)

adjustment_lines["gross_amount_clean"] = 0.00
adjustment_lines["platform_fee_clean"] = 0.00
adjustment_lines["payment_fee_clean"] = 0.00
adjustment_lines["tax_withheld_clean"] = 0.00
adjustment_lines["refund_adjustment_clean"] = 0.00
adjustment_lines["manual_adjustment_clean"] = adjustment_amounts
adjustment_lines["net_amount_clean"] = adjustment_amounts

print("Refund lines:", f"{len(refund_lines):,}")
print("Adjustment lines:", f"{len(adjustment_lines):,}")

--- 01_syndata-checkpoint.ipynb, Cell 66 ---
# Combine all settlement line types

settlement_clean = pd.concat(
    [
        sale_lines,
        refund_lines,
        adjustment_lines
    ],
    ignore_index=True
)

settlement_clean["settlement_line_id"] = [
    f"SET-{number:09d}"
    for number in range(
        1,
        len(settlement_clean) + 1
    )
]

print("Total settlement lines:", f"{len(settlement_clean):,}")

display(
    settlement_clean[
        "settlement_line_type_clean"
    ]
    .value_counts()
    .to_frame("line_count")
)

--- 01_syndata-checkpoint.ipynb, Cell 67 ---
# Convert settlement lines into an unfamiliar source format

def format_settlement_date(value, format_number):
    if format_number == 0:
        return value.strftime("%Y-%m-%d")
    elif format_number == 1:
        return value.strftime("%d/%m/%Y")
    else:
        return value.strftime("%Y-%m-%d %H:%M:%S")


def settlement_currency_alias(currency_code, format_number):
    aliases = {
        "GBP": ["GBP", "£", "Pound Sterling"],
        "EUR": ["EUR", "€", "Euro"],
        "SEK": ["SEK", "kr", "Swedish Krona"],
        "DKK": ["DKK", "kr", "Danish Krone"]
    }

    return aliases[currency_code][format_number]


n_settlement_lines = len(settlement_clean)

settlement_export = pd.DataFrame()

settlement_export["statement_line_id"] = (
    settlement_clean["settlement_line_id"]
)

settlement_export["order_reference"] = (
    settlement_clean["external_order_id_clean"]
)

settlement_export["partner_code"] = np.where(
    settlement_rng.random(n_settlement_lines) < 0.025,
    " " + settlement_clean["partner_id_clean"] + " ",
    settlement_clean["partner_id_clean"]
)

settlement_export["line_type"] = (
    settlement_clean["settlement_line_type_clean"]
)

transaction_date_formats = settlement_rng.integers(
    0,
    3,
    size=n_settlement_lines
)

settlement_export["transaction_date"] = [
    format_settlement_date(
        date_value,
        int(format_number)
    )
    for date_value, format_number in zip(
        settlement_clean["transaction_date_clean"],
        transaction_date_formats
    )
]

payout_date_formats = settlement_rng.integers(
    0,
    3,
    size=n_settlement_lines
)

settlement_export["payout_date"] = [
    format_settlement_date(
        date_value,
        int(format_number)
    )
    for date_value, format_number in zip(
        settlement_clean["payout_date_clean"],
        payout_date_formats
    )
]

currency_formats = settlement_rng.integers(
    0,
    3,
    size=n_settlement_lines
)

settlement_export["currency"] = [
    settlement_currency_alias(
        currency,
        int(format_number)
    )
    for currency, format_number in zip(
        settlement_clean["currency_clean"],
        currency_formats
    )
]

settlement_export["gross_amount"] = (
    settlement_clean["gross_amount_clean"]
)

settlement_export["platform_fee"] = (
    -settlement_clean["platform_fee_clean"]
)

settlement_export["payment_fee"] = (
    -settlement_clean["payment_fee_clean"]
)

settlement_export["tax_withheld"] = (
    -settlement_clean["tax_withheld_clean"]
)

settlement_export["refund_adjustment"] = (
    settlement_clean["refund_adjustment_clean"]
)

settlement_export["manual_adjustment"] = (
    settlement_clean["manual_adjustment_clean"]
)

settlement_export["net_amount"] = (
    settlement_clean["net_amount_clean"]
)

settlement_export["source_file"] = (
    "settlement_"
    + settlement_clean["partner_id_clean"]
    + "_"
    + settlement_clean["payout_date_clean"]
    .dt.strftime("%Y%m%d")
    + ".csv"
)

settlement_export["ingested_at"] = (
    settlement_clean["payout_date_clean"]
    + pd.to_timedelta(
        settlement_rng.integers(
            1,
            72,
            size=n_settlement_lines
        ),
        unit="h"
    )
)

print("Source-style settlement fields created.")
display(settlement_export.head())

--- 01_syndata-checkpoint.ipynb, Cell 71 ---
# Inspect the settlement and payout exports

print("Settlement line types:")
display(
    settlement_export["line_type"]
    .value_counts()
    .to_frame("line_count")
)

print("\nSettlement missing values:")
display(
    settlement_export.isna()
    .sum()
    .to_frame("missing_count")
    .sort_values(
        "missing_count",
        ascending=False
    )
)

print("\nSettlement sample:")
print(settlement_export.head(10).to_string())

print("\nPayout sample:")
print(payout_export.head(10).to_string())

--- 01_syndata-checkpoint.ipynb, Cell 86 ---
# Create a documented data-quality rule catalogue

dq_rule_catalog = pd.DataFrame([
    {
        "rule_id": "LIST-001",
        "table_name": "partner_listing_export",
        "field_or_fields": "source_partner_code",
        "rule_description": "Partner code must be present and map to the partner reference table.",
        "severity": "critical",
        "action": "quarantine",
        "business_rationale": "Without a partner identifier, the listing cannot be attributed or investigated."
    },
    {
        "rule_id": "LIST-002",
        "table_name": "partner_listing_export",
        "field_or_fields": "source_item_code",
        "rule_description": "Partner item code must be present after trimming whitespace.",
        "severity": "critical",
        "action": "quarantine",
        "business_rationale": "The product cannot be mapped without a usable partner item code."
    },
    {
        "rule_id": "LIST-003",
        "table_name": "partner_listing_export",
        "field_or_fields": "source_snapshot_date",
        "rule_description": "Snapshot date must parse into a valid date.",
        "severity": "high",
        "action": "quarantine",
        "business_rationale": "A record without a valid snapshot date cannot support trend or freshness analysis."
    },
    {
        "rule_id": "LIST-004",
        "table_name": "partner_listing_export",
        "field_or_fields": "source_market",
        "rule_description": "Country aliases must map to a recognised country code.",
        "severity": "high",
        "action": "correct_or_quarantine",
        "business_rationale": "Country attribution is required for international performance analysis."
    },
    {
        "rule_id": "LIST-005",
        "table_name": "partner_listing_export",
        "field_or_fields": "source_price",
        "rule_description": "Price must be parseable and non-negative.",
        "severity": "high",
        "action": "quarantine",
        "business_rationale": "Invalid prices can affect product availability and commercial reporting."
    },
    {
        "rule_id": "LIST-006",
        "table_name": "partner_listing_export",
        "field_or_fields": "source_stock",
        "rule_description": "Reported stock must be parseable and non-negative.",
        "severity": "high",
        "action": "quarantine_or_investigate",
        "business_rationale": "Invalid stock values can create false availability or overselling risk."
    },
    {
        "rule_id": "LIST-007",
        "table_name": "partner_listing_export",
        "field_or_fields": "source_listing_state",
        "rule_description": "Listing state must belong to the documented source-status vocabulary.",
        "severity": "medium",
        "action": "standardise_or_investigate",
        "business_rationale": "Status values drive live-listing and offline-item metrics."
    },
    {
        "rule_id": "LIST-008",
        "table_name": "partner_listing_export",
        "field_or_fields": "partner_code, item_code, snapshot_date",
        "rule_description": "Repeated business keys require investigation before deduplication.",
        "severity": "medium",
        "action": "retain_or_deduplicate_with_lineage",
        "business_rationale": "Repeated exports may be retries, amendments, or true duplicates."
    },
    {
        "rule_id": "INV-001",
        "table_name": "inventory_snapshot_export",
        "field_or_fields": "partner_code, item_code",
        "rule_description": "Partner and item identifiers must be present after trimming.",
        "severity": "critical",
        "action": "quarantine",
        "business_rationale": "Inventory cannot be reconciled without usable identifiers."
    },
    {
        "rule_id": "INV-002",
        "table_name": "inventory_snapshot_export",
        "field_or_fields": "available_qty, reserved_qty, inbound_qty",
        "rule_description": "Inventory quantities must be numeric and non-negative.",
        "severity": "high",
        "action": "quarantine_or_investigate",
        "business_rationale": "Invalid quantities can distort availability and stock-risk analysis."
    },
    {
        "rule_id": "ORDER-001",
        "table_name": "order_header_export",
        "field_or_fields": "source_order_id",
        "rule_description": "Order identifier must be present.",
        "severity": "critical",
        "action": "quarantine",
        "business_rationale": "Order lines, fulfilment events, returns, and settlement lines depend on the order identifier."
    },
    {
        "rule_id": "ORDER-002",
        "table_name": "order_header_export",
        "field_or_fields": "source_created_at",
        "rule_description": "Order timestamp must parse into a valid timestamp.",
        "severity": "high",
        "action": "quarantine",
        "business_rationale": "Order timing is required for trend, latency, and settlement analysis."
    },
    {
        "rule_id": "ORDER-003",
        "table_name": "order_header_export",
        "field_or_fields": "source_status",
        "rule_description": "Order status must map to the canonical status vocabulary.",
        "severity": "medium",
        "action": "standardise_or_investigate",
        "business_rationale": "Order status determines whether sales, cancellations, and refunds are included in KPIs."
    },
    {
        "rule_id": "LINE-001",
        "table_name": "order_line_export",
        "field_or_fields": "source_order_id, source_line_id",
        "rule_description": "Order and line identifiers must be present.",
        "severity": "critical",
        "action": "quarantine",
        "business_rationale": "A line without an order relationship cannot be reconciled."
    },
    {
        "rule_id": "LINE-002",
        "table_name": "order_line_export",
        "field_or_fields": "source_quantity",
        "rule_description": "Quantity must parse into a positive numeric value.",
        "severity": "high",
        "action": "quarantine",
        "business_rationale": "Quantity is required for units and order-value analysis."
    },
    {
        "rule_id": "SHIP-001",
        "table_name": "shipment_event_export",
        "field_or_fields": "external_order_id, line_ref, event",
        "rule_description": "Shipment event must have an order, line, and recognised event type.",
        "severity": "high",
        "action": "quarantine_or_investigate",
        "business_rationale": "Operational events must be connected to an order line."
    },
    {
        "rule_id": "RETURN-001",
        "table_name": "return_case_export",
        "field_or_fields": "return_id, external_order_id, line_ref",
        "rule_description": "Return identifier and order relationship should be present.",
        "severity": "high",
        "action": "quarantine_or_investigate",
        "business_rationale": "Returns must be connected to sales to calculate net revenue and return rates."
    },
    {
        "rule_id": "SETTLE-001",
        "table_name": "settlement_line_export",
        "field_or_fields": "statement_line_id, partner_code, line_type",
        "rule_description": "Settlement line must have a line identifier, partner, and recognised line type.",
        "severity": "critical",
        "action": "quarantine",
        "business_rationale": "Settlement lines must be attributable and classified."
    },
    {
        "rule_id": "SETTLE-002",
        "table_name": "settlement_line_export",
        "field_or_fields": "net_amount",
        "rule_description": "Net amount must be parseable as a monetary value.",
        "severity": "high",
        "action": "quarantine",
        "business_rationale": "Settlement reconciliation depends on a valid amount."
    },
    {
        "rule_id": "SETTLE-003",
        "table_name": "settlement_line_export",
        "field_or_fields": "order_reference",
        "rule_description": "Missing order references should be retained as unallocated settlement items rather than automatically deleted.",
        "severity": "medium",
        "action": "retain_and_flag",
        "business_rationale": "Aggregated or manual adjustments may legitimately lack an order-level reference."
    }
])

print(
    "Data-quality rules created:",
    len(dq_rule_catalog)
)

display(dq_rule_catalog.head(10))

--- 01_syndata-checkpoint.ipynb, Cell 116 ---
# Helpers for standardising settlement and payout currencies

partner_base_currency_map = (
    partner_ref
    .set_index("partner_id")["base_currency"]
    .to_dict()
)


def standardise_settlement_currency(
    currency_value,
    partner_id
):
    if pd.isna(currency_value):
        return pd.NA

    value = str(currency_value).strip()

    if value in ["GBP", "£", "Pound Sterling"]:
        return "GBP"

    if value in ["EUR", "€", "Euro"]:
        return "EUR"

    if value in ["SEK", "Swedish Krona"]:
        return "SEK"

    if value in ["DKK", "Danish Krone"]:
        return "DKK"

    # "kr" is ambiguous, so use the partner's base currency.
    if value == "kr":
        return partner_base_currency_map.get(
            partner_id,
            pd.NA
        )

    return pd.NA


settlement_line_type_map = {
    "SALE": "sale",
    "REFUND": "refund",
    "ADJUSTMENT": "adjustment"
}

--- 01_syndata-checkpoint.ipynb, Cell 117 ---
# Load and standardise settlement lines

raw_settlements = raw_tables[
    "settlement_line_export"
].copy()

silver_settlement_line = pd.DataFrame()

silver_settlement_line["source_row_number"] = (
    raw_settlements.index + 1
)

silver_settlement_line["settlement_line_id"] = (
    raw_settlements["statement_line_id"]
    .astype("string")

In [167]:
from pathlib import Path
import json

project_root = Path(
    "/Users/tanayajadhav/Desktop/meridian_partner_commerce_health"
)

notebook_paths = [
    project_root / "notebooks" / "jupyter" / "01_syndata.ipynb",
    project_root / ".ipynb_checkpoints" / "01_syndata-checkpoint.ipynb",
]

for notebook_path in notebook_paths:
    print("\n" + "=" * 80)
    print("NOTEBOOK:", notebook_path)
    print("EXISTS:", notebook_path.exists())

    if not notebook_path.exists():
        continue

    notebook = json.loads(
        notebook_path.read_text(encoding="utf-8")
    )

    for cell_number, cell in enumerate(
        notebook.get("cells", []),
        start=1
    ):
        cell_text = "".join(cell.get("source", []))

        if (
            "settlement_export" in cell_text
            or "settlement_line_export" in cell_text
            or "settlement_line_type_clean" in cell_text
        ):
            print(f"\n--- Cell {cell_number} ---")
            print(cell_text)

================================================================================
NOTEBOOK: /Users/tanayajadhav/Desktop/meridian_partner_commerce_health/notebooks/jupyter/01_syndata.ipynb
EXISTS: True

--- Cell 64 ---
# Prepare synthetic settlement sales lines

settlement_rng = np.random.default_rng(RANDOM_SEED + 90)

partner_fee_rates = {
    "CH_A": 0.14,
    "CH_B": 0.16,
    "CH_C": 0.12,
    "CH_D": 0.18
}

sale_orders = order_header[
    order_header["order_status_clean"] != "cancelled"
].copy()

sale_orders = sale_orders.reset_index(drop=True)

sale_lines = pd.DataFrame()

sale_lines["settlement_line_type_clean"] = "SALE"

sale_lines["external_order_id_clean"] = (
    sale_orders["source_order_id"]
)

sale_lines["partner_id_clean"] = (
    sale_orders["partner_id_clean"]
)

sale_lines["currency_clean"] = (
    sale_orders["currency_clean"]
)

sale_lines["transaction_date_clean"] = (
    sale_orders["order_timestamp_clean"]
    + pd.to_timedelta(
        settlement_rng.integers(
            0,
            3,
            size=len(sale_orders)
        ),
        unit="D"
    )
)

sale_lines["payout_date_clean"] = (
    sale_lines["transaction_date_clean"]
    + pd.to_timedelta(
        settlement_rng.integers(
            7,
            22,
            size=len(sale_orders)
        ),
        unit="D"
    )
)

sale_lines["gross_amount_clean"] = (
    sale_orders["item_amount_clean"]
    - sale_orders["discount_amount_clean"]
    + sale_orders["shipping_amount_clean"]
).round(2)

sale_lines["platform_fee_clean"] = (
    sale_lines["gross_amount_clean"]
    * sale_lines["partner_id_clean"]
    .map(partner_fee_rates)
).round(2)

sale_lines["payment_fee_clean"] = (
    sale_lines["gross_amount_clean"]
    * settlement_rng.uniform(
        0.018,
        0.032,
        size=len(sale_orders)
    )
).round(2)

sale_lines["tax_withheld_clean"] = (
    sale_orders["tax_amount_clean"]
).round(2)

sale_lines["refund_adjustment_clean"] = 0.00
sale_lines["manual_adjustment_clean"] = 0.00

sale_lines["net_amount_clean"] = (
    sale_lines["gross_amount_clean"]
    - sale_lines["platform_fee_clean"]
    - sale_lines["payment_fee_clean"]
    - sale_lines["tax_withheld_clean"]
).round(2)

print("Sale settlement lines:", f"{len(sale_lines):,}")
display(sale_lines.head())

--- Cell 65 ---
# Create refund settlement lines from the return cases

refund_lines = pd.DataFrame()

refund_lines["settlement_line_type_clean"] = "REFUND"

refund_lines["external_order_id_clean"] = (
    return_case_base["source_order_id"]
)

refund_lines["partner_id_clean"] = (
    return_case_base["partner_id_clean"]
)

refund_lines["currency_clean"] = (
    return_case_base["source_currency"]
    .map({
        "GBP": "GBP",
        "£": "GBP",
        "Pound Sterling": "GBP",
        "EUR": "EUR",
        "€": "EUR",
        "Euro": "EUR",
        "SEK": "SEK",
        "kr": "SEK"
    })
    .fillna("GBP")
)

refund_lines["transaction_date_clean"] = (
    return_case_base["return_received_date_clean"]
)

refund_lines["payout_date_clean"] = (
    refund_lines["transaction_date_clean"]
    + pd.to_timedelta(
        settlement_rng.integers(
            5,
            20,
            size=len(refund_lines)
        ),
        unit="D"
    )
)

refund_lines["gross_amount_clean"] = 0.00
refund_lines["platform_fee_clean"] = 0.00
refund_lines["payment_fee_clean"] = 0.00
refund_lines["tax_withheld_clean"] = 0.00

refund_lines["refund_adjustment_clean"] = (
    -return_case_base["refund_amount_clean"]
).round(2)

refund_lines["manual_adjustment_clean"] = 0.00

refund_lines["net_amount_clean"] = (
    refund_lines["refund_adjustment_clean"]
)

# Create a small number of manual adjustments
adjustment_source = sale_orders.sample(
    n=max(1, int(len(sale_orders) * 0.012)),
    random_state=RANDOM_SEED
).copy()

adjustment_lines = pd.DataFrame()

adjustment_lines["settlement_line_type_clean"] = "ADJUSTMENT"

adjustment_lines["external_order_id_clean"] = (
    adjustment_source["source_order_id"]
)

unallocated_adjustment_mask = (
    settlement_rng.random(len(adjustment_source))
    < 0.30
)

adjustment_lines.loc[
    unallocated_adjustment_mask,
    "external_order_id_clean"
] = None

adjustment_lines["partner_id_clean"] = (
    adjustment_source["partner_id_clean"]
)

adjustment_lines["currency_clean"] = (
    adjustment_source["currency_clean"]
)

adjustment_lines["transaction_date_clean"] = (
    adjustment_source["order_timestamp_clean"]
    + pd.to_timedelta(
        settlement_rng.integers(
            3,
            15,
            size=len(adjustment_source)
        ),
        unit="D"
    )
)

adjustment_lines["payout_date_clean"] = (
    adjustment_lines["transaction_date_clean"]
    + pd.to_timedelta(
        settlement_rng.integers(
            7,
            25,
            size=len(adjustment_source)
        ),
        unit="D"
    )
)

adjustment_amounts = (
    settlement_rng.normal(
        loc=0,
        scale=12,
        size=len(adjustment_source)
    )
    .round(2)
)

adjustment_lines["gross_amount_clean"] = 0.00
adjustment_lines["platform_fee_clean"] = 0.00
adjustment_lines["payment_fee_clean"] = 0.00
adjustment_lines["tax_withheld_clean"] = 0.00
adjustment_lines["refund_adjustment_clean"] = 0.00
adjustment_lines["manual_adjustment_clean"] = adjustment_amounts
adjustment_lines["net_amount_clean"] = adjustment_amounts

print("Refund lines:", f"{len(refund_lines):,}")
print("Adjustment lines:", f"{len(adjustment_lines):,}")

--- Cell 66 ---
# Combine all settlement line types

settlement_clean = pd.concat(
    [
        sale_lines,
        refund_lines,
        adjustment_lines
    ],
    ignore_index=True
)

settlement_clean["settlement_line_id"] = [
    f"SET-{number:09d}"
    for number in range(
        1,
        len(settlement_clean) + 1
    )
]

print("Total settlement lines:", f"{len(settlement_clean):,}")

display(
    settlement_clean[
        "settlement_line_type_clean"
    ]
    .value_counts()
    .to_frame("line_count")
)

--- Cell 67 ---
# Convert settlement lines into an unfamiliar source format

def format_settlement_date(value, format_number):
    if format_number == 0:
        return value.strftime("%Y-%m-%d")
    elif format_number == 1:
        return value.strftime("%d/%m/%Y")
    else:
        return value.strftime("%Y-%m-%d %H:%M:%S")


def settlement_currency_alias(currency_code, format_number):
    aliases = {
        "GBP": ["GBP", "£", "Pound Sterling"],
        "EUR": ["EUR", "€", "Euro"],
        "SEK": ["SEK", "kr", "Swedish Krona"],
        "DKK": ["DKK", "kr", "Danish Krone"]
    }

    return aliases[currency_code][format_number]


n_settlement_lines = len(settlement_clean)

settlement_export = pd.DataFrame()

settlement_export["statement_line_id"] = (
    settlement_clean["settlement_line_id"]
)

settlement_export["order_reference"] = (
    settlement_clean["external_order_id_clean"]
)

settlement_export["partner_code"] = np.where(
    settlement_rng.random(n_settlement_lines) < 0.025,
    " " + settlement_clean["partner_id_clean"] + " ",
    settlement_clean["partner_id_clean"]
)

settlement_export["line_type"] = (
    settlement_clean["settlement_line_type_clean"]
)

transaction_date_formats = settlement_rng.integers(
    0,
    3,
    size=n_settlement_lines
)

settlement_export["transaction_date"] = [
    format_settlement_date(
        date_value,
        int(format_number)
    )
    for date_value, format_number in zip(
        settlement_clean["transaction_date_clean"],
        transaction_date_formats
    )
]

payout_date_formats = settlement_rng.integers(
    0,
    3,
    size=n_settlement_lines
)

settlement_export["payout_date"] = [
    format_settlement_date(
        date_value,
        int(format_number)
    )
    for date_value, format_number in zip(
        settlement_clean["payout_date_clean"],
        payout_date_formats
    )
]

currency_formats = settlement_rng.integers(
    0,
    3,
    size=n_settlement_lines
)

settlement_export["currency"] = [
    settlement_currency_alias(
        currency,
        int(format_number)
    )
    for currency, format_number in zip(
        settlement_clean["currency_clean"],
        currency_formats
    )
]

settlement_export["gross_amount"] = (
    settlement_clean["gross_amount_clean"]
)

settlement_export["platform_fee"] = (
    -settlement_clean["platform_fee_clean"]
)

settlement_export["payment_fee"] = (
    -settlement_clean["payment_fee_clean"]
)

settlement_export["tax_withheld"] = (
    -settlement_clean["tax_withheld_clean"]
)

settlement_export["refund_adjustment"] = (
    settlement_clean["refund_adjustment_clean"]
)

settlement_export["manual_adjustment"] = (
    settlement_clean["manual_adjustment_clean"]
)

settlement_export["net_amount"] = (
    settlement_clean["net_amount_clean"]
)

settlement_export["source_file"] = (
    "settlement_"
    + settlement_clean["partner_id_clean"]
    + "_"
    + settlement_clean["payout_date_clean"]
    .dt.strftime("%Y%m%d")
    + ".csv"
)

settlement_export["ingested_at"] = (
    settlement_clean["payout_date_clean"]
    + pd.to_timedelta(
        settlement_rng.integers(
            1,
            72,
            size=n_settlement_lines
        ),
        unit="h"
    )
)

print("Source-style settlement fields created.")
display(settlement_export.head())

--- Cell 68 ---
# Add realistic settlement-source variations

# Allow monetary columns to contain both numeric and text formats
for column in [
    "gross_amount",
    "platform_fee",
    "payment_fee",
    "tax_withheld",
    "refund_adjustment",
    "manual_adjustment",
    "net_amount"
]:
    settlement_export[column] = (
        settlement_export[column]
        .astype("object")
    )

comma_decimal_mask = settlement_rng.random(
    n_settlement_lines
) < 0.018

for column in [
    "gross_amount",
    "platform_fee",
    "payment_fee",
    "tax_withheld",
    "refund_adjustment",
    "manual_adjustment",
    "net_amount"
]:
    affected_values = settlement_export.loc[
        comma_decimal_mask,
        column
    ]

    settlement_export.loc[
        comma_decimal_mask,
        column
    ] = (
        pd.to_numeric(
            affected_values,
            errors="coerce"
        )
        .round(2)
        .astype("string")
        .str.replace(".", ",", regex=False)
    )

# A small number of settlement lines have missing order references
# because they are aggregated or adjustment lines.
missing_reference_mask = settlement_rng.random(
    n_settlement_lines
) < 0.012

settlement_export.loc[
    missing_reference_mask,
    "order_reference"
] = None

settlement_path = RAW_DIR / "settlement_line_export.csv"

settlement_export.to_csv(
    settlement_path,
    index=False
)

print(f"Settlement export saved to: {settlement_path}")
print(f"Row count: {len(settlement_export):,}")
print(
    f"File size in MB: "
    f"{settlement_path.stat().st_size / 1024**2:.2f}"
)

--- Cell 71 ---
# Inspect the settlement and payout exports

print("Settlement line types:")
display(
    settlement_export["line_type"]
    .value_counts()
    .to_frame("line_count")
)

print("\nSettlement missing values:")
display(
    settlement_export.isna()
    .sum()
    .to_frame("missing_count")
    .sort_values(
        "missing_count",
        ascending=False
    )
)

print("\nSettlement sample:")
print(settlement_export.head(10).to_string())

print("\nPayout sample:")
print(payout_export.head(10).to_string())

--- Cell 86 ---
# Create a documented data-quality rule catalogue

dq_rule_catalog = pd.DataFrame([
    {
        "rule_id": "LIST-001",
        "table_name": "partner_listing_export",
        "field_or_fields": "source_partner_code",
        "rule_description": "Partner code must be present and map to the partner reference table.",
        "severity": "critical",
        "action": "quarantine",
        "business_rationale": "Without a partner identifier, the listing cannot be attributed or investigated."
    },
    {
        "rule_id": "LIST-002",
        "table_name": "partner_listing_export",
        "field_or_fields": "source_item_code",
        "rule_description": "Partner item code must be present after trimming whitespace.",
        "severity": "critical",
        "action": "quarantine",
        "business_rationale": "The product cannot be mapped without a usable partner item code."
    },
    {
        "rule_id": "LIST-003",
        "table_name": "partner_listing_export",
        "field_or_fields": "source_snapshot_date",
        "rule_description": "Snapshot date must parse into a valid date.",
        "severity": "high",
        "action": "quarantine",
        "business_rationale": "A record without a valid snapshot date cannot support trend or freshness analysis."
    },
    {
        "rule_id": "LIST-004",
        "table_name": "partner_listing_export",
        "field_or_fields": "source_market",
        "rule_description": "Country aliases must map to a recognised country code.",
        "severity": "high",
        "action": "correct_or_quarantine",
        "business_rationale": "Country attribution is required for international performance analysis."
    },
    {
        "rule_id": "LIST-005",
        "table_name": "partner_listing_export",
        "field_or_fields": "source_price",
        "rule_description": "Price must be parseable and non-negative.",
        "severity": "high",
        "action": "quarantine",
        "business_rationale": "Invalid prices can affect product availability and commercial reporting."
    },
    {
        "rule_id": "LIST-006",
        "table_name": "partner_listing_export",
        "field_or_fields": "source_stock",
        "rule_description": "Reported stock must be parseable and non-negative.",
        "severity": "high",
        "action": "quarantine_or_investigate",
        "business_rationale": "Invalid stock values can create false availability or overselling risk."
    },
    {
        "rule_id": "LIST-007",
        "table_name": "partner_listing_export",
        "field_or_fields": "source_listing_state",
        "rule_description": "Listing state must belong to the documented source-status vocabulary.",
        "severity": "medium",
        "action": "standardise_or_investigate",
        "business_rationale": "Status values drive live-listing and offline-item metrics."
    },
    {
        "rule_id": "LIST-008",
        "table_name": "partner_listing_export",
        "field_or_fields": "partner_code, item_code, snapshot_date",
        "rule_description": "Repeated business keys require investigation before deduplication.",
        "severity": "medium",
        "action": "retain_or_deduplicate_with_lineage",
        "business_rationale": "Repeated exports may be retries, amendments, or true duplicates."
    },
    {
        "rule_id": "INV-001",
        "table_name": "inventory_snapshot_export",
        "field_or_fields": "partner_code, item_code",
        "rule_description": "Partner and item identifiers must be present after trimming.",
        "severity": "critical",
        "action": "quarantine",
        "business_rationale": "Inventory cannot be reconciled without usable identifiers."
    },
    {
        "rule_id": "INV-002",
        "table_name": "inventory_snapshot_export",
        "field_or_fields": "available_qty, reserved_qty, inbound_qty",
        "rule_description": "Inventory quantities must be numeric and non-negative.",
        "severity": "high",
        "action": "quarantine_or_investigate",
        "business_rationale": "Invalid quantities can distort availability and stock-risk analysis."
    },
    {
        "rule_id": "ORDER-001",
        "table_name": "order_header_export",
        "field_or_fields": "source_order_id",
        "rule_description": "Order identifier must be present.",
        "severity": "critical",
        "action": "quarantine",
        "business_rationale": "Order lines, fulfilment events, returns, and settlement lines depend on the order identifier."
    },
    {
        "rule_id": "ORDER-002",
        "table_name": "order_header_export",
        "field_or_fields": "source_created_at",
        "rule_description": "Order timestamp must parse into a valid timestamp.",
        "severity": "high",
        "action": "quarantine",
        "business_rationale": "Order timing is required for trend, latency, and settlement analysis."
    },
    {
        "rule_id": "ORDER-003",
        "table_name": "order_header_export",
        "field_or_fields": "source_status",
        "rule_description": "Order status must map to the canonical status vocabulary.",
        "severity": "medium",
        "action": "standardise_or_investigate",
        "business_rationale": "Order status determines whether sales, cancellations, and refunds are included in KPIs."
    },
    {
        "rule_id": "LINE-001",
        "table_name": "order_line_export",
        "field_or_fields": "source_order_id, source_line_id",
        "rule_description": "Order and line identifiers must be present.",
        "severity": "critical",
        "action": "quarantine",
        "business_rationale": "A line without an order relationship cannot be reconciled."
    },
    {
        "rule_id": "LINE-002",
        "table_name": "order_line_export",
        "field_or_fields": "source_quantity",
        "rule_description": "Quantity must parse into a positive numeric value.",
        "severity": "high",
        "action": "quarantine",
        "business_rationale": "Quantity is required for units and order-value analysis."
    },
    {
        "rule_id": "SHIP-001",
        "table_name": "shipment_event_export",
        "field_or_fields": "external_order_id, line_ref, event",
        "rule_description": "Shipment event must have an order, line, and recognised event type.",
        "severity": "high",
        "action": "quarantine_or_investigate",
        "business_rationale": "Operational events must be connected to an order line."
    },
    {
        "rule_id": "RETURN-001",
        "table_name": "return_case_export",
        "field_or_fields": "return_id, external_order_id, line_ref",
        "rule_description": "Return identifier and order relationship should be present.",
        "severity": "high",
        "action": "quarantine_or_investigate",
        "business_rationale": "Returns must be connected to sales to calculate net revenue and return rates."
    },
    {
        "rule_id": "SETTLE-001",
        "table_name": "settlement_line_export",
        "field_or_fields": "statement_line_id, partner_code, line_type",
        "rule_description": "Settlement line must have a line identifier, partner, and recognised line type.",
        "severity": "critical",
        "action": "quarantine",
        "business_rationale": "Settlement lines must be attributable and classified."
    },
    {
        "rule_id": "SETTLE-002",
        "table_name": "settlement_line_export",
        "field_or_fields": "net_amount",
        "rule_description": "Net amount must be parseable as a monetary value.",
        "severity": "high",
        "action": "quarantine",
        "business_rationale": "Settlement reconciliation depends on a valid amount."
    },
    {
        "rule_id": "SETTLE-003",
        "table_name": "settlement_line_export",
        "field_or_fields": "order_reference",
        "rule_description": "Missing order references should be retained as unallocated settlement items rather than automatically deleted.",
        "severity": "medium",
        "action": "retain_and_flag",
        "business_rationale": "Aggregated or manual adjustments may legitimately lack an order-level reference."
    }
])

print(
    "Data-quality rules created:",
    len(dq_rule_catalog)
)

display(dq_rule_catalog.head(10))

--- Cell 117 ---
# Load and standardise settlement lines

raw_settlements = raw_tables[
    "settlement_line_export"
].copy()

silver_settlement_line = pd.DataFrame()

silver_settlement_line["source_row_number"] = (